### ISSUE TITLE
Please release old versions of the docs on readthedocs

### ISSUE THREAD

**Issue by white238** [ThePhD/sol2#1016]
Unfortunately I have a project that can't move forward to C++17 yet, so I was going to utilize your version 2.20.6 until we can.  Can you do and keep around a readthedocs build of version of 2.20.6?

**Comment by OrfeasZ** [comment]
Since all of the documentation source is stored in the repo, you can just build it yourself for the specific commit / tag you are on. Just run `make` in the `docs` directory and it should give you some details on the different options you have for building it. I believe you will need Python and [Sphinx](https://www.sphinx-doc.org/en/master/) for it to work.

**Comment by white238** [comment]
True, just an ease of use for customers of your project.  Readthedocs has this ability built in.  It is just a button click on the versions page to activate a version based on your git tag.  But it's your project, you can feel free to close the issue if this is not something you wish to support, as I can build your documentation myself with sphinx as you said.

**Comment by ThePhD** [comment]
I'm actually looking to move away from readthedocs and friends, so I wouldn't want to turn this feature on only to them blow it up in a month or two's time...

That being said; I turned it on anyways because I enjoy making bad decisions. :D

https://sol2.readthedocs.io/en/v2.20.6/

**Comment by white238** [comment]
I appreciate it.  I made sure to download the docs.  Hopefully next year all the codes that depend on our library will be C++17 and this wont be an issue.

**Comment by white238** [comment]
Curious as to why you want to move away from readthedocs though...
