### ISSUE TITLE
Variant recursive container type example

### ISSUE THREAD

**Issue by cleaton** [ThePhD/sol2#1022]
Hi, Thanks for the great project.
I was wondering if there's any examples for variant recursive container types that supports automatic conversion to lua table.
I am trying to push dynamic arguments to lua coroutines from a job queue and would like those arguments to convert into lua types automatically.

The following is the code I have now  but it does not compile due to illegal type conversion.
Any pointers on how to best solve this use case is greatly appreciated, thanks.
```
invalid user-defined conversion from ‘const sol::as_table_t<lua_table_t>’ to ‘const lua_table_t’ [-fpermissive]
  897 |     return p.push(L, std::forward<T>(t), std::forward<Args>(args)...);
```
code:
```c++
using lua_base_t = std::variant<int, double, std::string>;

struct lua_array_t;
struct lua_table_t;

using lua_all_t =
    std::variant<int, double, std::string, 
                 sol::as_table_t<lua_array_t>, sol::as_table_t<lua_table_t>>;
            

struct lua_array_t : std::vector<lua_all_t> {};

struct lua_table_t : std::map<lua_base_t, lua_all_t> {};

struct job
{
    sol::coroutine c;
    std::variant<std::tuple<>,std::tuple<lua_all_t>, std::tuple<lua_all_t, lua_all_t>> args;
}
```

**Comment by ThePhD** [comment]
Recursive variants would require you to write a custom checker / pusher for the type. You cannot use vanilla sol2 to support a recursive variant. Finally, `sol::as_table_t` is something that is generally used to tag things from function parameters or return values, not in classes in general.

I would also like to say that `sol::coroutine` is not a threaded thing, and so you might be setting yourself up for a footgun. A Lua coroutine (and sol2's coroutines) are not similar to `coroutine`s in C++ or other languages.

Finally, instead of doing this, you may want to simply store `sol::object`s instead and then do the discrimination, rather than trying to create recursive structures.

```
struct job {
     sol::protected_function work;
     std::vector<sol::object> arguments;
};

int main () {
     /* blah blah setup */
     job& j = scheduler.get_job();
     j.work(sol::as_args(j.arguments));
     /* stuff things teardown */
     return;
}
```

You can improve memory usage by not using `std::vector` but instead `std::array<sol::object, 2>` with an additional `int number_of_arguments;` to differentiate between 1, 2 and 3 arguments. Note that everything you are doing is runtime anyways, so trying to cram them all in `std::variant`s is likely not worth the effort unless you desperately need to avoid serialization.
