### ISSUE TITLE
How to solve this "Run function has exception 

### ISSUE THREAD

**Issue by gearslogy** [ThePhD/sol2#1025]
Hi,ThePhD:

I am writing a plug-in for a software. I want to bind a function in this software, and this function will return a value. **The function itself will have an exception first,** but the software itself will return the correct value based on the exception. **The problem is, sol will also catch this exception**, and then cause this function to fail to return the correct value according to its own exception.

How to run the functions registered in sol according to the logic of this third-party software?

the function documents:https://learn.foundry.com/katana/3.6/dev-guide/OpsAndOpScript/CookInterface/Cpp.html#katanaclassFoundry_1_1Katana_1_1GeolibCookInterface_1ae85e24171576e26670bcbcb826a2a505
```c
FnAttribute::Attribute getAttr(FnPlatform::StringView attrName, FnPlatform::StringView inputLocationPath = FnPlatform::StringView(), int inputIndex = kFnKatGeolibDefaultInput) const
```
Which highlights:
**Input scene graph locations which have not been cooked at the time of the query may throw an internal exception, aborting execution of the requesting Op. _Client code should not catch these exceptions,_ they are a signal to the the runtime to recook the Op when the inputs are ready.**

------------------
Let me first write that this function is called under normal C++ Plugin circumstances, 
Although there will be exceptions, the software will handle it by itself
```c
FnAttribute::StringAttribute att = iface.getAttr("type", "/root/world/geo/primitive1", 0);
std::string get;
if (att.isValid()) {
   get = att.getValue("", false);
}
```
-------------------------
 I bind this function to sol to call. sol will catch the execption that Cause the function to not run correctly
```c
auto getTypeFunc2 = [&iface](const std::string& inputLocation, const int& inputIndex) {
            std::string get;

            // The function itself will have an exception first,Then it will return the correct result
            FnAttribute::StringAttribute att = iface.getAttr("type", inputLocation,inputIndex);  
            if (att.isValid()) {
                get = att.getValue("", false);
                return get;
            }
            return get;
        };
lua->set("gettype", getTypeFunc2);
```

```
lua->save_script()
```
---------------------
I have tried to get rid of the exception by looking at your documentation:
```cmake
add_compile_definitions(SOL_NO_EXCEPTIONS=1 SOL_ALL_SAFETIES_ON=0 SOL_EXCEPTIONS_SAFE_PROPAGATION=0)
```
If you call the function like this, the software crashes directly

thanks

**Comment by ThePhD** [comment]
You cannot throw an exception through a C API and expect everything not to go to hell.

Lua is a C API. Throwing an exception through it will break everything, especially the Lua VM itself. Therefore, you need to change your function to behave differently. I recommend the following approach:

- Get something like [tl::expected](https://github.com/TartanLlama/expected).
- Change your function signature for the bindings to be something that returns `tl::expected<T, std::exception_ptr>`.
- If the function you are wrapping throws an exception, trap it and store it in an `exception_ptr` and return it.
- Exit the script if something goes wrong, returning the `exception_ptr` if there is one.
- Check if there is an exception pointer, and then rethrow.

# "Wow, that's way too complicated, what the hell."

Well, that's what happens when C VMs like Lua/LuaJIT mix with libraries that use exceptions for control flow of the program.

You can maybe try to make sol2 resistant to this by using the LuaJIT 2.1.0-beta{whatever} version, and then turn on `SOL_EXCEPTIONS_SAFE_PROPAGATION=1` or something similar. Then the exception might be able to pass through LuaJIT without taking everything down, but I don't recommend it.

Good luck.
