### ISSUE TITLE
Low performance when going over the Lua table on the C++ side

### ISSUE THREAD

**Issue by lhog** [ThePhD/sol2#1048]
C++17, MINGW64 environment, Lua 5.1

My Lua script is passing a lua array ~10k elements at the rate of about ~100 times per second (at frame/sec rate essentially) through a function, which is bound as userdata.

Lua part:
```
local array10k = {<10k floats, indexed from 1 to 10k>}
object:Upload(array10k, ...)
```

The corresponding C++ part:
```
Upload(const sol::table& luaTblData, ....) {

	std::vector<lua_Number> dataVec;
	dataVec.resize(luaTblData.size());

	for (auto k = 0; k < luaTblData.size(); ++k) {
		const auto& maybeNum = luaTblData.get<sol::optional<lua_Number>>(k + 1);
		dataVec.at(k) = maybeNum.value_or(static_cast<lua_Number>(0));
	}
}
```

This takes ~4 ms on the CPU side, which corresponds to around 15% of the whole draw frame cost.
Seems like I'm doing some operation inside the loop very-very inefficiently.

How would you write the loop above in the most performant way with sol2?

P.S. Very sad to see Discord gone, was an excellent place for sol2 community to meet and share ideas/issues.

**Comment by Rochet2** [comment]
Tests show that almost 2ms is spent on the for loop alone. This is probably because of the size() function call, which could be done just once. Also changed away from .at() since it seems its considered slower than other access methods.
```cpp
void Upload4(const sol::table& luaTblData) {
    auto size = luaTblData.size();
	std::vector<lua_Number> dataVec;
	dataVec.resize(size);

	for (auto k = 0; k < size; ++k) {
		dataVec[k] = luaTblData.raw_get_or<lua_Number>(k + 1, 0);
	}
}
```

The rest of the time is spent on getting a value from lua inside the loop. It seems that different methods of doing a get are roughly equal.
By dropping the error handling you can get some "significant" speed boost.
I am unsure what sol is doing under the hood in this case, but it cuts the time down to half. This code is fastest I could produce so far. The speed benefit of dropping the handling of non number value is 1ms.
If you are using `#define SOL_ALL_SAFETIES_ON 0` then an invalid value would be converted to 0 automatically and the handling isnt really needed.

```cpp
void Upload5(const sol::table& luaTblData) {
    auto size = luaTblData.size();
	std::vector<lua_Number> dataVec;
	dataVec.resize(size);

	for (auto k = 0; k < size; ++k) {
		dataVec[k] = luaTblData.raw_get<lua_Number>(k + 1);
	}
}
```

The timing of the code is around 1.5 ms.

**Comment by Rochet2** [comment]
You could maybe also consider not using a table, but a vector directly in lua.

**Comment by lhog** [comment]
Hi @Rochet2 !

Thanks a lot for the invaluable hint!
Indeed `auto size = luaTblData.size();` shaved off around 50% of the perf toll.

Perhaps you con elaborate on two questions:
* Can safety be disabled for the scope of some call or is `#define SOL_ALL_SAFETIES_ON 0` the only way?
* Re: `vector directly in lua` do you mean I should export some simplified vector class as userdata?

**Comment by Rochet2** [comment]
> Can safety be disabled for the scope of some call or is #define SOL_ALL_SAFETIES_ON 0 the only way?

Probably cannot disable it for a single call. Depends on what safety feature though.
Also above I actually incorrectly said that an invalid value would be converted to 0. That seems to happen for strings only, but tables etc. in the luaTblData would result in an error and not convert to a 0 value automagically.

> Re: vector directly in lua do you mean I should export some simplified vector class as userdata?

Yes, vector<lua_Number> itself, but of course you wouldnt need to expose all of the methods of that class.
Then there would be no need to convert from table to vector or similar. The traversing would be faster also and so.
However there may be other issues that you should evaluate, such as do you need to traverse the table in lua as that for example is probably slower for a vector than a lua table.

**Comment by ThePhD** [comment]
Sorry about the Discord, but I had to be sure everything was gone! Even my Discord ID should now be showing up as "Ghost"/"Deleted User".

As @Rochet2 has gotten you much closer to: yes, that's a good way to get rid of the problems. The last problem you have is the fact that you are using a "normal" table. That means sol2 stores it in the registry, and has to re-push its identity onto the Lua Stack every time it performs an operation. You can probably get some good gains by doing the following:

```cpp
void Upload4(sol::stack_table luaTblData) {
    // NOTE: above, we use stack_table instead of table
   // very dangerous if you accidentally unbalance / blow up the stack somewhere
   // tread lightly!!!
    auto size = luaTblData.size();
    // .size() is a O(logn) operation: lua does not store the size of a table in any property, and it's basically
   // doing fancy counting of nodes. That's why it must be hoisted out of the loop.
    std::vector<lua_Number> dataVec;
    dataVec.resize(size);

    for (auto k = 0; k < size; ++k) {
	dataVec[k] = luaTblData.raw_get<lua_Number>(k + 1);
    }
}
```

This stops the "pushing on every instance" issue. Note that if you have garbage data in there sol2 will likely just panic/crash you. In some configurations, it will return 0 or garbage data rather than crash horrifically.

**Comment by ThePhD** [comment]
Also as @Rochet2 pointed out: if you are not /making/ the data in Lua and making it instead in C++, you can cheat by just storing and using a `std::vector` in C++. It'll behave mostly the same way, and has lots of the methods you'd probably need for your vector type: https://sol2.readthedocs.io/en/latest/containers.html#container-operations

**Comment by lhog** [comment]
Hi @ThePhD !

Glad to see you again!

`Upload4()` got me some additional boost.
My use-case is that data (10k thing) come from Lua.

I tried passing:
```
std::vector<lua_Number> uploadVec;
uploadVec.reserve(10000);
lua["UploadVec"] = uploadVec;
```

and fill it up from Lua:
```
local function DoStuff()
  for i = 1, 10000 do
    UploadVec:add(math.random())
  end
end
DoStuff()
```

but it's twice slower than `Upload*`, so I guess I would go with `Upload4/Upload2`.

Huge thanks again @Rochet2 and @ThePhD !
