### ISSUE TITLE
How to deep clone a sol::table

### ISSUE THREAD

**Issue by roughbits01** [ThePhD/sol2#1063]
Sorry if this was asked before, I didn't find anything online. I'm looking for a way to deep clone a sol:table on the C++ side.

**Comment by ThePhD** [comment]
### Short Answer

I can't, that's for you to have to work out!

### Long Answer

You can, just not as perfectly or easily. It requires a lot of manual serializing to a real type, and then copying it over to the target table. Here's a small thread on how someone does it between 2 states: the principle is the same for between 2 tables: #991

I can't do this for you because I don't know -- as the library writer -- how I'm supposed to transfer your class from one place to another. You could create a system where you transfer over userdata by checking if they have a `:copy()` function on them, and then calling that to do a copy, and then putting that in the new table. `number`s are easy to copy over, `string`s are easy to copy over, `function`s are a bit more difficult, but bytecode serialization may help there: https://sol2.readthedocs.io/en/latest/tutorial/all-the-things.html#transferring-functions-dumping-bytecode

Good luck!

**Comment by roughbits01** [comment]
First of all thank you so much for taking the time to answer 🙂 Just to be clear I wasn't by any mean suggesting to add this to the library. Was just looking for examples of how can this be done. Thank you some much for the links will take a look. Also my table is created in lua (parsed from a file) and only contains strings, numbers and booleans so I guess it wouldn't be so much of a hassle to put in place.

**Comment by ThePhD** [comment]
Oh yeah, then that's super easy: the example in that issue should work just fine.

Maybe I should create a basic "serialization.cpp" example, and have a similar example there...

**Comment by roughbits01** [comment]
Yep that's what I did and it worked as expected! Thanks again for your help.
