### ISSUE TITLE
Cannot open lua.h

### ISSUE THREAD

**Issue by hsdk123** [ThePhD/sol2#1066]
Hi, it seems that even though I set
```
set(SOL2_BUILD_LUA ON)
```
I still get the error
```
Severity	Code	Description	Project	Line	File	Suppression State
Error	C1083	Cannot open include file: 'lua.h': No such file or directory	C:\Users\daego\Desktop\Projects\Light.vn-multi\core\out\build\x64-Release\Light.vn-multi	39	C:\Users\daego\Desktop\Projects\Light.vn-multi\core\out\build\x64-Release\_deps\sol2-src\include\sol\compatibility\lua_version.hpp	

```

**Comment by ThePhD** [comment]
That option is for testing purposes only and requires you to link the Lua libraries in using your CMake properly. I do not maintain a proper "Lua CMake"; just enough to get my tests by. I don't recommend you depend on it, because I _will_ break you.

But!

If you're okay with me smacking things around as I improve the CMake and being randomly broken, do this:

```cmake
target_link_libraries(whatever_your_library_application_whatever_is
    PRIVATE 
    sol2::sol2 
    ${LUA_LIBRARIES}
)
```

**Comment by ThePhD** [comment]
Good luck!
