### ISSUE TITLE
try/catch error has trash value

### ISSUE THREAD

**Issue by EToreo** [ThePhD/sol2#107]
I am getting different behavior on Linux and Windows here.  I am deliberately testing an undefined function in LUA.  (I'm testing that the error is passed back up to my C++ addon.)

LUA script:
```lua
badFunctionName(0);
```

```cpp
    try {
      // run the script now that everything has been defined
      lua.script(script);
    } catch (std::exception & e) {
      std::cout << "C++ ERROR: " << e.what() << std::endl;
      error = e.what();
    }
```

On Linux I get a full error: `C++ ERROR: lua: error: [string "badFunctionName(0);..."]:1: attempt to call a nil value (global 'badFunctionName')`
On Windows I get `C++ ERROR: ?` where `?` is a random character, usually something outside of traditional alpha/numeric.

**Comment by ThePhD** [comment]
Try taking a `const std::exception& e`. I'm assuming that it's not being copied proper since you're taking a plain reference, which in Windows is probably referring to dead memory. Also, remember that there's a bug if you have exceptions turned off in Windows regarding how it copies around memory associated with an exception. See [here](https://github.com/ThePhD/sol2/issues/85#issuecomment-219119099).

**Comment by EToreo** [comment]
I tried changing the catch to a cost ref, it does not improve the situation.  I am compiling with `/EHsc` set to turn on exception handling in Windows.

I read through the tread you linked and nothing popped out at me that I haven't already tried.  Any other thoughts?

**Comment by ThePhD** [comment]
Are you using luajit?

**Comment by EToreo** [comment]
Nope.  I compile native lua along with my source files.

**Comment by ThePhD** [comment]
I can't repro this between lua 5.2.4 or lua 5.3.2 . I get the error messages just fine. If something changes, let me know...
