### ISSUE TITLE
SOL_LUAJIT not defined and not documented

### ISSUE THREAD

**Issue by piotr-piatkowski** [ThePhD/sol2#1082]
I'm compiling with luajit-2.1, and I had problems with using `jit` module - it's not available even after I load it with `open_libraries`:

```
int main(int argc, char**argv) {
    sol::state lua;
    lua.open_libraries(
        sol::lib::base,
        sol::lib::jit
    );

    try {
        lua.safe_script("print('jit.version=' .. jit.version)");
    }
    catch(const sol::error &err) {
        cout << "Error: " << err.what() << endl;
    }
}
```
So this gives an error:
```
Error: sol: runtime error: [string "print('jit.version=' .. jit.version)"]:1: attempt to index global 'jit' (a nil value)
```

After some digging I found that I should define `SOL_LUAJIT` before including sol.hpp - and this helps and everything works fine, but shouldn't this be set automatically, or at least documented somewhere? I couldn't find any mention except for some closed issues discussions.

(BTW, why is `safe_script` throwing an exception? I expected it to just return `protected_function_result` - but it's throwing `sol::error` instead)

**Comment by ThePhD** [comment]
`SOL_LUAJIT` is automatically defined by detecting that `luajit.h` is available and include-able by checking `LUAJIT_VERSION`. Do you have a certain setup that triggers the specific kind of failure here? Are you mixing headers from normal Lua and Luajit?

`safe_script`, on a `panic` call (but not normal script error), will throw an exception. You can override this behavior in many different ways, including defining `SOL_DEFAULT_PASS_ON_ERROR`. I don't recommend that because it turns all `safe_script` calls and similar into things that just pass the error through naively. I might be able to decrease the danger by aggressively tagging many of the calls `[[nodiscard]]`.
