### ISSUE TITLE
API change regarding new_enum in SOL

### ISSUE THREAD

**Issue by seichter** [ThePhD/sol2#1089]
1. Produce any relevant imaginary code that illustrates what you would like or desired behavior.

In 2.20.6 I was able to add enums to a user type like so (ns is my namespace table) in a large system which I try to port.

```cpp
    ns.new_usertype<image>("image"
                           , sol::constructors<image()>()
                           ,"create",&image::create
                           ,"size",sol::readonly_property(&image::size)
                           ,"change_count",sol::property(&image::change_count,&image::set_change_count)
                           ).new_enum("layout" // this is what I can do with SOL2
                                      ,"rgb8", image::RGB8
                                      ,"rgb32", image::RGBA8
                                      ,"gray", image::LUM);

// in sol3 I need to get a temporary first and add the enum as a table separately

```
Porting to 3.2.2 new_type is now a private member. And I have to add the table for the enum separately. Was this change introduced by design or by accident?

2. Include a description and title of what you would like.

Preferably I would stick to the old API. However, if there was a good reason to change I am fine with that.

**Comment by ThePhD** [comment]
This was an intentional change to allow `new_usertype` to actually return a `sol::usertype` rather than `*this`. This is necessary because creating a `usertype` object and modifying it is much easier on compile-times than having one giant variadic function with all members listed. It also formalized the concept of having the `usertype` object, which someone could use to both register and deregister a usertype.

To fix, just move the `new_enum` call directly onto `ns` itself. This is probably frustrating but will only have to be done once. Apologies, v3 is a breaking API change!
