### ISSUE TITLE
Lua object that holds references to other objects

### ISSUE THREAD

**Issue by lhog** [ThePhD/sol2#1097]
Hey @ThePhD !

Need some help here.

I have a C++ object exposed to Lua via sol, that should hold the references to other objects of different class (also exposed to Lua) to the data from these objects later on.

It works fine when all objects are alive. But I'd like to prevent a situation when one of the referenced objects gets erroneously nil'ed by a user's code and Garbage Collected. In such cases an attempt to access GCed object causes crash. 
Some snippets to explain what I'm doing better:

Lua:
```
terrainVAO = gl.GetVAO() -- referencer object
terrainVertexVBO = gl.GetVBO() -- referenced object

terrainVAO:Attach(terrainVertexVBO)

terrainVertexVBO = nil
collectgarbage("collect")

--------------- Later
terrainVAO:DoSomething( ) -- causes crash.
```

CPP side:
```
class LuaVAOImpl {
....
public:
	void Attach(LuaVBOImpl& luaVBO) { vertLuaVBO =  &luaVBO; };
	void DoSomething( ) { vertLuaVBO->DoSomething(); }; //crash is here. Here I'm trying to access an object that has been GCed from Lua.
private:
	LuaVBOImpl* vertLuaVBO = nullptr;
````

Is there any way for sol to control lifetime of referenced objects explicitly or a better way for a one object to hold references to other objects?

**Comment by lhog** [comment]
Seems like replacing `gl.GetVBO()` to produce shared_ptr<LuaVBOImpl> and changing `Attach(shared_ptr<LuaVBOImpl>& luaVBO)` & shared_ptr<LuaVBOImpl> vertLuaVBO does the trick, but I'm not totally sure if it's a correct way.

**Comment by ThePhD** [comment]
It depends on what `gl.GetVBO()` is producing, as you have come to understand. If you return a value or a `unique_ptr`-like class, then Lua (sol2) takes ownership of that memory. If you are not careful with how you hand out references, then when the Lua memory dies, any references to the Lua memory in C++ (such as by a pointer or reference taken in a C++ function) also becomes fraudulent.

Using `std::shared_ptr` is one such way to prevent a leak, at the cost of taking out a lot of expensive copies. Another is to have `gl.GetVBO()` return a raw pointer and have a Resource Management System that exists outside of Lua, so that Lua is not managing the lifetime of anything.

**Comment by lhog** [comment]
Thanks a lot. Helpful as always!

**Comment by Leadwerks** [comment]
This was caused app by declaring the Editor class twice in sol. I was not able to recreate this in the web app above, but no matter.
