### ISSUE TITLE
How to call package methods ?

### ISSUE THREAD

**Issue by ensisoft** [ThePhD/sol2#1102]
Hi, sorry if this is a stupid question but I'm really struggling to find some examples that would not dump everything in the global scope. I.e. how to call a function a module (table). Assume the example below:

let's say this is my lua code:

```
MyGame = {... }

function MyGame:Tick() 
   print('tick')
   ....
end
```

This is the c++ code.

```
sol::state L;
L.open_libraries();
L.script_file("game.lua");
L["MyGame"]["Tick"](L["MyGame"]);
```

This seems to work but I doubt this is the "idiomatic" way this is supposed to be done... it's just way too ugly and also having to pass the table self parameter explicitly doesn't seem right. This might be that I'm just confused about how to use the lib properly but like I said I can't really find anything like this in the examples. 

I'm also interested to contribute some example code if needed once I wrap my own head around this. Thanks!

**Comment by atom0s** [comment]
The self-call tutorial example looks to be what you're trying to do:
https://github.com/ThePhD/sol2/blob/develop/examples/source/tutorials/quick_n_dirty/self_call.cpp

**Comment by ThePhD** [comment]
> This seems to work but I doubt this is the "idiomatic" way this is supposed to be done... it's just way too ugly and also having to pass the table self parameter explicitly doesn't seem right.

You can make it a little cleaner by just saving some variables, like using a `sol::table` as @atom0s has shown in the linked example:

```cpp
sol::state L;
L.open_libraries();
L.script_file("game.lua");

sol::table self = L["MyGame"];
self["Tick"](self);
```

There's no "member function"s in Lua. `MyGame:Tick()` is syntax sugar for `MyGame.Tick(MyGame)`. I can't do that "magical rewrite" for you in sol2, because one function call syntax needs to work for both "member functions" and normal functions. So, you need an explicit "self" parameter.

Not ideal, but that's the way it goes! If you really need some kind of special object that always passes "self", let me know and maybe I can design something.

**Comment by ensisoft** [comment]
@atom0s @ThePhD  Thanks for the quick replies. Ok, if that's the "right" way to make the function call then that's it and that's fine.
