### ISSUE TITLE
Userdata without Usertype

### ISSUE THREAD

**Issue by s5bug** [ThePhD/sol2#1123]
Converting a project that uses
```cpp
    Controller* controller = reinterpret_cast<Controller *>(lua_newuserdata(L, sizeof(Controller)));
    std::memset(controller, 0, sizeof(Controller));
```
to use sol.

This pointer gets mutated in other function calls, and holds some state data.

How do I get sol to allocate a `Controller*` (or a `Controller&`? or a smart pointer? I'm not at all experienced with C++) without having to go through the hassle of defining a usertype? And how do I then return that userdata from a function?

**Comment by ThePhD** [comment]
Answering things in reverse.

No Binding Necessary
=============

You don't need to bind a usertype in order to put it in and outside of sol2:

```cpp
lua_State* L; /* some pre-existing lua state in your Lua application */

int main () {
     sol::state_view lua(L);
     lua["meow"] = catte{};
     
     catte* p = lua["catte"];
     catte& p = lua["catte"];
     
     return 0;
}
```

For more on setting usertypes, see: https://sol2.readthedocs.io/en/latest/tutorial/all-the-things.html#c-classes-from-c

This covers also using `std::unique_ptr` and `std::shared_ptr`, which is as simple as: literally just using it there's no setup required lmao.

"I want to mess with memory directly"
========================

Memory layout for `lua_newuserdata` calls is a bit complex (not really) because we obey alignment and layouting rules. For like 97% of types this doesn't matter for shit, but we've run afoul fo some people's code because the alignment was wrong when they just went casting it. So,

take a look at these docs: https://sol2.readthedocs.io/en/latest/api/usertype_memory.html

In plain terms (completely ignoring memory alignment), that looks like this:

```cpp
    Controller** pp_controller = reinterpret_cast<Controller **>(lua_newuserdata(L, sizeof(Controller*) + sizeof(Controller)));
    Controller* p_controller = *(pp_controller + 1);
    *pp_controller = *p_controller;
    std::memset(p_controller, 0, sizeof(Controller));
```


But You Can Abstract That Away In Sol2
=========================

When you get more comfortable with sol2, you can actually leave these sections of your code alone and instead define **interop layers** instead: https://github.com/ThePhD/sol2/tree/develop/examples/interop

Replace "Kaguya" or "LuaBridge" with whatever bespoke thing your application is doing. The simplest example to see that from is this one: https://github.com/ThePhD/sol2/blob/develop/examples/interop/kaguya/source/kaguya.cpp

We use kaguya-special methods because that's what the example is, but you can replace it with your own functionality. This means that...

```
Controller* controller = lua["controller];
```

will invoke whatever special getters/checkers you define instead of the ones packaged with sol2.

**Comment by s5bug** [comment]
Got it, I think the first section of your answer is what I want.

[Did I accomplish it correctly?](https://github.com/hamhub7/tas-script/blob/0bf5d9e049bf9b961dd1322b53f1b65f970f2afd/source/lua_hiddbg.cpp)

**Comment by ThePhD** [comment]
Looks good to me. Both `Controller*` and `Controller&` will alias the memory directly in Lua and leave no copies, so you should be okay.

👍
