### ISSUE TITLE
Example of finding the reference to the caller of a method of a usertype's class?

### ISSUE THREAD

**Issue by alexandreburton** [ThePhD/sol2#1137]
Hello!

I am in a situation where it is relevant to know the Lua "context" within which a usertype's functions are being called. Looked at #715 and the "complicated" function of environment_snooping, as well as pure Lua debug facilities, but there a few gray zones (to me) in the interaction between the interpreter's stack and the Sol features. 

Specifically i'm binding class methods, and i'm looking for something such as: 

```C++
MyUserThing::generate() {
    auto caller_ref = get_my_lua_caller(); // maybe needing a lua_state pointer? or..?
    // etc.
}
```
where given this lua code:

```lua
thing_a:process(thing_b:generate())
```

during `thing_b`'s `generate()` execution, `caller_ref` would reference something that would let me reach `thing_a`.

doing this:

```lua
thing_a:generate()
```

would give me `caller_ref = sol::nil`, or some other way of knowing we're at the top level.

Instances of `MyUserThing` are created through a `lua_.set_function("make_a_thing" ...)` "factory" (not within Lua with the `:new()` constructor feature), if that makes a difference.

Thanks in advance!

**Comment by ThePhD** [comment]
https://sol2.readthedocs.io/en/latest/api/this_state.html

**Comment by ThePhD** [comment]
Note that you don't need to pass anything explicitly: it is a "transparent argument"

https://github.com/ThePhD/sol2/blob/develop/examples/source/this_state.cpp

**Comment by ThePhD** [comment]
I should probably answer the full question rather than let you stitch the thing up manually:

you'll need to put that reference somewhere.

"How do I get to `thing_a`?" By using `sol::this_state`, getting the state, and putting the `thing_a` in a place where `process()` can reach it. There is legitimately no "magic" I can perform for you here that does something like let you walk Lua's expression or call graph (as by the time these functions are called they're bytecode). Not even the Debug library helps you here, because you don't call `thing_a:process(...)` until `thing_b::generate()` is done; there's no way to explicitly associate the two, so you need to add that explicit association yourself with a C++ `thread_local` or by leaving something in the Lua State, which is a single-threaded entity that you know won't have locking issues (for a multi-threaded program).
