### ISSUE TITLE
A puzzling question?

### ISSUE THREAD

**Issue by wzhengsen** [ThePhD/sol2#1142]
* sol version: 3.2.3
* lua version: 5.4.2
* Visual Studio 2019
* Windows 10 x64

> code:
```c++
struct Test1 {
    Test1() { std::cout << 1 << std::endl; }
};
struct Test2 {
    Test2() { std::cout << 2 << std::endl; }
};
sol::state lua = {};

auto t1 = lua.new_usertype<Test1>("Test1");

// --------I can do this,compile pass--------
sol::table u2t = lua["Test1"];
u2t.new_usertype<Test2>("Test2");
//-------------------------------------------

// -----------I can't do this,compile error------------
// auto t2 = t1.new_usertype<Test2>("Test2");
// t1.as<sol::table>().new_usertype<Test2>("Test2");
// ----Why ban this way,they have the same behavior----

lua.script(R"(
    local t1 = Test1.new();
    local t2 = Test1.Test2.new();
)");
```

**Comment by ThePhD** [comment]
I don't think I went out of my way to ban that... can you make sure to use `t1.get<sol::table>().new_usertype<Test2>("Test2");` instead? The reason it's not named `as` is because proxy types do lookup.

In short, it does `t1.get(<sol::table>("Test2")`, which is different from converting the already-stored object (`sol::object`) into something by using `.as<T>()`.

**Comment by wzhengsen** [comment]
thanks for your anwser.
