### ISSUE TITLE
I cannot use the default construct to create an object with sol-v4.0.0-alpha.

### ISSUE THREAD

**Issue by wzhengsen** [ThePhD/sol2#1151]
* sol version: lastest version
* lua version: 5.4.2
* Visual Studio 2019
* Windows 10 x64

@ThePhD 
Thanks for your help, actually, I have 3 questions.

```c++
#include <string>
#include <iostream>
#include "sol/sol.hpp"

struct Test {
    void Print() {
        std::cout << "Print in C++." << std::endl;
    }
};
int main() {
    sol::state lua = {};
    lua.open_libraries();
    lua.new_usertype<Test>("Test",
        sol::meta_function::construct, sol::constructors<Test()>(),
        "_new", []() {return Test();},
        "Print", &Test::Print
        );
    lua.script(R"+*(
        -- Question one:
        -- Why Test.Print != Test.Print?
        if Test.Print == Test.Print then
            print("Test.Print == Test.Print");
        else
            print("Test.Print != Test.Print");
        end

        -- Question two:
        local test = Test._new();--This line is ok.
        --local test = Test.new();--This line raise a error "attempt to index a nil value (local 'test')"


        -- Question three:
        -- Why print "Print in C++."?
        -- I wrapped the "cppPrint" function with the "luaPrint" function and overridden Test.Print,
        -- but it doesn't seem to work?
        local cppPrint = Test.Print;
        local luaPrint = function(self)
            print("[Lua Print wrapper:]");
            cppPrint(self);
        end;
        Test.Print = luaPrint;
        test:Print();
    )+*");
    return 0;
}
```

**Comment by atom0s** [comment]
**Question 1:** sol creates a C-closure for indexed functions from a registered usertype that are not set as a lua_CFunction.
You can see this taking place in:
 - https://github.com/ThePhD/sol2/blob/f54138305d73a695889153a5122c17bebdab854e/include/sol/usertype_storage.hpp#L475
 - https://github.com/ThePhD/sol2/blob/f54138305d73a695889153a5122c17bebdab854e/include/sol/usertype_storage.hpp#L112


**Question 2:** Think your code was broken, as that works fine. 
The error you said would indicate you tried to index the wrong thing since it says 'test' in lowercase.


**Question 3:** This is by design if I recall and see correctly. You can accomplish this type of thing though via using your own metatable handling such as:
 - https://github.com/ThePhD/sol2/blob/f54138305d73a695889153a5122c17bebdab854e/examples/source/usertype_dynamic_get_set.cpp
 - https://github.com/ThePhD/sol2/blob/f54138305d73a695889153a5122c17bebdab854e/examples/source/overridable_function_members.cpp

There was a previous issue that was similar to this here: https://github.com/ThePhD/sol2/issues/583

You can also leave the field out of registration then you can set it from Lua such as the following. 
sol will always allow overrides if it was originated from Lua:

```lua
function Test:Print()
    print('asdf');
end

local test = Test:new();

test:Print(); -- prints: asdf

function Test:Print()
    print('asdf 1234');
end

test:Print(); -- prints: asdf 1234
```
