### ISSUE TITLE
How can I bind a function from a class member variable?

### ISSUE THREAD

**Issue by Wantcha** [ThePhD/sol2#1158]
I have a struct called CameraComponent. Inside that struct I have a few regular bools and one SceneCamera variable, called Camera, with a series of public functions. How can I go about binding those functions to Lua through the original struct?

I have for the regular variables

`type["primary"] = &CameraComponent::Primary`

but it seems I can't do

`type["SetOrthographic"] = &CameraComponent::Camera::SetOrthographic`

**Comment by ThePhD** [comment]
What does "seems I can't do" mean? Compiler error? Runtime error? Unexpected arguments?

**Comment by Wantcha** [comment]
> What does "seems I can't do" mean? Compiler error? Runtime error? Unexpected arguments?

I get an error on Camera, saying " name followed by "::" must be a class or namespace name "

**Comment by ThePhD** [comment]
Can you show me the full error? Can you post a code snippet that behaves similarly? What is `Camera`, here? A variable? A nested class name?

**Comment by Wantcha** [comment]
```
struct CameraComponent
	{
		SceneCamera Camera;
		bool Primary = true; //Could make the scene be responsible for this
		bool FixedAspectRatio = false;

		CameraComponent() = default;
		CameraComponent(const CameraComponent&) = default;
	};
```

`auto cameraComponent_type = m_State.new_usertype<CameraComponent>("CameraComponent", sol::no_constructor,
			"primary", &CameraComponent::Primary,
			"fixedAspectRatio", &CameraComponent::FixedAspectRatio,
			"SetOrthographic", &CameraComponent::Camera::SetOrthographic);`

That is the full compiler error, I'm afraid. This is how I define CameraComponent and bind it to Lua. SetOrthographic is simply a public function from the SceneCamera class.

**Comment by ThePhD** [comment]
Oh, you edited the post.

You need `type["SetOrthographic"] = &CameraComponent::SceneCamera::SetOrthographic`. This will bind the function `SetOrthographic` to the top-level `type`. This may not be what you intended, so you may be better off doing `new_usertype<SceneCamera>(...)` and binding all the relevant camera methods, then moving on from there.

If you need to modify taken arguments, then you can use `sol::property`, hand-written lambdas, and more, to bind what you want. https://github.com/ThePhD/sol2/blob/develop/examples/source/property.cpp

**Comment by Wantcha** [comment]
I see. The reason I didn't define SceneCamera as its own usertype was because I didn't want the user to have to type
' GetCameraComponent().Camera.SetOrthographic() '
but rather just
' GetCameraComponent().SetOrthographic() '

I know it's a bit cheaty and I wouldn't have had this problem if I didn't have SceneCamera in its own separate class in the first place, but I wanted to know if I can get away with it. Does the first solution you offered, the one where you bind the function to the top level type give me this result?

**Comment by ThePhD** [comment]
No, because it will expect a `SceneCamera` type to `SetOrthographic`, not a `CameraComponent`.

You can alleviate this by just writing functions that do what you want and then binding those:

```cpp
struct CameraComponent
	{
		SceneCamera Camera;
		bool Primary = true;
		bool FixedAspectRatio = false;

		CameraComponent() = default;
		CameraComponent(const CameraComponent&) = default;

		void SetOrthographic() {
			camera.SetOrthographic();
		}
	};

auto cameraComponent_type = m_State.new_usertype<CameraComponent>("CameraComponent",
			/* ... */
			"SetOrthographic", &CameraComponent::SetOrthographic);

```

"I have dozens, maybe even a hundred methods like this, this will take me forever!"

Sorry; there's no way I can make that desired magical syntax work. If Reflection was a real thing, maybe, but that's another 3-6 years off in C++ time.

If you never, ever bind the `SceneCamera` type anywhere, at all, directly and it is ONLY ever accessed through `CameraComponent` (for the ENTIRE application), you could get away with defining a `SceneCamera` extension point that, for the `SceneCamera` type, just gets the `CameraComponent` and then returns the `Camera` object. But this would mean every use of `SceneCamera&`/`const SceneCamera&`/`SceneCamera` in your function calls bound to Lua would need to *actually* be `CameraComponent`s, and not `SceneCamera`s.

If you meet those requirements and are sure you won't ever be surprised if things go poorly, well. Here's an example, you'll need to change the return types and how things are checked and such: https://github.com/ThePhD/sol2/blob/develop/examples/source/customization_convert_on_get.cpp

Good luck.
