### ISSUE TITLE
How to use sol::override when binding a sol::property

### ISSUE THREAD

**Issue by roughbits01** [ThePhD/sol2#1195]
Hey :) I'm not sure this is possible but I tried to find how to achieve it online with no luck. So I'm using a GUI library and I want to bind its classes to Lua. In my game I heavily use sol::property and try to avoid as much as I can the getter/setter syntax. One of the classes looks like this

```C++
class MyClass {
public:
    const UglyString& getStr() const;
    void setStr(const UglyString& str);

private:
    UglyString str;
};
```

In order to bind it with sol3 I would do something like this 

```C++
state.new_enum("my_class",
        ...
        "str", sol::property(&MyClass::getStr, &MyClass::setStr));
```

However I don't want to expose the string wrapper and do the conversion to std::string. This is possible using sol::overload but only works for functions (getter/setter). I'm wondering what's the best way to achieve this with sol::property?

Thanks in advance and thank you so much for creating a great library!

**Comment by ThePhD** [comment]
You need to create `pusher`s and `getter`s and `checker`s for this type. The docs are, unfortunately, underwhelming for this here but you can see a good example by looking at the code here:

https://github.com/ThePhD/sol2/blob/develop/examples/customization/source/lua_zm_interop.cpp#L8

and

https://github.com/ThePhD/sol2/blob/f56b3c698c2116f41aad3bf731ba8400e68c498b/tests/runtime_tests/source/customizations.cpp#L72

That should get you to pushing, checking, and getting an `UglyString` that works just fine with Lua. Note the use of `sol::types<TheCustomType>` tag in the `sol_lua_push/check/get` extension functions: you need to use this type otherwise you will get a lot of bad function calls suddenly manifesting.

**Comment by roughbits01** [comment]
Thank you so much. It worked! Found this tutorial which also helped https://blog.rubenwardy.com/2020/07/22/sol3-vector-extension/

**Comment by roughbits01** [comment]
Pasting here so it's useful for others :) 
```C++
namespace sol {

bool sol_lua_check(sol::types<UglyString>, lua_State* L, int index,
    std::function<sol::check_handler_type> handler,
    sol::stack::record& tracking)
{
    return sol::stack::check<std::string>(L, index, handler, tracking);
}

int sol_lua_push(sol::types<UglyString>, lua_State* L, const UglyString& c)
{
    return sol::stack::push(L, c.c_str());
}

UglyString sol_lua_get(sol::types<UglyString>, lua_State* L,
    int index, sol::stack::record& tracking)
{
    return sol::stack::get<std::string>(L, index, tracking);
}

}
```

**Comment by ThePhD** [comment]
🎉
