### ISSUE TITLE
Can't push variables onto stack when using this_state

### ISSUE THREAD

**Issue by poopings** [ThePhD/sol2#1202]
```cpp
class entity {
public:
	int get(sol::this_state L) {
		// same issue
		//int n = lua_tointeger(L, 1);
		//return 1;
		return sol::stack::push(L, 47);
	}
};

entity* ent = new entity;

int main() {
	sol::state lua;
	lua.open_libraries();

	lua["ent"] = ent;
	lua.new_usertype<entity>("entity",
        	"get", &entity::get
	);

	lua.script("function f(i) local var = ent:get(i) print(var) return var end f(20)");
}
```
Hello, me again. Having trouble pushing items onto stack when using the sol::this_state method of args. Just returns the amount of items pushed onto the stack and doesn't actually push it. Functions calls fine, but prints 1.

**Comment by poopings** [comment]
Have also tried
```cpp
class entity {
public:
	int get(int n, sol::this_state state) {
		lua_State* L = state;
		return sol::stack::push(L, 47);
	}
};
```

but it still doesn't work

**Comment by ThePhD** [comment]
Okay, now I am beginning to understand why you're doing this.

You are trying to translate what the Lua Manual, Tutorials, and other documentation written about/for Lua by blogs and others into sol2 and its bindings.

The way to interact with bindings is to simply bind a function that does work. You do not need to "push" anything. You do not need the state to do it. sol2 abstracts all of this away for you when you bind any kind of function. The way to properly push an integer from a member function is like so:

```cpp
class entity {
public:
	int get(int n, sol::this_state state) {
		return 47; // just the normal return value
	}
};
```

### "Okay, but I want to use Raw Lua with lower-level sol2 primitives instead"

Then you need to bind _raw, unprotected Lua functions_. See the tutorial, here: https://sol2.readthedocs.io/en/latest/functions.html#raw-functions-lua-cfunction

You do not get to mix-and-match the modes without using other primitives and setting up other things with sol2. Member functions do NOT count as "raw Lua functions": they cannot be stored as `lua_CFunction`s. That is, this does not compile:

```cpp
class entity {
public:
	int my_raw_function(lua_State* L) {
		return 0;
	}
};

int main () {
     lua_CFunction raw_lua = &entity::my_ra_function; // No.
     return 0;
}
```

A member function (or a stateful lambda or any other type of complex "callable") cannot be a raw Lua function with raw Lua-like semantics because they require additional information to call them properly that a `lua_CFunction` does not have.

### That being said...

Just bind your C++ code normally. You can even mix sol2 primitives to return things in fancy ways that serialize directly into Lua (see: https://github.com/ThePhD/sol2/blob/develop/examples/source/any_return.cpp#L6 | or: https://github.com/ThePhD/sol2/blob/develop/examples/source/as_returns.cpp#L11)

**Comment by poopings** [comment]
https://github.com/ThePhD/sol2/issues/77

This is actually what i'm trying to accomplish, it just wasn't included in my example. Would I be able to use sol::object as an alternative to pushing variables into stack if it doesn't work with member functions?

**Comment by poopings** [comment]
> 
> 
> Okay, now I am beginning to understand why you're doing this.
> 
> You are trying to translate what the Lua Manual, Tutorials, and other documentation written about/for Lua by blogs and others into sol2 and its bindings.
> 
> The way to interact with bindings is to simply bind a function that does work. You do not need to "push" anything. You do not need the state to do it. sol2 abstracts all of this away for you when you bind any kind of function. The way to properly push an integer from a member function is like so:
> 
> ```c++
> class entity {
> public:
> 	int get(int n, sol::this_state state) {
> 		return 47; // just the normal return value
> 	}
> };
> ```

Actually, I'm trying to perform this that you linked ( https://github.com/ThePhD/sol2/blob/develop/examples/source/any_return.cpp#L6) and/or this https://github.com/ThePhD/sol2/issues/77 but with the example you sent it's much more clear now. Thanks!
