### ISSUE TITLE
`SOL_NO_MEMORY_ALIGNMENT` is `SOL_ON` by default!

### ISSUE THREAD

**Issue by legends2k** [ThePhD/sol2#1215]
[Documentation on `SOL_NO_MEMORY_ALIGNMENT`][macro] says

> **Not** turned on by default under any settings: _this MUST be turned on manually_

However, `//include/sol/version.hpp` has it `SOL_ON` by default:

``` c
#if defined (SOL_NO_MEMORY_ALIGNMENT)
	#if (SOL_NO_MEMORY_ALIGNMENT != 0)
		#define SOL_ALIGN_MEMORY_I_ SOL_OFF
	#else
		#define SOL_ALIGN_MEMORY_I_ SOL_ON
	#endif
#else
	#define SOL_ALIGN_MEMORY_I_ SOL_DEFAULT_ON
#endif
```

[macro]: https://sol2.readthedocs.io/en/latest/safety.html#memory-config

**Comment by ThePhD** [comment]
Oh. That's hella wrong: my bad.

**Comment by Smertig** [comment]
I think there is no error. 

`SOL_ALIGN_MEMORY_I_` is on by default, not a `SOL_NO_MEMORY_ALIGNMENT` that is opposite.

**Comment by ThePhD** [comment]
I was looking at the branch inside `#if defined(SOL_NO_MEMORY_ALIGNMENT)`, but looking it over again I think that's right too.

I guess we'll all okay then!

**Comment by legends2k** [comment]
@Smertig / @ThePhD In that case should the documentation be updated to reflect the fact that `SOL_NO_MEMORY_ALIGNMENT` is not `ON` by default?

**Comment by ThePhD** [comment]
Ah, sorry. We're not being very clear here. The config you define, as a user, is `SOL_NO_MEMORY_ALIGNMENT`. That is, "please turn off memory alignment". Memory alignment is on by default: the configuration parameter inside is "Please USE memory alignment". It's the opposite of what the user defines. That's why it shows up like it does: the internal one is `SOL_ALIGN_MEMORY_I_`, which is why it defaults to `SOL_DEFAULT_ON`.

**Comment by legends2k** [comment]
Thanks for the explanation @ThePhD!
