### ISSUE TITLE
DLL Boundaries

### ISSUE THREAD

**Issue by inkadnb** [ThePhD/sol2#122]
Is it safe for Sol objects to cross DLL boundaries? I ask because the majority of the Sol code-base is reliant on the STL and I'm employing PIMPL in most of my project.

Most of the logic I have that utilizes Sol resides in a DLL that is used by an executable, however hydrating objects that rely on Sol and abiding to PIMPL is difficult. I was hoping I didn't need to link LuaJIT to both the DLL and Executable.

Any suggestions?

**Comment by ThePhD** [comment]
I'm going to be perfectly honest, I have no idea what the problem would be or why Sol is hard to use with PIMPL. :D

That being said, Sol is a header only library: with object declarations and implementations available to any code that uses it, I can only imagine the problem being you compiled with an older version of Sol wherein we changed the internal layout of a class. We've... actually never done that since the old repository: we've only implemented functions and stored things in the Lua VM, never actually changed data layouts. So, at the very least, that's constant and won't cause problems?

Again, I have no idea what you're trying to refer to. If you want to HIDE Lua, then no. Sol includes Lua directly, Sol is header only, therefore Lua API will be present alongside Sol. If you want to hide it, you'll need to make some kind of implementation-hiding wrapper or only use it in select implementation (CPP) files and keep it out of headers.

I am not sure what benefit you would have from hiding Sol / Lua in the implementation. Unlike <windows.h> or OpenGL, they don't introduce contentious macros and typedefs that can fight each other and the Lua API is more or less something you can pick and keep stable across all platforms.

**Comment by inkadnb** [comment]
Sorry, I was burning the midnight oil so I wasn't doing a very good job and explaining myself. I don't think the problem is an inherit issue of Sol, but perhaps more an environment/design issue. I'm ultimately concerned about having CRT objects cross DLL boundaries (see [Passing C/C++ Objects section](http://siomsystems.com/mixing-visual-studio-versions/))

I wasn't trying to hide it just for the sake of hiding it, more because I'm trying to avoid having CRT objects cross dll boundaries.

Currently my game engine is structured like so:
- gameengine.dll - houses most of the core engine logic
- driver.exe - houses game-play specific code

In gameengine I have a ScriptingEngine that is simple abstraction on top of Sol, one of it's members is a global lua state. When a script is loaded through a script object (another simple abstraction) it needs to somehow hit the global lua state in-order to call [require_file](http://sol2.readthedocs.io/en/latest/api/state.html#function-require-require-file) and store the resulting sol::object. Currently what I'm doing is letting the script load itself by grabbing the sol::state through the ScriptingEngine->getLuaState(); However, by doing this I'm allowing sol::state to cross the boundary between gameengine.dll and driver.exe, and because Sol implements the STL, CRT objects are also crossing that boundary which is generally frowned upon.

Is this something that's generally acceptable in cases like these?

**Comment by ThePhD** [comment]
Sol does not implement any of the STL.

Everything deriving from `sol::reference` / `sol::stack_reference` (e.g., every single type that matters in `Sol` and would likely cross DLL boundaries) do not include STL elements as part of its data layout and interface. They are based on having a `lua_State*` pointer and maybe an `int`: that's it. The only exception is a `std::unique_ptr` that resides in `sol::state`. However, keep in mind that you do not have to pass around the `sol::state` object around: simply handing out the `lua_State*` is enough, and somewhere else you can [continue to use the sol:: abstraction on top of any lua_State* with sol::state_view](http://sol2.readthedocs.io/en/latest/tutorial/existing.html).

I still have no idea if it's actually "DLL" safe but given the requirements you're talking about... yeah, don't really think you're gonna run into any problems.

**Comment by ThePhD** [comment]
I'm going to mark this as closed, since -- I think -- this will no longer be an issue for you. Good luck with your engine! Drop by and let me know how things roll out with it in a new issue if you like. :D
