### ISSUE TITLE
Returning table from Lua function as std::map [noob question]

### ISSUE THREAD

**Issue by Galicarnax** [ThePhD/sol2#1226]
After looking through the docs and examples, I still can't understand how I should go about having a function in Lua that returns a table (integer keys, string values) as `std::map<int, std::string>` into C++ side. I can see from the examples how to pass `std::map` into Lua as a table, but I need it the other way round. Sorry if I'm missing something really simple, but after spending some time I feel I need a small nudge in the right direction. I  see from examples ("table.cpp") how can I access table values from a table _variable_, but I need to have an entire table returning from a _function_. Something along these lines:
```c++
sol::state lua;
lua.script(R"(
   function f()
      local t = {}
      t[1] = "one"
      t[2] = "two"
      return t
   end
)");

std::map<int, std:string> result = lua["f"](); // this will not work, but then what?

```

**Comment by Rochet2** [comment]
Doing the conversion is not trivial. This is why its left for the embedder, you, to solve.
For example, how would one handle the case when values in the table are not of expected type?
Conversion also requires traversing the table, which is not always that fast.

https://sol2.readthedocs.io/en/latest/api/as_table.html
> the data cannot be gotten out back out in C++ as a C++ type

If you insist on using tables, you can either keep using the lua table in C++ or, if you must, you can do a conversion step between the two.

Instead of using tables in lua, you could expose `map<int, std::string>` to lua, which would work as you expect.
This seems to be already done by default: https://sol2.readthedocs.io/en/latest/containers.html
But you have to somehow create the initial map object I assume as I cant see an obvious way to make one.

Here is an example that shows all 3 approaches and omits error handling
https://godbolt.org/z/9cd7ddabx

<details>

```cpp
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

#include <map>
#include <string>

#include <iostream>

auto from_table(sol::table const& t) {
    std::map<int, std::string> result;
    for (auto const & e : t) {
        auto k = e.first.as<sol::optional<int>>();
        auto v = e.second.as<sol::optional<std::string>>();
        if (k && v) {
            result[*k] = *v;
        }
    }
    return result;
}

int main() {
    sol::state lua;
    lua.open_libraries(sol::lib::base, sol::lib::package);

    lua.script(R"(
    function f()
        local t = {}
        t[1] = "one"
        t[2] = "two"
        return t
    end
    )");

    std::cout << "Using lua table:" << std::endl;
    {
        sol::table result = lua["f"]();
        for (auto it : result) {
            std::cout << it.first.as<int>() << " " << it.second.as<std::string>() << std::endl;
        }
    }
    
    std::cout << "Converting from table:" << std::endl;
    {
        std::map<int, std::string> result = from_table(lua["f"]());
        for (auto it : result) {
            std::cout << it.first << " " << it.second << std::endl;
        }
    }

    std::cout << "Exposing cpp map:" << std::endl;
    lua["NewMap"] = [](){ return std::map<int, std::string>(); };
    lua.script(R"(
    function f()
        local t = NewMap()
        t[1] = "one"
        t[2] = "two"
        return t
    end
    )");
    {
        std::map<int, std::string> result = lua["f"]();
        for (auto it : result) {
            std::cout << it.first << " " << it.second << std::endl;
        }
    }
    return 0;
}
```

</details>

**Comment by Galicarnax** [comment]
Many thanks, this is that very nudge I looked for.

**Comment by ThePhD** [comment]
Thanks for helping with that, @Rochet2! I've been too swamped getting Unicode to work and helping take care of the li'l nephew, so I'm glad someone else is helping out here. 🎉
