### ISSUE TITLE
How to accept any data type in a single parameter ?? 

### ISSUE THREAD

**Issue by joyoussidd** [ThePhD/sol2#1283]
I have a function

```
data.set_function("InvokeAPI",  sol::overload([this](const std::string& FileObjectName, const std::string& Name) {
               return HandlerInstance.InvokeAPIFunction(FileObjectName, Name);
               },
               [this](const std::string& FileObjectName, const std::string& Name, sol::as_table_t<std::vector<std::string>> argumentList) {
               return HandlerInstance.InvokeAPIFunction(FileObjectName, Name, argumentList.source);
            }));
```

Now, I want that InvokeAPI accepts other data types as well, say for example vector of double. 
I tried overloading with sol::as_table_t<std::vector<double>> but it still calls the string overload version. 
What is the right way to achieve this and how can I call the double overload ?

**Comment by joyoussidd** [comment]
@ThePhD Can you please Guide ??

**Comment by ThePhD** [comment]
```cpp
auto invoke_api = [this](const std::string& FileObjectName, sol::object obj) {
     if (obj.is<std::string>()) {
          std::string Name = obj.get<std::string>();
          return HandlerInstance.InvokeAPIFunction(FileObjectName, Name);
     }
     else if (obj.is<std::vector<double>>()) {
          std::vector<double> Numbers = obj.get<std::vector<double>>();
          return HandlerInstance.InvokeAPIFunction(FileObjectName, Numbers);
     }
     // ... add more as you need
};
data.set_function("InvokeAPI",  std::move(invoke_api));
```

`sol::overload` - and the way this function is written - match on the first thing that works. So put it in the exact order that you need, otherwise something higher up in the if-else chain will trigger for something you don't intend. A good way to do this is to use the most specific type first, and then trail off to more and more general types.

Good luck!

**Comment by joyoussidd** [comment]
@ThePhD Thanks alot

**Comment by joyoussidd** [comment]
@ThePhD  I checked this but getting error with "get" member function.

Can I accept mix data types using sol::variadic_args ?? 
If its possible then how can I convert and store the mix elements QVariantList [An QT API which accepts any data type]

**Comment by joyoussidd** [comment]
@ThePhD Please reply sir

**Comment by ThePhD** [comment]
I don't know what "getting error with get member function" means since you haven't given me an example or anything. The code works for me, so I'd like some kind of example code or description of the actual error or problem.

You can use `sol::variadic_args` to get multiple different types, or multple of the same type, at any offset in the argument list. Here's an example: https://github.com/ThePhD/sol2/blob/develop/examples/source/variadic_args.cpp

it only gets `int` but you can pull any number of arguments you want out. If you know your types in advance you can just use `std::variant`.

**Comment by joyoussidd** [comment]
@ThePhD Ok thanks alot will try it out today
