### ISSUE TITLE
problem with std::shared_ptr's reference count

### ISSUE THREAD

**Issue by Ung0d** [ThePhD/sol2#129]
When I copy a shared_ptr into lua and then setting the value to nil, the instance in lua is not destructed as expected. Any suggestions how to fix that other then using raw-ptrs for lua refs instead?

```
#include <sol.hpp>
#include <iostream>
#include <memory>

struct TestMe
{
    TestMe() {}
    ~TestMe()
    {
        std::cout << "DESTRUCTED" << std::endl;
    }
};

int main()
{
    auto test = std::make_shared<TestMe>();

    sol::state lua;

    lua["test"] = test;
    std::cout << test.use_count() << std::endl; //prints 2 since we just copied the ptr into lua
    lua["test"] = sol::nil;
    std::cout << test.use_count() << std::endl; //still prints 2! why?

    return 0;
}
```

**Comment by ThePhD** [comment]
Because Lua runs on a Garbage Collection system and that might not trigger the "DESTRUCTED" until Lua deems that it needs to throw away that memory.

Note that when the Lua State is destroyed, that destructor runs.

If you are uncomfortable with these semantics, you will have to look into manipulating the garbage collector with the `lua_gc` function and other functions. Even then, calling `lua_gc(lua, LUA_GCCOLLECT, 0);` does not mean that "test" will be cleaned up.

**Comment by Ung0d** [comment]
Well, that completely ruins the point of shared_ptrs, since my objects stay alive for a random amount of time when I actually expect the reference counter to be 0. 

Since destructing the lua state indeed works, I will test performance when creating a local state each time a want to run a set of scripts. Do you generally suggest such an approach?

**Comment by ThePhD** [comment]
It doesn't make any sense at all, because once Lua takes a dependency on the memory it will delete it whenever it feels like. That's exactly how Garbage Collection works: see every garbage collected language ever invented for all time. The whole point of having a GC in a language is that you give up some control for the overall benefit of not explicitly managing your memory and perhaps some memory locality and up-front allocation benefits.

It would be nice if Lua's garbage collector wasn't an old dog from ages long ago, but it is. Both LuaJIT and the most recent iteration of Lua have interested in implementing a new GC that would behave better, but even then the language has no guarantee when your object would be destroyed.

The reason you'd use a `shared_ptr` with Lua is if you throw something into the Lua system, but don't know if the C++ version or the Lua version will die first. If you don't have a need for that, use a `std::unique_ptr`, `std::move` it into Lua, and then let Lua kill the memory without holding onto it in C++. Make sure nothing depends on the thing being deleted, and so whenever Lua destroys it things will be fine.

That's really all the advice I can give you. As I said earlier, you're dealing with GC in Lua, not C++'s RAII. You have no memory guarantees with the Lua Language.

**Comment by Ung0d** [comment]
I totally accept the GC "drawback" from lua, thanks anyway for clarifying the point. 
Funny thing is, the solution for me is as simple as this:

```
    auto test = std::make_shared<TestMe>();

    sol::state lua;

    lua["test"] = test;
    std::cout << test.use_count() << std::endl; //prints 2 since we just copied the ptr into lua
    std::shared_ptr<TestMe>& testBack = lua["test"];
    testBack.reset();
    lua["test"] = sol::nil;
    std::cout << test.use_count() << std::endl; //hurraayyy
```

As long as I forbid creating shared_ptr instance inside lua-code, that solves my problem. I reset the ptrs manually and dont care when GC destroys the empty wrappers left back.

Only problem left atm is about weak_ptrs. I have a weak_ptr instance registered in lua and want to use it. Since converting it to a local shared_ptr variable would again trigger the GC problem, I currently tend to call weak:lock() simply every time I use the weak_ptr. Like:

```
namespace sol
{
    template <typename T>
    struct unique_usertype_traits<std::weak_ptr<T>>
    {
        typedef T type;
        typedef std::weak_ptr<T> actual_type;
        static const bool value = true;

        static bool is_null(const actual_type& value)
        {
            return value.expired();
        }

        static type* get (const actual_type& p)
        {
            return p.lock().get();
        }
    };
}
```

Not really aesthetic, but it works. One last question: Any thoughts about that?

**Comment by ThePhD** [comment]
That looks a tad dangerous. `p.lock()` creates a new `std::shared_ptr`, and then you `.get()` the value out of it. Aside from holding onto a pointer value of a temporary shared pointer that's destructed by the time that `get` function has its value returned to the system (dangerous), can't really fault the code.

**Comment by JoshKlint** [comment]
I tried adding a function like this:
```
	void SOL_RESET_SHAREDPTR(shared_ptr<Model>& sptr)
	{
		sptr.reset();
	}
	lua.set_function("Delete",SOL_RESET_SHAREDPTR);
```
And then I tried it in Lua:
```
local model = CreateBox() --returns a shared_ptr<Model>
Delete(model)
```
The result was a shared_ptr in lua that had an invalid pointer and didn't know it. I'm not sure how, but it seems very dangerous.

**Comment by OrfeasZ** [comment]
@JoshKlint when you're allowing people to explicitly "delete" things you should also be prepared to handle cases where they might try to use something deleted. One way to avoid this issue is to follow standard lua semantics and handle deletion as part of the Garbage Collection process, where things are destroyed when they go out of scope and GC occurs. This of course may not fit with the programming model you're trying to create, in which case probably the best way to ensure someone can't break your program by trying to do things on deleted objects is to perform additional checks internally (inside your bound methods, etc.) to make sure your shared pointer is still holding a valid pointer.

**Comment by JoshKlint** [comment]
Yeah, I don't think it's a good idea. I'm okay with something like this:
```
local model = CreateBox()
model:Hide()
model = nil -- It will happen when it happens
```
Or this:
```
local model = CreateBox()
model = nil
collectgarbage()
```

**Comment by JoshKlint** [comment]
It really does seem like this should work:
```
void SOL_RESET_SHAREDPTR(shared_ptr<Entity>& sptr)
{
	sptr = nullptr;
}
```
The user is not deleting a Lua object, they are changing the state of the shared_ptr that Lua is passing around.

**Comment by ThePhD** [comment]
@JoshKlint So this is a problem of how memory is represented with "unique_usertype"s: http://sol2.readthedocs.io/en/latest/api/unique_usertype_traits.html

This means that the front-side of the `unique_usertype` (the pointer) isn't updated. A little bit unfortunate. There is a way to fix it, but I never provided the function to do it. I probably should.... but I'm heading off to class.

**Comment by ThePhD** [comment]
@JoshKlint Here's a potential fix, pushed to latest.

I can guarantee that this is probably a bad idea and will violate user expectations, but go crazy: https://github.com/ThePhD/sol2/blob/develop/examples/shared_ptr_modify_in_place.cpp

**Comment by JoshKlint** [comment]
Okay, this code will print false and then cause an exception:
```
if window:KeyHit(KEY_SPACE) then		
	Reset(model)
	print(model==nil) --prints false
	model:Hide()
end
```
Proper usage would be like this:
```
if window:KeyHit(KEY_SPACE) then		
	Reset(model)
	model = nil
end
```
For most types of objects it is perfectly fine to let them hang around a while before the garbage collector discards them. However, visible objects are an issue. At this point this is probably the best approach:
```
if window:KeyHit(KEY_SPACE) then		
	model:Hide()
	model = nil
end
```
However this is operating on the assumption that we know this is the only place the object is being used. Maybe some other part of the code is keeping the object alive and we don't actually want it hidden. We don't know. So in that case, maybe this is a bit better:
```
if window:KeyHit(KEY_SPACE) then		
	model:Hide()
	collectgarbage()
end
```
This is the solution we really want, but I don't know if it is possible:
```
if window:KeyHit(KEY_SPACE) then		
	Reset(model)
	print(model==nil) --prints true
end
```

**Comment by JoshKlint** [comment]
That second to last example should be like this. I can’t find an edit button on my phone:
‘’’
model = nil
collectgarbage()
‘’’

**Comment by ThePhD** [comment]
Lua does not support in-place type changing. This means that out parameters and function calls cannot fundamentally change the type of the variable that calls it / is called with it.

There's just nothing you can do. This is, of course, the problem with having a reference-based language that does not let the user override `operator=` for the current type, but only its children.

**Comment by JoshKlint** [comment]
Okay, this design is satisfactory. Thanks again for creating this library. My users are very excited about these new capabilities.
https://www.leadwerks.com/community/blogs/entry/2147-more-amazing-things-you-can-do-with-lua-in-leadwerks-5/

**Comment by ThePhD** [comment]
@JoshKlint That's great! Would you mind if I put that blog post in the Mentions page on the sol2 documentation?

**Comment by JoshKlint** [comment]
Sure. It's an unreleased product so nothing is 100% certain, but you are welcome to post that.

**Comment by JoshKlint** [comment]
See ya in 1-2 years 😉
