### ISSUE TITLE
Add create method for constructor

### ISSUE THREAD

**Issue by aster2013** [ThePhD/sol2#130]
Hi, I have a class like this.
```
class Image
{
public:
    Image(Context* context);
    //  ...
};
```
The context is a global object in C++, and I dont want to binding it to Lua.
So in Lua I want to create image object like this:
```
image = Image.new() or
image = Image()
```
How I do it?

**Comment by ThePhD** [comment]
See "initializers" for usertype: http://sol2.readthedocs.io/en/latest/api/usertype.html#usertype-constructor

````cpp
class Image
{
public:
    Image(Context* context);
    static void create( Image* i ) {
        std::allocator<Image> alloc;
        alloc.construct( i, &my_global_context_whatever );
        // -- ALTERNATIVELY
        new (i) Image(&my_global_context_whatever);
    }
//  ...
};

lua.new_usertype<Image>( "Image",
	"new", sol::initializers( Image::create )
);

````

It can be a free function or whatever. The docs specify how it works in a little bit more detail.

**Comment by mutex36** [comment]
I see you can use placement new to construct memory inside the lua stack.
But what if you want to allocate memory on the c++ heap? (in order to have a clear c++ ownership)

**Comment by ThePhD** [comment]
@mutex36 Use `sol::factory` and return a `std::unique_ptr`, or just make any old plain free functions and return what you want. Note that you should return a `unique_ptr` or `shared_ptr` so that Sol knows that it belongs to C++: passing in a pointer will result in a reference to the pointed-to object being made, and it will not preserve / copy what you give it.
