### ISSUE TITLE
Fail to add it to my project.

### ISSUE THREAD

**Issue by HuZhehua** [ThePhD/sol2#132]
Hi! I was trying to write a demo project using sol2 and got several question to ask you.
1. Does sol2 need to be compiled or installed? Why there is "#include <sol2.hpp>", and the source package you provide have two file named "sol2.hpp". I tried to include them separately and failed.

2. Does sol2 need boost as mandatory? If it only need optional.hpp, why folder Optional is empty?

Thanks for your attention!

**Comment by Nava2** [comment]
This is the only header you need: https://github.com/ThePhD/sol2/blob/develop/single/sol/sol.hpp
Your `Optional/` folder is empty because you didn't initialize the submodules: `git submodule init --recursive`. 

Check out the [tutorial](http://sol2.readthedocs.io/en/latest/tutorial/getting-started.html).

**Comment by ThePhD** [comment]
@Nava2 is right. 

This does remind me that I should add a note in the docs that you can also pull the repository and rely on the `single/sol/sol.hpp` if you want to be on the latest and greatest, all the time.

**Comment by ThePhD** [comment]
Now with a bit more explanation and documentation: http://sol2.readthedocs.io/en/latest/tutorial/getting-started.html
