### ISSUE TITLE
optional argument doesn't work in LuaJIT

### ISSUE THREAD

**Issue by THE-FYP** [ThePhD/sol2#137]
this code work fine in Lua 5.3.2, but in LuaJIT 2.0.4 causes strange behavior.
you can see in comments that the function without a return value doesn't cause any problems same as a function with multiple arguments, but function with one argument and any return value does.
```cpp
bool func1(sol::optional<int> i)
{
	if (i)
		std::cout << i.get() << std::endl;
	else
		std::cout << "optional isn't set" << std::endl;
	return true;
}

int func2(int i)
{
	std::cout << i << std::endl;
	return 1337;
}

void func3(int i)
{
	std::cout << i << std::endl;
}

bool func4(int i, int i2)
{
	std::cout << i << std::endl;
	std::cout << i2 << std::endl;
	return true;
}

int main(int, const char **)
{
	try
	{
		sol::state lua;
		lua.open_libraries();
		lua.set_function("func_opt_ret_bool", func1);
		lua.set_function("func_ret_int", func2);
		lua.set_function("func_ret_void", func3);
		lua.set_function("func_2_args", func4);
		lua.script(R"(
		func_ret_void(42)
		func_ret_void()
		print'ok'				-- works fine
		)");
		lua.script(R"(
		func_2_args(4, 2)
		func_2_args()			-- works fine
		print'ok'
		)");
		lua.script(R"(
		func_opt_ret_bool(42)
		func_opt_ret_bool()		-- interrupts script execution
		print'ok'
		)");
		lua.script(R"(
		func_ret_int(42)
		func_ret_int()			-- causes uncatchable exception
		print'ok'
		)");
	}
	catch (const std::exception& e)
	{
		std::cout << e.what() << std::endl;
	}
	catch (...)
	{
		std::cout << "unknown exception" << std::endl;
	}
	return _getch();
}
```
Lua output:
```
42
0
ok
4
2
0
0
ok
42
optional isn't set
ok
42
0
ok
```
LuaJIT output:
```
42
0
ok
4
2
0
0
ok
42
optional isn't set
42
0
```
tested on latest sol2 (2.9.0).

**Comment by ThePhD** [comment]
Lua 5.3.3 does not flip out nearly as much if you access indices that don't exist. LuaJIT is MUCH more stringent and will bite your hand if you don't give it what it expects (e.g., an integer argument).

Just dropping arguments from functions that get called into C++ is not supported. I'm not even sure that's valid Lua code. That thing has to have a value. That Lua hands you some semi-garbage default (0 for integers, nullptrs for userdata) is irrelevant to the fact that you're smearing honey on your face and then sticking it into a hornet's nest.

Provide `nil` for the arguments you don't use. Otherwise, Lua/LuaJIT will continue to behave weird. You should not be dropping arguments out of a function unless you specifically handle such a case (e.g. with `sol::variadic_arguments` as shown [here](http://sol2.readthedocs.io/en/latest/api/variadic_args.html)).

**Comment by ThePhD** [comment]
As a side note, your script would fail a bit more appropriately with `#define SOL_CHECK_ARGUMENTS` in place. See http://sol2.readthedocs.io/en/latest/safety.html

**Comment by THE-FYP** [comment]
so `sol::optional` does not affect function arguments? i think it should.
lua code
```lua
function func(a)
  a = a or 0
  return a
end
print(func(1))
print(func())
```
shows why.

**Comment by ThePhD** [comment]
`optional` more or less does this, but the problem arises when we have to calculate the number of arguments we need to pop off the stack. `optional` still expects 1 argument to be given to it, and pops one argument off the stack when Lua leaves.

I need to investigate how implementations operate this, so for now please pass `nil` to prevent stack breakages and smashes for now.

To address your other 3 examples in the original post:
What's trashing your script is the 3 other examples executing UB. Tou break the VM by making it pull things out that don't exist, and leave it up to the safety of the underlying machine (we catch these errors with `#define SOL_CHECK_ARGUMENTS`).

"func_ret_void" (`func3`) -- Shouldn't work, and is caught by `#define SOL_CHECK_ARGUMENTS`. That it works is simply implementation defined behavior of the system. At this point you've triggered UB in LuaJIT's implementation because pulling out an integer argument where there is none, basically accessing dead memory. This can also screw up the stack pointer and horribly gimp LuaJIT's runtime, silently inserting dead values and other bogus things into memory which leads to bugs that manifest themselves much later during script execution.

"func_2_args" (`func4`) -- shouldn't work for the same reasons as above. It's implementation-defined behavior, and Lua 5.3.3 is a LOT nicer about this than it has to be. LuaJIT by now has a potentially corrupted stack, so you're working with a nightmare. Also caught by `#define SOL_CHECK_ARGUMENTS`.

"func_ret_int" (`func2`) -- This should not work and crashes miserably, based on implementation-defined behavior of the Lua VM you use. `#define SOL_CHECK_ARGUMENTS` catches this, as I explained for "func_2_args" and "func_ret_void".

**Comment by ThePhD** [comment]
@THE-FYP So I went back and talked to people on the lua mailing list. Your `optional` code should work no problem now, and we should avoid hitting any kind of UB in the implementation.

Thanks for reporting this and making me check it over. Pull from latest or use the latest release.

Good luck!
