### ISSUE TITLE
Return values of a script

### ISSUE THREAD

**Issue by UltraEngine** [ThePhD/sol2#1476]
I want to run a script and get the returned value(s) in C++:
```lua
local component = {}

component.movement = Vec3(0)
component.rotation = Vec3(0)

function component.Update()
	self.entity:Move(self.movement)
	self.entity:Turn(self.rotation)
end

return component
```
Here is my simplied C++ function:
```c++
bool RunScript(const WString& path, std::vector<sol::stack_object>& results)
{
	// Load the script code
	std::string source = LoadString(path);

	// Get the stack size
	int stacksize - LuaGetStackSize(L);

	// Run the script
	Lsol->safe_script(source, path);

	// Get the number of return values
	int returnvalues = LuaGetStackSize(L) - stacksize;

	// Retrieve the return values
	for (int n = 0; n < returnvalues; ++n)
	{
		val = sol::staclk::??? // WHAT GOES HERE???
		results.push_back(val);
	}

	// Restore the stack size
	LuaSetStackSize(L, stacksize);

	return true;
}
```
Is my design basically correct? How to I retrieve a return value with sol? Will the returned values still be valid after the stack size is restored and the function returns?

**Comment by UltraEngine** [comment]
It looks like you have to know what you are looking for, You can't just return a list of generic values:
```c++
auto result = sol::stack::check_get<sol::table>(L);
```

**Comment by UltraEngine** [comment]
It's all coming back to me now...the good old crazy Lua stack commands
```c++
				auto r = sol::stack::check_get<sol::table>(L, before - after);
				if (r) 
				{
					auto component = make_shared<LuaComponent>();
					component->name = StripAll(path);
					sol::stack::push(L, As<Entity>());
					lua_pushvalue(L, -2);
					lua_setfield(L, -2, component->name.ToUtf8String().c_str());	
```

**Comment by Rochet2** [comment]
You may want to take a look at what happens when a script has an error.
Looks as if you might not have error handling yet there. Just a side note though.

> It looks like you have to know what you are looking for, You can't just return a list of generic values:

sol::object should be a generic "lua value" object.
But I guess if you are expecting a table, then maybe just fetch that.

For multiple returns if you know the amount of them, see [here](https://sol2.readthedocs.io/en/latest/tutorial/functions.html?highlight=multiple#multiple-returns-to-and-from-lua).
If you want arbitrary amount of returns, then the following code  works at least on sol 3.2.1. https://godbolt.org/z/9TT41b3sj

```cpp
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

#include <vector>
#include <iostream>

int main() {
    sol::state lua;
    lua.open_libraries();
    
    auto pfr = lua.safe_script("return 1,2,3");
    if (!pfr.valid()) {
        sol::error err = pfr;
        std::cout << err.what() << std::endl;
    }
    else
    {
        sol::variadic_results results = pfr;
        std::cout << results.size() << std::endl;
    }
    return 0;
}
```

> It makes me nervous that sol::optional is returning a reference to a table. If I store this table in a C++ variable will I be able to use it later, or do I need to ensure that Lua keeps it in memory?:

If you use the normal sol::table and similar types, then under the hood sol will create [a luaref](https://www.lua.org/manual/5.4/manual.html#luaL_ref) that is stored in the object. The ref is freed when the sol::table is destroyed (RAII). So you do not need to care about memory management if you store the sol::table etc types. The ref will keep it alive in lua until the ref is freed.

What you do need to keep in mind is that you do not want to destroy the objects on another thread as the destructor will access lua. And you should not close/destroy lua before destroying all of the reference objects (sol::table, sol::object etc) as the destructor will try to access lua instance that does not exist.

If you use some special stack type, like sol::stack_object, then the value may be freed by lua. For example lets say that during a function call you refere to a value on the stack, then after the function call ends lua can free that value.
Btw. seems that `sol::stack_` variants do not do RAII mechanics. So if one uses them, they should not expect stack to shrink when destroying a sol::stack_table for example.

>the good old crazy Lua stack commands

What you got there is alright.
I imagine something like this (not working code)
```cpp
auto pfr = lua.safe_script("return { 'hello' }");
if (!pfr.valid())
    return;

sol::optional<sol::table> t = pfr;
if (!t)
    return;

sol::stack_userdata entity = lua.push(this->As<Entity>()); // or sol::stack::push
entity["fieldname"] = t;
```

This is where I got, which is pretty close: https://godbolt.org/z/xs9G8TqsE

<details>

```cpp
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

#include <vector>
#include <iostream>

// Mock entity
struct Entity {
    int i = 0;
};

int main() {
    sol::state lua;
    lua.open_libraries();
    
    // quick mock binding that has the [] accessor
    sol::usertype<Entity> entity_type = lua.new_usertype<Entity>("Entity");
    entity_type[sol::meta_function::index] = []() {
        std::cout << "index" << std::endl;
    };
    entity_type[sol::meta_function::new_index] = []() {
        std::cout << "new_index" << std::endl;
    };

    // Some debug prints to see that stack is empty at the end
    std::cout << sol::stack::top(lua) << std::endl;
    {
        // Execute a script
        auto pfr = lua.safe_script("return { 'hello' }");
        // check for errors
        if (!pfr.valid())
            return 1; // For sake of brevity, leaving out error throwing
        
        // Make sure the value is a table (safely)
        sol::optional<sol::table> t = pfr;
        if (!t)
            return 2;
        
        sol::stack::push(lua, Entity { 42 }); // Emulates pushing As<Entity>()
        sol::stack::set_field(lua, "fieldname", t);
        sol::stack::pop<Entity>(lua); // We need to pop the entity. I couldnt find a clearner way to do this or have any RAII mechanic to achieve this
    }
    std::cout << sol::stack::top(lua) << std::endl;
    return 0;
}
```

</details>
