### ISSUE TITLE
How to pass a lua table to c++ code with call a C++ function in the Lua code

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#152]
c++ code:
```
// bind this function to lua
void func(sol::table t) {
    // t need passed from lua code
}
```

lua code:
```
// call func
local t = { 1, 2, 4 }
func(t)
```

But I found it didn't work, the sol::table t is not the table I want.

**Comment by ThePhD** [comment]
Why is it not the table you want? It looks fine to me. Here is a _complete_ code sample:

````cpp
void func (sol::table t) {
     // This function is called
     int is_1 = t[1];
     int is_2 = t[2];
     int is_4 = t[3];
}

int main () {
     sol::state lua;
     lua.set_function("func", func);
     lua.script("local t = { 1, 2, 4 }\nfunc(t)");
}
````

**Comment by aiplay** [comment]
Your code is work, but I write like this:

```
#include <sol.hpp>

void func (sol::table t) {
    int one = t[1];
    int two = t[2];
    int three = t[3];
    printf(" one : %d, two : %d, three : %d\n", one, two, three);
}

class A {
public:
    MatrixStack();
    ~MatrixStack();
}

int main() {
    sol::state lua;
    lua.new_usertype<A>("A", "func", func);
    lua.script("local a = A.new()\n
        a:func({ 1, 2, 3 })\n");
}
```

print result is 0 all.

**Comment by ThePhD** [comment]
Because you're using it wrong. `new_usertype` is for binding a new class type. "func" is just a function, and should be bound with either `set_function`, OR called using `a.func({ 1, 2, 3 })`. Note that we use the `a.` -- the dot -- and not `a:`. Colon is special in Lua and passes the thing before `:` as the first argument to the function.

To have less problems while you work and get errors when you run your code when things are bad, define `SOL_CHECK_ARGUMENTS`. This will throw an error message when you do something bad.

Here is your sample, rewritten with minor changes (that will also allow it to compile).

````cpp
#define SOL_CHECK_ARGUMENTS 1

#include <sol.hpp>
#include <cstdio>

void func(sol::table t) {
	int one = t[1];
	int two = t[2];
	int three = t[3];
	printf(" one : %d, two : %d, three : %d\n", one, two, three);
}

class A {
public:
	A() {}
	~A() {}
};

int main() {
	sol::state lua;
	lua.new_usertype<A>("A", "func", func);
	lua.script(R"(
        local a = A.new()
        -- does not work
        --a:func({ 1, 2, 3 })

        -- works as expected
        a.func({ 1, 2, 3 })
        A.func({ 1, 2, 3 })
    )");
}
````

Please also read the docs, which can show you proper ways to use Sol: http://sol2.readthedocs.io/en/latest/tutorial/all-the-things.html

If something is unclear in the docs, I would be happy to hear how to improve it to help you find your way.
