### ISSUE TITLE
Compile fail when bind member function with new_usertype, and the param is const pointer.

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#153]
Here is the code
```
#include "sol.hpp"

class A
{
public:
    A() {};
    ~A() {};
};

class B
{
public:
    B() {};
    ~B() {};
    void foo(const A* a) {};
}

int main(void)
{
    sol::state lua;
    lua.new_usertype<B>("B", "foo", &B::foo);
    return 0;
}
```

Compile fail, error:
**_stack_get.hpp:297:12: error: assigning to 'void *' from incompatible type 'const A *'
udata = detail::catch_cast<T>(udata, basecast);_**

**Comment by ThePhD** [comment]
This is a bug in my implementation. Sorry about that: I've got a fix ready and will push it soon.

Thanks for checking this over for me.

**Comment by aiplay** [comment]
Ok，did sol has email list or some discussion groups? Recently I intend to integrate sol into our project, although sol has tutorial and api manual, I still hope to have a way to consult some questions.

**Comment by nabijaczleweli** [comment]
GH Issues > mailing lists/discussion groups

**Comment by ThePhD** [comment]
GIthub Issues is the place to put them. A mailing list I've found to be discouraging, alongside forums: they often have month-old topics in them and that makes people feel like they'll receive no support if they post there.

Github, on the other hand, shows latest commit information and can also display recent issues. Issues are also easily searchable as well, so it makes it easier for people to find out things.

I am considering getting a Gitter for the real-time chat aspect, but that might be overdoing it (especially since I won't be available 24/7 to basically run support).

**Comment by nabijaczleweli** [comment]
Employ some Indians, maybe?

**Comment by ThePhD** [comment]
Fixed: https://github.com/ThePhD/sol2/releases/tag/v2.10.0
