### ISSUE TITLE
Working with `callable` structs

### ISSUE THREAD

**Issue by Nava2** [ThePhD/sol2#162]
Is there a means of working with `callable` structs? 

```C++
struct my_func {
  void operator()() { std::cout << "foo" << std::endl; }
};
```

I checked the docs, [here](http://sol2.readthedocs.io/en/latest/tutorial/functions.html?highlight=callable), but there's no reference to these structs and sol doesn't let you call them if you register them as udata.

**Comment by Nava2** [comment]
Further searching, revealed the [metatable docs](http://sol2.readthedocs.io/en/latest/api/metatable_key.html?highlight=metatable). This looks like a start. 

Perhaps this could be done automagically via the [`std::is_callable`](http://en.cppreference.com/w/cpp/types/is_callable) in the future/feature-gated?

**Comment by ThePhD** [comment]
There's a bit of an inconsistency here that I'm not sure how to properly solve.

````cpp
sol::state lua;
lua.set_function( "f", my_func() ); // registers it as a function
lua["f"] = my_func(); // registers it as a function
lua.set("f", my_func() ); // registers AS A USERDATA
````

`set` registers whatever `my_func()` is as a userdata, since it doesn't do the `is_callable` check. We have an `is_callable` trait in the codebase already (and we need it because VC++'s result_of / is_callable is busted, and that `std` trait is beyond C++14, which we have to avoid using for the sake of back compat).

I'm thinking I might add an explicit wrapper function available to everyone. The currently undocumented one is `sol::function_args( ... );`. I'll probably change it to `sol::as_function`, and it will explicitly invoke the function pusher instead of the userdata pusher.

**Comment by ThePhD** [comment]
http://sol2.readthedocs.io/en/latest/api/as_function.html

To be specific.

**Comment by Nava2** [comment]
Out of curiousity, does overloading work with as-function?

Kevin Brightwell

**Comment by ThePhD** [comment]
Should not be needed no matter the scenario with `overloaded`: If you mean `sol::as_function( sol::overload( ... ) )`, the `as_function` isn't necessary because `overload` provides a strong type that we know is a function. If you want `sol::overload( sol::as_function( obj ), ... );`, it's also redundant because we assume all things passed into `overload` are indeed functions.
