### ISSUE TITLE
new constructor for object - sol::(good_name_here) ?

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#168]
At the moment, we have `sol::object`, and like all stack-based objects it takes `(lua_State* L, int index)` as a constructo to make something. It has been proposed VIA e-mail that we should perhaps figure out a way to allow a person to do `make_object`, but without the `make_object` function and instead invoking a constructor with `sol::object`.

As it stands, `sol::object o(lua_State* L, sol::in_place, arg, ...)` might be a good candidate, as well as. `sol::object o(lua_State* L, sol::in_place<T>, arg, ...)` to be more specific? Taaaad wonky, though, and the syntax is a bit long... but, it does follow with other `in_place` styles of construction (see new things in the [`std::`](http://en.cppreference.com/w/cpp/utility/in_place)).

@eliasdaler Thoughts here, since this was also of interest to you?

**Comment by eliasdaler** [comment]
`in_place` looks good and the interface is okay and I doubt that anything can be done about this. `in_place<T>` is a good idea as we don't have `T` in `sol::object` (we do have it in some stuff like `std::optional`, it's a template argument).
The type can be deducted when user passes only one arg, for example `sol::object o(L, sol::in_place, 5);` will contruct and `int`. It's unclear what you can do with a bunch of random args, that's why passing `sol::in_place<T>` is needed.

I think that it'd be great to have shorter overload without `in_place`: `sol::object::object(lua_State* L, T&& arg)` which will do the same thing as `sol::make_object`.

**Comment by ThePhD** [comment]
I can't do `sol::object::object( lua_State* L, T&& arg )` because it's a breaking change with an existing constructor, `sol::object::object( lua_State* L, int stack_index );`. I'm all for making the API better, and in hind sight it probably would have been smart of me to do as you said and make some kind of strong typedef for the `stack_index` version, like `sol::object::object( lua_State* L, index_t stack_index );`. Problem is, `sol`'s been released for a while, that constructor's a public, documented constructor, and people have taken source-code level dependencies on it. I took breaking changes when moving from sol1 -> sol2, but I can't really do another breaking change like that until I go from `sol2` -> `sol3`, so I need to get creative. :(

**Comment by eliasdaler** [comment]
Oh, fair enough. Passing `sol::in_place` (or something else to trigger overload) really looks like the only way to do it for now. 

Maybe something more descriptive than `in_place` would be cooler though. It's pretty obvious what will be created in place and what will be copied. (rvalue - in place, lvalue - copy / ref). Something like `sol::object o(L, sol::in_place, someObject);` doesn't make much sense, because the copy will be made.

**Comment by ThePhD** [comment]
Documented here: http://sol2.readthedocs.io/en/latest/api/object.html#overloaded-constructor-object

**Comment by eliasdaler** [comment]
Awesome!

Btw, some typos in docs which I'm very lazy to fix myself:

"One allows construction of a**N** object from other reference types such as sol::table and sol::stack_reference. The secon**D** creates an object which references the specific element at the given index in the specified lua_State*. "

**Comment by ThePhD** [comment]
Thanks, fixed!
