### ISSUE TITLE
Set two different C++ function to Lua but have the same name, only execute the second

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#169]
Here is my code

```
#include "stdio.h"
#include "sol.hpp"

void a(int a)
{
    printf("a : %d\n", a);
}

void b(int b)
{
    printf("b : %d\n", b);
}

int main(void)
{
    sol::state lua;
    lua.set_function("a", a);
    lua.set_function("a", b);
    lua.script("a(1)");
    return 1;
}
```

Base on the print, only function b is called except function a.
And, should Sol give some prompt that can not set two diffrent function for the same key?

**Comment by ThePhD** [comment]
This is the expected behavior of the Lua language and the API.

Think about what you're asking. How would `a(1)` know to call a, versus b, in that situation? Even if you [overloaded](http://sol2.readthedocs.io/en/latest/api/overload.html) it, it would be completely insane for Lua to just "alternate between" or "pick one of the two to call at random" when the call (which is `a(1)`) is identical every time.

**Comment by aiplay** [comment]
I mean is sol should know "a" has been set, when I set for second time, let me know "a" has been set and whether to change set the other name.

**Comment by ThePhD** [comment]
You need to explicitly check if it exists:

````cpp
sol::state lua;
auto a_proxy = lua["a"];
if (a_proxy.valid()) {
     std::cout << "first check, it exists" << std::endl;
}
lua["a"] = 50;
if (a_proxy.valid()) {
     std::cout << "second check, it exists" << std::endl;
}
````
