### ISSUE TITLE
Return a pointer from C++ method to Lua and sending that pointer from Lua to other method 

### ISSUE THREAD

**Issue by bazi-nevis** [ThePhD/sol2#174]
Hi
I want to be able to return a pointer from C++ method to Lua and sending that pointer from Lua to other method. For example I have a method like this:

````
SceneGroupNode* GraphicsEngineFacade::GetSceneGraphRoot() {
    return scene_.GetSceneRootNode();
}
````

This method returns a pointer that I want to send that to following method:

`void CreateTexturedTriangle(SceneGroupNode* parent);` 

I used sol2 like this to introduce it to the Lua:

`lua_state_.new_usertype<GraphicsEngineFacade>("GraphicsEngineFacade",
      "CreateTexturedTriangle", &GraphicsEngineFacade::CreateTexturedTriangle,
      "GetSceneGraphRoot", &GraphicsEngineFacade::GetSceneGraphRoot);`

In Lua I want to get that pointer and sent it to the CreateTexturedTriangle method.
How can I do this? When I use the pointer in C++ I get segmentation fault.
Any help is appreciated.

**Comment by ThePhD** [comment]
I do not have enough information to assist you. I need more information.

What's the Lua code calling this function look like? How do you get the pointer back in C++? How did you create a `GraphicsEngineFacade`? Are you making a new object, or are you just trying to call "GraphicsEngineFacade" directly because it's some weird singleton type? `new_usertype` does not register a singleton, if that's what this is: it works to help make objects, although you can register static functions and call them.

As a side note, an overview of tutorial topics is here for your perusal as well: http://sol2.readthedocs.io/en/latest/tutorial/tutorial-top.html

**Comment by atbigelow** [comment]
This seems to be an exact issue that I am running into. Here's some stripped down code I have:

```
class SequenceFrameset : public Component {
public:
	SequenceFrameset(uint16_t duration, std::map<std::uint16_t, SequenceFrame*> frames);
};

class SequenceComponent : public Component {
public:
	SequenceComponent(std::string name);

	SequenceFrameset* add(std::string type, SpriteComponent* sprite);
};

flux.new_usertype<flux::Scene::Sequence::SequenceComponent>("Sequence",
	sol::constructors<sol::types<std::string>>(),

	"add", &flux::Scene::Sequence::SequenceComponent::add,

	sol::base_classes, sol::bases<flux::Scene::Component>()
);
```

I get a massive amount of errors when I include the "add" method for Sequence. All it does in C++ land is return a pointer to a new SequenceFrameset.

**Comment by ThePhD** [comment]
@atbigelow Posting a new issue might better aid me in keeping my eyes on this, since I don't exactly get the most visual notifications when a closed issue gets commented on.

That being said, what are the errors? Your code looks fine at a glance and similar mock-ups work for me.

**Comment by atbigelow** [comment]
I'll file a new issue with more details! Sorry for bumping an old issue; seemed similar at the time, but it also lacked some details.
