### ISSUE TITLE
Crash on lua_error

### ISSUE THREAD

**Issue by Trebgarta** [ThePhD/sol2#178]
Well, at least that is my guess, it might be default_at_panic too. Just pulled the latest repo, used single.py with Python 3.4 and compiled these with Mingw-w64 GCC 6.1:

```cpp
...
//sorry for the indentation, copy pasting is a difficult job
try {
    // create an empty lua state
     sol::state lua;
     lua.open_libraries(sol::lib::base);

     // call lua code directly
     std::cout << "=== basic example ===" << std::endl;
     lua["GL"] = lua.create_table_with("VERTEX_SHADER", GL_VERTEX_SHADER);
      lua["GL"]["CreateBuffer"] = GL::CreateBuffer;
      lua.script_file("main.lua"); // Here is the error
  }
 catch (const std::exception&  except) {
     std::cout << except.what() << std::endl;
 }
 catch(...) {
     std::cout <<  "What?"<< std::endl;
 }
...
```
And main.lua:

```lua
print("Buffer! " .. fdadsfsaf) --Just a standard nonexistant variable
```

Though nothing is caught and a fatal crash ensues, GDB says 
```
 lua_error(L);
(gdb) s
gdb: unknown target exception 0xe24c4a02 at 0x7fffe2037788

Thread 1 received signal ?, Unknown signal.
0x00007fffe2037788 in RaiseException ()
   from C:\WINDOWS\System32\KernelBase.dll
```
Afterwards I put this right before lua_error in script_file:
```cpp
auto X = lua_tostring(L, lua_gettop(L));
printf("%s\n", X);
fflush(stdout);
lua_error(L);
```
And error message is printed successfully, "main.lua:13: attempt to concatenate global 'fdadsfsaf' (a nil value)", right before lua_error is called, which results in a crash.

**Comment by ThePhD** [comment]
Works for me in Visual Studio (VC++) and with MinGW g++:

!(Visual Studio 2015)[http://i.imgur.com/bCrOP6E.png]

!(MinGW g++)[http://i.imgur.com/XziuIp0.png]

Please make sure you have the latest version, please make sure you have a supported compiler, and please check to make sure you [haven't defined "SOL_NO_EXCEPTIONS"](http://sol2.readthedocs.io/en/latest/exceptions.html).

**Comment by Trebgarta** [comment]
I have reproduced the issue in plain C API without sol so since it really isnt an "issue" of sol2 and instead my LuaJIT, Im closing it. Sorry for your time.

Though I'd still like to hear ideas, the premise is simple: lua_error wont call lua_Cfunction passed with lua_atpanic before exiting. I'll try to recompile a newer version of LuaJIT, maybe try it once again with a version of Lua.

**Comment by ThePhD** [comment]
"LuaJIT" is the key point here that you didn't mention in your original post: x86 versions of LuaJIT do NOT play nice with exceptions, AT ALL. This has been documented numerous times and many issues have been opened on sol2 about it, and it has its [own section in sol2's documentation as well because it's that much of a problem](http://sol2.readthedocs.io/en/latest/exceptions.html#luajit-and-exceptions) -- sol2's docs also link to relevant tables from LuaJIT that also describe its exception capabilities and the rules you need to play by.

LuaJIT also doesn't quite call the panic function sometimes as well; that's just how the interpreter is. It could be an issue with LuaJIT... or it could not be. I have no idea.

It's no trouble, though, to check these things; this allows me to add to the docs and further explain things, perhaps in ways I haven't before that make sense to more people.

**Comment by Trebgarta** [comment]
I have seen that. Though I thought it wasnt relevant to me because I used 64-bit binaries and the issue wasnt thrown exceptions in C++ functions called in Lua, at least that was what I thought the particular issue you wrote there about LuaJIT was.

What I also noticed is that even the default panic function of LuaJIT wont output anything to stderr before exiting. Looking at [here](https://github.com/LuaJIT/LuaJIT/blob/7e05355a08255f508d334eded96095e0bde06e2e/src/host/minilua.c#L6209-L6214) and [here](https://github.com/LuaJIT/LuaJIT/blob/7e05355a08255f508d334eded96095e0bde06e2e/src/host/minilua.c#L1025-L1038) made me think otherwise. Probably I dont get it though, LuaJIT's or sol's architecture are leagues beyond my level.

Well, I will try with plain Lua tomorrow. Why are we using lua_error anyway? We can just get the error message from the top of the stack and do what we want with it when a lua execution returns an error code.

**Comment by ThePhD** [comment]
Because if an error happens you want to be notified. If you want more control, sol2 provides you with efficient primitives to do that.

- [Safe function calls](http://sol2.readthedocs.io/en/latest/tutorial/functions.html#reading-protected-functions).
- [Optional to avoid having errors thrown at all](http://sol2.readthedocs.io/en/latest/tutorial/variables.html#optional-lookup).
- [load_result, which can allow you to check for success and convert to a sol::error or whatever result type without errors](http://sol2.readthedocs.io/en/latest/tutorial/functions.html#reading-protected-functions)

Finally, we use `lua_error` in the API because it provides a singular error handling mechanism that is well-documented and well-defined. That LuaJIT behaves VERY poorly and does not properly check variables in certain cases is not something I can control (or you, for that matter).

Still, if you prefer the stack sol2 has many stack abstractions contained in [the `sol::stack` namespace](http://sol2.readthedocs.io/en/latest/api/stack.html), but all the functions are not absolutely documented because they're mostly used internally and are subject to changes.

**Comment by nabijaczleweli** [comment]
New tag: `SuckMyNuts.LuaJit`?

**Comment by Trebgarta** [comment]
I can confirm that neither GNU compiled Lua nor MSVC compiled LuaJIT have any problems.

As suggested per http://luajit.org/extensions.html#exceptions

I'll try Cygwin and see what happens.

**Comment by Trebgarta** [comment]
x64 MSVC LuaJIT _still_ wont call panic function either, however it throws an exception caught by ```catch(...)``` and inside catch block one can do what a panic function does, get the error message from top of the stack and print it.
