### ISSUE TITLE
sol::State won't destroy after registering same type class twice

### ISSUE THREAD

**Issue by jkbz64** [ThePhD/sol2#191]
Hello,
I've been trying to 'extend' my class during runtime and everything was fine until the sol::State going out of scope. After 'registering two parts' of the same Type, the sol::State won't get destroyed. Is it problem of registering two same type classes? If so, then there should be some protection against it, right?
I'm including the code which reproduces crash:
```
class A
{
public:
    void a() { std::cerr << "a"; }
    void b() { std::cerr << "b"; }
};

int main()
{
    {
        sol::state lua;
        //Register a and a() method
        lua.new_usertype<A>("A", "a", &A::a);
        //Create and expose object to lua
        A obj;
        lua.set("a", &obj);
        //Call a()
        lua.script("a:a()"); //Works fine
        //Let's add new method to A class
        sol::usertype<A> ab("b", &A::b);
        //'Extend type'
        lua.set_usertype("A", ab);
        //Call b()
        lua.script("a:b()"); //Works fine
    } //lua state is destroyed
    // crash
}
```

**Comment by ThePhD** [comment]
This isn't supported. I should probably throw an error (or just panic when `SOL_NO_EXCEPTIONS` is defined... but I'm not sure how I'd manage that well). 

Either way, if you tried to call `a()` again it would error. The metatable for this class gets replaced entirely.

That being said, I can only repro the crash in MinGW. Which is the worst kind of crash to have to repro, because working with gdb is a fucking trainwreck...

**Comment by jkbz64** [comment]
I just tested it out and calling ```a()``` worked :v:

**Comment by ThePhD** [comment]
So, here's a way that you can do this and have it be at least somewhat supported and not having to kind of go through this kind of really rough way of working with things:

- Set the new usertype using `sol::state::new_simple_usertype<A>( "A", ... )`.
- Get the usertype table from Lua using `sol::table metatable = lua["A"];`
- Adding stuff to it directly: `metatable["b"] = &A::b;`

This I believe can work for you, should be supported for the next while, and probably won't crash your stuff. As a caveat, `simple_usertype`s have some restrictions on how they're usable since they change the semantics for how you access things, particularly variables and such. See the notes/docs here: http://sol2.readthedocs.io/en/latest/api/simple_usertype.html

**Comment by ThePhD** [comment]
Further investigation yields this works because we're employing the same optimizations that `simple_usertype` makes since you don't add anything that requires `.` access (e.g., member variables or properties), so there's only a basic table underneath and that table only gets added to, not fully replaced.

The good news is, your example doesn't crash anymore since I fixed the bug. The bad news is appending at runtime should _not_ work with a plain usertype, only a simple usertype, which means you'll be a tad locked into the restrictions mentioned in the last post.

Pick your poison I guess? vOv

**Comment by ThePhD** [comment]
No longer crashes: https://github.com/ThePhD/sol2/releases/tag/v2.11.7
