### ISSUE TITLE
Working with Visual Studio (MSVC) is undocumented

### ISSUE THREAD

**Issue by Nava2** [ThePhD/sol2#192]
How do I generate/use a project within Visual Studio?

I found a bug but I'm trying to discern why it's happening, so I wanted to properly debug it but I can't use an IDE which makes it a lot harder. 

(P.S. this is why a cmake-based build is handy, I could just generate a Visual Studio project :sweat_smile:)

E: MSVC -> Visual Studio

**Comment by nabijaczleweli** [comment]
>How do I generate/use a project within MSVC?

You don't use projects within MSVC, as it's a compiler.

>I found a bug but I'm trying to discern why it's happening, so I wanted to properly debug it but I can't use an IDE which makes it a lot harder. 

offtop

>(P.S. this is why a cmake-based build is handy, I could just generate a Visual Studio project 😅)

CMake is shit. offtop

**Comment by ThePhD** [comment]
Include the header, link in Lua however you'd like (VIA a prebuilt library or just including all the source files in a "Lua" project and then just building), then just build. It's pretty much the same thing as with every other platform: as per usual, I don't really bundle up Lua 5.1/5.2/5.3 with the project here since I expect someone else will.

For an example, see: https://github.com/ThePhD/lua-bench/tree/master/vendor
The semi-official `Lua` distribution on Github that you can submodule (if that's a need), + the "lua.vcxproj" file, where I literally just include the entire source directory except the files for building the example interpreter (luac.c and lua.c, IIRC).

**Comment by Nava2** [comment]
I've been using VS via CMake project generation for so long that I have zero idea how to setup a project manually. I'll find some tutorials since I'm getting "invalid reads" when I try to link to `lua.dll`.

**Comment by ThePhD** [comment]
It's pretty easy: just make a new (empty) C++ project using the Project Wizard, tell the Solution Explorer to Show All Files, navigate to your Lua directory, and then include everything. You'll also need to open the Project Properties and set it to build a ".dll" (or a ".lib", depending on your needs) and... that's it. You'll be all set.

**Comment by ThePhD** [comment]
Noted in `getting started` docs about how to create a VC++ project for Lua: https://github.com/ThePhD/sol2/releases/tag/v2.11.7
