### ISSUE TITLE
A problem when using  coroutine

### ISSUE THREAD

**Issue by 11nk** [ThePhD/sol2#207]
I want to do this .

```lua
function test()
	print('run ok .')
end

run()
```

```cpp
class co_test
{
public:
	co_test() {}
	~co_test() {}

	void init()
	{
		lua_.open_libraries();

		lua_.set_function("run", &co_test::do_some, this);

		lua_.script_file("init.lua");
	}

	void do_some()
	{
		co_ = lua_["test"];

		if ( co_ ) {
			co_(); // vaild . but run will faild .
		}
	}

private:
	sol::state lua_; //
	sol::coroutine co_; //
};

```
coroutine create ok. but run failed . but after script_file return, run will be ok .
i think it's not a bug . I've never used coroutine before

**Comment by ThePhD** [comment]
Run fails, and it gives you an error as to why it failed. `if (co_)` just checks that it's ready to run. It doesn't tell you if it failed. To check failure, you need to save the result of `co_` and check `.valid()` there or `optional<>` for something with an actual return value.

As an aside, coroutines run on separate threads. This code will fail unconditionally because you have not created a separate thread for the coroutine to run on and you are currently inside of the Lua running state (e.g., `do_some` is being called while Lua runs your script file). Therefore it will be considered to be in the suspended state and Lua will error everytime you try to access it or compute work specifically with `lua_resume`, which is what a coroutine uses to do work.

Try to use `sol::function`/`sol::protected_function` if you need to call the function from inside the interpreter. Otherwise, follow the second example [here](http://sol2.readthedocs.io/en/latest/api/coroutine.html#main-with-thread-cpp) which spawns a thread you can use to do work and resume on.
