### ISSUE TITLE
Bare-bones pushing of functions

### ISSUE THREAD

**Issue by vifino** [ThePhD/sol2#228]
Hello.

Sorry if I didn't find it in the documentation, but how would I just push a C++ function so I can use it as return values or use it with `settable`  and friends directly?

I haven't seen many wrappers for C++ yet, `luawrapper` didn't have such an interface.

It would really help me out a lot!

Thanks!

**Comment by ThePhD** [comment]
You'll want to get your hands dirty with `sol::stack::push`. This is what the higher-level abstractions are built on. Read about it here: http://sol2.readthedocs.io/en/latest/api/stack.html

Note that the interface is volatile since it can change for performance reasons, but we're more or less stable now since after adding the `record` structure we've captured almost everything we need about the stack. This should help you get on your way.
