### ISSUE TITLE
table::for_each on a table originating from sol::as_table has an extra size element

### ISSUE THREAD

**Issue by Philpax** [ThePhD/sol2#242]
Latest LuaJIT, sol2 009d6b0:
```cpp
#include <iostream>
#include <vector>
#include "sol.hpp"

int main()
{
	sol::state state;
	state.open_libraries();
	
	// Vector
	std::vector<std::string> values;
	values.push_back("a");
	values.push_back("b");
	values.push_back("c");

	state["historyV"] = sol::as_table(values);

	std::cout << "Vector:" << std::endl;
	sol::table resultV = state["historyV"];
	resultV.for_each([&](sol::object const& key, sol::object const& value) {
		std::cout << key.as<int>() << " " << value.as<std::string>() << std::endl;
	});

	// Table
	state.script("historyT = {'a', 'b', 'c'}");

	std::cout << "Table:" << std::endl;
	sol::table resultT = state["historyT"];
	resultT.for_each([&](sol::object const& key, sol::object const& value) {
		std::cout << key.as<int>() << " " << value.as<std::string>() << std::endl;
	});

	std::cin.get();
	return 0;
}
```

results in
```
Vector:
1 a
2 b
3 c
-1 3
Table:
1 a
2 b
3 c
```
The extra element appears to correspond to the size (adjusting the number of elements changes the value). Probably an awry stack manipulation somewhere?

**Comment by ThePhD** [comment]
Ah. This is actually a small optimzation: for tables, I add the extra `-1` key signaling a useful 'capacity' argument for when a `std::vector` is serialized from a table from Lua. This prevents things like reallocation during pushback when grabbing extremely large tables from Lua. It is an implementation detail, so I suppose I should just get rid of it, since screwing up something like iteration probably isn't too terribly worth it...

**Comment by ThePhD** [comment]
The key won't be there anymore, albeit we'll have to figure out some other mystical, magical place to store the size, because otherwise we're stuck with the limits of the default container's size and reallocation costs.

https://github.com/ThePhD/sol2/releases/tag/v2.14.9
