### ISSUE TITLE
std containers

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#250]
Something I'm still struggling to do perfectly right, `std::` containers are a thorn in my side because of the way Lua handles tables and iterations between 5.1 and 5.3. In 5.1, ipairs/pairs and other table arguments demand the arguments are indeed tables. This works but carries the cost of losing whatever data structure performance and benefits came from the container of choice (`map`, `unordered_map`, `vector`, `array`, etc.).

In 5.3 this has been relaxed, and the new for syntax with the `__pairs` metamethod calls makes having userdata emulating table features far more efficient for handling C++ containers in some special fashion. I can overload the length, operator[] set and get calls, and a number of other things transparently and shovel inordinate amounts of data in my vectors. vectors can also be taken by reference, transported to C++ function calls without copying, and essentially has far more performance benefits and interop benefits than converting std containers to tables.

People, unfortunately, prefer it both ways. Some people wants tables made out of their C++ structures... but they ALSO want them to refer back to the original data and have it all work. Others want a map to stay a map, to transport it through Lua, and get out the same map (with potentially updated values) in a C++ function call.

I never specifically documented the behavior because it is indeed in a state of flux. I want to go the usertype route, but I need a clever way to make `pairs`/`ipairs` in the old world happy, table-enthusiasts happy, but the same "don't lossy-transform my container into a table" people happy.

Help.

**Comment by kavika13** [comment]
> People, unfortunately, prefer it both ways. Some people want tables made out of their C++ structures... but they ALSO want them to refer back to the original data and have it all work. Others want a map to stay a map, to transport it through Lua, and get out the same map (with potentially updated values) in a C++ function call.

Breaking this down, I am guessing that no one prefers making copies. It's that they prefer for the native interface to function, and all operations to have the expected side-effects.

The problem is that Sol2 is trying to do this with a single internal implementation for all runtimes, yet still guarantee good performance. Without understanding all the intricacies on the Lua side, it sounds like that's not going to be possible. My suggestion would be to consider runtime specific implementations, even if it makes Sol2 a little more complicated. If you have to relax any constraints here, I'd relax performance before I relaxed complexity.

If you have to relax the performance constraint on some runtimes to make everything appear seamless, then it might be good to also support an interface that guarantees performance. This wouldn't have to support the native Lua table manipulation, but could provide its own standardized Lua interface instead. It could also choose to provide multiple types of Lua containers, instead of trying to shoe horn all of them into one type with one interface.

If you go to the trouble of providing an alternate interface, it would also be good to support adapting custom containers, but providing consistent interfaces in Lua. Maybe something like `sol::property`, but with `add`/`remove`/`index`/`clear`/`whatever` methods.

I hope these suggestions aren't just making the problem more difficult :)

**Comment by kavika13** [comment]
> If you have to relax any constraints here, I'd relax performance before I relaxed complexity

This advice might also be in conflict with other choices made in the library. For example, protected functions are opt-in instead of being the default. Maybe if you can't shim things per-runtime, then the default should be performant, but complicated on the Lua side, and the "opt-in" interface should smooth over the native Lua interface, but not guarantee performance?

**Comment by ThePhD** [comment]
I'm beginning to consider maybe if I can inject a table in, but then use metamethods on that table that has a special userdata in its upvalues that would allow me to simply keep the original container as a userdata. That way someone could have the 'table' type, manipulate it as such, pass it off to pairs/ipairs/etc., but still have the inner workings of a std- container. I'm... not exactly sure that's the best way to do it, but that's what I am thinking of thus far.

I'm not even sure it works, actually. I'll have to code up a demo and give it a run over. :v

**Comment by kavika13** [comment]
I don't mean to clutter the thread with how the existing stuff works, but it's at least partially relevant.

I realize now after some digging that you've already done the option I mentioned in the second comment, at least with respect to vectors. Lua's length and index operators are already working and are probably future-proof no matter what your final solution is.

For maps, I know you can read and write from known keys, but is there a way to find a list of those keys like you can with a table? Or would a user have to expose them through a custom method on the usertype?

**Comment by ThePhD** [comment]
With the current Sol implementation of a userdata with overridden metamethods, here's what happens:

- Lua 5.3 ![Lua 5.3 pairs call](http://i.imgur.com/dFEeOzr.png)
- Lua 5.2 ![Lua 5.2 pairs call](http://i.imgur.com/JIfEBJN.png)
- Lua 5.1 / LuaJIT ![Lua 5.1 pairs call](http://i.imgur.com/x8vYFMf.png)

So really only `pairs` is bad here for Lua 5.1. This is why I was thinking of having the table-shim sit in front, because then maybe we could fake things up. Of course, that has a bit of overhead and is also... well, just difficult to implement as well.

**Comment by ThePhD** [comment]
I would also like to, in the future, add some good way of having `add`, `clear`, `index`, and other code. I don't know the "idiomatic" way to have those as part of the Lua code, however, because there's not really too many methods and they're all not member functions, e.g.: https://www.lua.org/manual/5.1/manual.html#5.5

It's a bit painful to find the idiomatic way to do things right / properly with all the versions of Lua. 5.3 simplifies some things, but I think in the end I'm going to have to have "non-standard" member functions...

**Comment by ThePhD** [comment]
[Bikeshed.jpg](http://chat.stackoverflow.com/transcript/message/33833431#33833431)

**Comment by kavika13** [comment]
I think you're just going to have to fork your code paths, as you're trying to support a forked language. Either that, or tell one of the forks that they are no longer supported.

**Comment by ThePhD** [comment]
Just tested some new techniques on working with Lua 5.1. It does not respect metamethods such as `__index`, `__newindex`, and `__pairs` or any of them really. Access is done raw / direct with `pairs`, so even if I try to make a rigged up table it just iterates over the empty shim-table and directly yanks out any keys without consulting any rigging or hijacking functions. Kinda crappy....

**Comment by ThePhD** [comment]
Confirmed `ipairs` doesn't play ball in Lua 5.1 either. Well, damn...

Guess that means that the way we're doing it now is the only way to go.

**Comment by Unarelith** [comment]
With Lua 5.1/LuaJIT, you can overwrite `ipairs` like so:
```lua
local function _ipairs(t, var)
  var = var + 1
  local value = t[var]
  if value == nil then return end
  return var, value
end
function ipairs(t) return _ipairs, t, 0 end
```

And ipairs will work with usertypes.

From: http://lua-users.org/wiki/GeneralizedPairsAndIpairs
