### ISSUE TITLE
Weird error under VC++ 2015  & Please add default constructor for state_view

### ISSUE THREAD

**Issue by Mark-Joy** [ThePhD/sol2#265]
1> Got error under VC++ 2015. Error got resolved after change the number **0**20100 to 20100 :
```javascript
#if !defined(SOL_LUAJIT) || ((SOL_LUAJIT_VERSION - 020100) <= 0)
````
to
```javascript
#if !defined(SOL_LUAJIT) || ((SOL_LUAJIT_VERSION - 20100) <= 0)
````
2>I would like to use the default constructor of state_view
```javascript
state_view() {}
```

**Comment by ThePhD** [comment]
You cannot use the default constructor of  `state_view`. It is a view into Lua, and therefore requires a `lua_State*`. Please hand it a `lua_State*` so that it can do its job properly.

Adding a default constructor to `state_view` will destroy its semantics: someone could create a `state_view` and then start calling functions on it. Internally, we would have to check if the `lua_State*` we store is null or not: that's a million null checks, for no real benefit.

If you need delayed initialization, consider `sol::optional<state_view>` and checking for it being equal to nullopt or if it has been initialized before using.

**Comment by ThePhD** [comment]
Regarding the macros, that's my bad. Octal literals are quite plainly trash in C and C++ and they should have never been implemented by having leading zeroes. Nevertheless, I'll fix it.

**Comment by Mark-Joy** [comment]
I think it's user responsibility for using state_view after assigning a lua_state to it.
I still have not figure out how to use sol::optional<state_view> for delayed initialization.
Currently, I added the default constructor and use it as below, maybe it's simpler
````javascript
sol::state_view lua{};
...
...
void func(lua_State *L)
{
   lua = L;
   ...
}
````

**Comment by ThePhD** [comment]
Pull from the latest to get the fix to the macro comparison. Sorry about that!

https://github.com/ThePhD/sol2/commit/9836aba51de84abe334c5f92ecc8a00c36714340
