### ISSUE TITLE
SOL_SAFE_USERTYPES not safe enough.

### ISSUE THREAD

**Issue by cracyc** [ThePhD/sol2#268]
In mame we have a Lua based interactive console so Lua commands can be used to interact with the running emulation but since a conversion to sol2 it'll crash if you type manager.machine() rather than manager:machine().  SOL_SAFE_USERTYPES seem to be designed to solve this but it would still crash even when enabled. By checking the type (https://github.com/mamedev/mame/commit/6fd9586a8966196857c8c36401215430b695ee93) before stack::get which appears to deference the nonexistent pointer the problem is mostly fixed but this doesn't look like the correct solution.

As an aside I used has_begin_end (https://github.com/mamedev/mame/blob/master/src/frontend/mame/luaengine.cpp#L79) to stop a container from begin converted to a table.  I saw you added is_container as an official way to do that but it faulted when I tried it.

**Comment by ThePhD** [comment]
What do you mean by `it faulted`? Like an actual segfault? I can take a look at `core_options` and see if I can repro the crash with a small amount of code and see why it's not working as you expect...

**Comment by ThePhD** [comment]
Also, it's not exactly the correct solution, you're right. The most correct thing to do here would be to use `stack::check_get<>`. I'm working on pushing this fix pretty much right now (just have to make sure all tests still pass).

FWIW, `#define SOL_CHECK_ARGUMENTS` would be able to catch this issue as well. It turns every get operation into a checked one.

**Comment by cracyc** [comment]
Right, segfault with GCC 6.2 on mingw.  Check_arguments did fix the crash but was way to aggressive with type checking and broke almost everything.

**Comment by ThePhD** [comment]
`SOL_SAFE_USERTYPES` has been heavily beefed up to use the checked versions (instead of just `stack::get`). Hopefully the rest of MAME should be okay with the checked getters being invoked in these cases.

As far as it breaking everything, that's a bit unfortunate. But I guess it's to be expected: SOL_CHECK_ARGUMENTS really does make sure you're being careful with your types, and not putting in, say, a `int32` and then pulling out a `std::string` on the other side (though in general, Lua lets you do this conversion off the stack.... which I begin to suspect is something that probably trips MAME up).

Finally, do let me know if you have any example code (just trying to rip out an isolated part of MAME with `core_options` is a bit tough on me, since I'm not used to the code base). When I try `namespace { template <> struct is_container<core_options> : std::false_type {}` and then treat it as a plain usertype, it seems to work out just fine for me.

Get the latest here: https://github.com/ThePhD/sol2/releases/tag/v2.15.0

**Comment by cracyc** [comment]
Thanks for that.  I'll see about a test for is_container.

**Comment by cracyc** [comment]
I can't find a working test case but I did a little testing in mame by printing "this" in the core_options constructor and in core_options::help() when called from lua.

With has_begin_end : false:type

`ctor: 0000000004dff800
ctor: 0000000004eb2ef0
help: 0000000004dff800`

and is_container : false:type

`ctor: 0000000004dff800
ctor: 0000000006d12ef0
help: 0000000006d753c0`

so somehow the pointer stored is invalid.  Maybe related to the fact that core_options can't be constructed from lua, only passed in?

**Comment by ThePhD** [comment]
When you pass in something of `core_options`, do you pass it in by value or by pointer (or `std::ref`)? sol2 copies / moves when you pass a const value / value. If you have a `core_options` sitting in C++ and pass it in, you should pass it by `std::ref( obj );` or `&obj` for it to only refer to the location in memory in C++.

**Comment by ThePhD** [comment]
If it's a value, then you should expect the address to change when you pass it in to Lua using `lua["opt"] = my_opts;`.

We don't make copies when you call a function, though: things are perfectly forwarded because we can guarantee that the Lua VM will execute for the duration of the function, then return: C++ won't have a chance to destroy any arguments until things return, so perfect forwarding is fine. This is not the case for `lua["opt"] = my_opts;`.

The change in address from the ctor (and the second ctor) to `help` is strange. I'm gonna have to pull a copy of MAME and try to find out what's going on... (as a side note, where in the execution are you, file / line wise, so I can breakpoint at that area?).

**Comment by cracyc** [comment]
Don't worry about the second ctor, that's another copy of core_options.  They're both set by reference at https://github.com/mamedev/mame/blob/master/src/frontend/mame/luaengine.cpp#L1689 . Doing it by value would be bad as they change during start up and also they use a static_cast from derived classes.

**Comment by ThePhD** [comment]
Damn, I finally found the bug. We were using the old `has_begin_end` in one place and not `is_container`, so it treated pointers in a funny way. Here's the updated release: https://github.com/ThePhD/sol2/releases/tag/v2.15.0

We added a test with code like the one in MAME so that it wouldn't happen again.

You should be all set!

**Comment by cracyc** [comment]
Great, thanks!
