### ISSUE TITLE
wrapper for lua_yield/lua_yieldk

### ISSUE THREAD

**Issue by 11nk** [ThePhD/sol2#272]
Will be support it later?

**Comment by ThePhD** [comment]
Impossible to support at the moment.

Lua uses `longjmp` / `setjmp` to perform a `lua_yieldk`. It's extremely restrictive and does not work because performing a `longjmp` completely throws away any callstack information and any other such information. True coroutine support / generator support is just not there in C++, and even when we do get coroutine support I'd need to figure out a way to pushing results to Lua even after jumping out of some arbitrary execution block a Developer specifies with `sol::yield()` or whatever.

It can't happen without me taking some dependency on something like `Boost.Fiber` or writing my own coroutine library.

**Comment by firas-assaad** [comment]
I would also be interested in this feature, if it ever becomes possible (assuming it's what allows Luabind's yield policy or luacppinterface's CreateYieldingFunction). I'd really like to stop using Luabind and Sol 2 is by far the best alternative I've come across. But I'm using the ability to yield from C++ to Lua to create a scripting system, something similar to [this coroutine article](http://lua.space/gamedev/using-lua-coroutines-to-create-rpg) but with C++ implementation of some of the coroutines.

Could you perhaps add a note or comparison point about this feature to your feature matrix? It took me some time to realize it's not even possible. Thanks for creating this!

**Comment by ThePhD** [comment]
I would have to look into how to make this safe in C++ again. Would you mind opening a new issue, so I have something to keep track of while I attempt this again?

**Comment by firas-assaad** [comment]
Sure. Do you mean another issue for lua_yield support, or just for documentation? Just making sure I don't create duplicates.

**Comment by ThePhD** [comment]
An issue for `lua_yield` support in some sensible manner.
