### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by Aykelith** [ThePhD/sol2#283]
Hello. I'm using sol2 with MinGW 5.3 & C++17 and I'm getting a lot of warnings. Because there are a lot I put them in a [gist](https://gist.github.com/Aykelith/8ef3fdd02f4e92037a045f8f7d89ce27).

**Comment by ThePhD** [comment]
This is bizarre. I compile with -Wall -Wpedantic on and I don't get any of these warnings (particularly -Wshadow ones or the ones warning about which path a compiler takes to do implicit conversions). What does your command line look like?

**Comment by Aykelith** [comment]
Hmm. Yes, I do have that commands in my compile:

> -std=c++17 -stdlib=libc++ -Wall -Wextra -Wshadow -Wconversion -Wunused-parameter -Wno-long-long -pedantic

**Comment by ThePhD** [comment]
Just some notes for my own head:
- `-Wno-long-long` is redundant in C++11 (it doesn't warn about this by default in C++11 and above, since `long long` is part of the C++ standard for 11 and beyond)
- `-Wall` + `-Wextra` will automatically trigger `-Wunused-parameter`
- `-Wshadow` and `-Wconversion` are not part of either of those and not specified in `-Wpedantic`. While a case can be made for `-Wshadow`, `-Wconversion` is probably noise: sol2 uses implicit conversions to mock up return-type polymorphism and thusly `-Wconversion` will cause a flood of warnings with typical usage, driving someone to use ugly `f.call<my_return_type, my_second_return_type>( ... )` and other crufty syntax just to get around it...

`-Wconversion` is probably not something we will attempt to support? It's a very blunt hammer and neither GCC nor Clang have fine-turning to allow for things like the useful and innocuous return-type polymorphism idiom we're using here...

**Comment by ThePhD** [comment]
`enum class stuff { table }; struct table {}; // -Werror=shadow triggers`

The above is a deal-breaker for me. `-Wshadow` will not be made part of sol2's build. You'll have to either silence the warnings for building with sol2 or do some other clever thing. If you like, I can add explicitly GCC/Clang pragmas to shut off Wshadow around sol2's code so this won't be a problem for you.

**Comment by ThePhD** [comment]
I added some guards to maybe help your code have less warnings.

Good luck. Sorry that we can't make the code -Wshadow clean, but it's just not a very smart warning trigger, apparently, since it doesn't even understand the compiler's own scoped-enum rules.

Get it here: https://github.com/ThePhD/sol2/commit/289ded358c645edc11ce6acadf803cdb96c27113

**Comment by Aykelith** [comment]
Thank you. It is a not a really big problem for me while the library works good.
