### ISSUE TITLE
How to use luajit with sol2?

### ISSUE THREAD

**Issue by shultays** [ThePhD/sol2#285]
I compiled lua jit and linked to it.

`if type(jit) == 'table' then
   print(jit.version)
end`

Correctly prints luajit 2.0.4 version.

However I couldn't see any performance improvements. Am I missing something? Is there a sol function I should call to enable jit?

**Comment by ThePhD** [comment]
It depends on what kind of code you're writing. LuaJIT will speed you up if you have a lot of scripts or a very big script that does most of the heavy lifting. That stuff will get turned into native x86/x64/PPC code for your platform and then run things natively rather than in an interpreted or instead of with a bytecode.

I don't know what your code is like so it's impossible for me to answer your question. If you're not seeing speedups, that's something for you to look into the LuaJIT documentation and your lua code about, and to also benchmark or profile your code with any of the well-known benching libraries (nonius, GoogleBenchmark, etc.) or good profilers (vtune, Unix's perf tools, etc.).

For sol2, performance regardless of the underlying Lua version and implementation can be achieved here, but the gains won't fix a larger performance problem based on how you've written your code:

http://sol2.readthedocs.io/en/latest/performance.html

**Comment by ThePhD** [comment]
As a side note, if you switch a lot between Lua and C++, you may be incurring the cost of jumping between the two far too often. Consider consolidating your scripts or making one or the other the more heavily used "main" application. Equally mixing the two by jumping between them very often (multiple times in a single loop) can be a tad problematic sometimes. Try to keep large swaths of code in one or the other and let sol2 and other mechanisms handle the smaller things like function calls to C++ and back.

**Comment by shultays** [comment]
> It depends on what kind of code you're writing. LuaJIT will speed you up if you have a lot of scripts or a very big script that does most of the heavy lifting

Yeah, it is kinda opposite of that. I have small functions on lua side that I call from c++ side. 

For example I have a "Bullet" object on c++ and lua side. it has an onTick function on lua side which changes speed/angle of bullet. And there are lots of bullets. 
https://github.com/shultays/bloodworks/blob/master/game/resources/guns/rocketlauncher/rocket.lua

Another example is I send a table to lua and lua fills it. (addParticle fills the table with particle start parameters and c++ reads them by table["string"])
https://github.com/shultays/bloodworks/blob/master/game/resources/particles/rocketSmoke/script.lua

I will check your performance page to night. 

> As a side note, if you switch a lot between Lua and C++, you may be incurring the cost of jumping between the two far too often. Consider consolidating your scripts or making one or the other the more heavily used "main" application

Yeah, I do that a lot too. I guess I can move gun->tick loop to lua side and each side loops separately

Thanks for the help..
