### ISSUE TITLE
Segfault when calling a function with a table

### ISSUE THREAD

**Issue by Tobger** [ThePhD/sol2#293]
This code causes a segfault in [sol.hpp:3909](https://github.com/ThePhD/sol2/blob/7628c635bd8f3ef486cbd06707da1926888fa9ab/single/sol/sol.hpp#L3909) ([stacktrace](https://i.stack.imgur.com/Vkt1N.png)) using lua 5.3 on Windows 7 with MinGW 5.3.0:

    #include "sol.hpp"
    int main() {
        sol::state lua;
        sol::table table;
        lua["foo"](table);
    }

In contrast similar code such as `lua["foo"]();` or `lua["foo"]("something");` throws an *"attempt to call a nil value"*-exception. The above code should throw an exception as well.

**Comment by ThePhD** [comment]
This code segfaults because `sol::table`, when default constructed, does not point to a valid `lua_State*`. Therefore, its error is different than others when you use it improperly (e.g., it tries to access the null `lua_State*` and flips out).

I don't want to add the manual check here, but I can think of a few ways to make it so this error doesn't happen in select cases like this.

I've also thought about maybe deleting the default constructor, but people have purportedly told me that these things being default-constructible is useful, so... Shrug.

**Comment by ThePhD** [comment]
Done. Get it here: https://github.com/ThePhD/sol2/blob/v2.15.5/single/sol/sol.hpp
