### ISSUE TITLE
Assign a new value for userdata in the lua

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#294]
I use the api 'new_usertype' to create a userdata for lua using, but why I can not assign a new value for userdata like this : u["key"] = 123 ?
Here is my code :
```
class Item
{
public:
    Item() = default;
    Item(int id, std::string name);
    virtual ~Item() = default;

    inline int getId() { return _id; };
    inline std::string getName() { return _name; };
private:
    int _id;
    std::string _name;
};

const string LUA_CODE =
"local item = Item.new(12, \"xujh\") \n"
"local id = item:getId() \n"
"local name = item:getName() \n"
"print(id) \n"
"print(name) \n"
"item[\"date\"] = 1989 \n"  -- ERROR ?
"print(item\.data) \n";

sol::state state;
state.open_libraries();
state.new_usertype<Item>("Item", sol::constructors<sol::types<int, string>>(), "getId", &Item::getId, "getName", &Item::getName);
state.script(LUA_CODE);
```

**Comment by ThePhD** [comment]
You cannot assign a new value because userdata are not just blank tables where that is allowed. If you want that functionality, you'll need to override the `__newindex` and `__index` functionality and then write behaviors that store extra fields in a table and retrieve extra fields from a table and pushes them back onto Lua.

An example of how you can do that is on the `metatable_key` API page (although I should probably link to that from somewhere at the Tutorial top level, so people can find it easier: http://sol2.readthedocs.io/en/latest/api/metatable_key.html)

It might make more sense for you to use a table and then attach a bunch of custom functions, or work directly with making your own userdata table to fit your needs. Sol2 offers that as a means of letting you override `__index` and `__newindex` explicitly and then writing your own behaviors in, but doesn't provide much additional functionality because predicting all the things users would want to do in that space is pretty close to impossible.
