### ISSUE TITLE
Compile too slow and the size of generated so is too large.

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#295]
Since our project use sol2 for lua binding, we found compiled on the android platform was cost 20 minutes and the size of so was 16Mb.
As use tolua++ compile was fast and so size was only 6Mb.
Is it because C++ template?
Could you tell me how fix this problem?

**Comment by ThePhD** [comment]
If you have lots of `new_usertype` or `usertype` uses, the template expansion will hurt in some places. I've been actively fighting that, but without a few key C++17 features (e.g., fold expressions), I'm required to expand things at the function level rather than inside of functions and thusly make tons and tons of intermediary functions that should be inlined or optimized away but are not always.

A few things could help slim down binary executable size and executable size down:

- Put all of your bindings in a `.cpp` file so that it is not done multiple times over. Remember that the usertype binding ends up being serialized into the Lua state, so you never need them to appear in a header and cause that same compilation overhead for every compiled file in your project.
- For extremely large usertypes, consider using `new_simple_usertype`. It performs much more work at runtime rather than compile-time, and should still give comparative performance (but it loses out in some cases for variable bindings or when you bind all functions to a usertype). The reason it was created was FOR people who used lots of usertypes but could not handle the larger compile times and did not mind sacrificing a little performance for compilation speed: http://sol2.readthedocs.io/en/latest/api/simple_usertype.html

That's my high-level advice, without seeing the code. I can't comment on why something like `tolua++` or other things are slimmer. There's also the problem that GCC likes to share all of its code by default: ostensibly, you can tell GCC to not export every single little function it has using some compiler flags and keywords, which might also help you slim down the executable size and keep it only presenting the interface that you wanted to from your Shared Object file.

**Comment by ThePhD** [comment]
I am going to make a note here that I need to make a "Reducing Compile Times" section in the documentation, and a "Reducing Binary Sizes" section in the documentation as well. I'll update the progress on how this goes here.

**Comment by ThePhD** [comment]
I've added some docs and notes here: http://sol2.readthedocs.io/en/latest/compilation.html

It's the best I can do for you without more specific information. It'll be a while until I can trim down binary sizes even further, with all the other work that's front and center.

**Comment by aiplay** [comment]
Thanks a lot!!

**Comment by EugenCazacu** [comment]
Hi,

I am looking to decrease the size of executables generated with sol2 which map some C++ interfaces to Lua. I am currently limited to using C++14, therefore I am sticking with sol 2.20.1 for now.

After reading this issue, I switched from `new_usertype` to `new_simple_usertype `when mapping usertypes. This decreased the size of the generated binary roughly by half in my tests (from ~1 Mb to 500 Kb for 10 usertypes with 10 functions each), which is right at the target I have. 

The documentation of the 2.21.1 version no longer documents `new_simple_usertype`, although the function is still in the API. 

I saw that you removed this type completely in sol3, stating that the compilation and runtime is better with `new_usertype` implementation. Unfortunately my tests show that the executable size does not decrease with sol3 `new_usertype` to the same levels as with the old `new_simple_usertype`.

So far I have tested the generated executable size with a few versions of gcc and clang, with O2, O3 and Os flags. O3 in my tests generates slightly smaller executables. O0 the largest by a factor of 5.

Do you have any additional advice to decrease significantly the executable size using sol with 2.20.1, 3.x and maybe how the binary size of the future sol4 would be?
Is there a particular reason not to use the `new_simple_usertype` from 2.20.1, as it no longer is documented?

Thank you!
