### ISSUE TITLE
Passing arguments to a coroutine?

### ISSUE THREAD

**Issue by LordKettune** [ThePhD/sol2#309]
So, in a game engine I'm working on, I have a system in which Lua's coroutines are used to create tasks which can be paused for a number of frames. It works as is, but I would like to be able to pass arguments into these tasks using variadic_args.

The function for starting a task looks like this:

```
void g_startTask(sol::function task, sol::variadic_args args)
{
  sol::thread thread = sol::thread::create(g_lua); //This is a bad idea. I'm working on it.

  unsigned i = g_tasks.size();
  g_tasks.emplace_back();
  g_tasks[i].cr = sol::coroutine(thread.state(), task);

  g_tasks[i].wait = g_tasks[i].cr.call( sol::as_args(args) ); //Here's where it breaks
}
```
Then, from Lua, something like this:
```
function main(x, y, z)
--do something
coroutine.yield(20) --wait 20 frames
--do something else
end

startTask(main, 10, 12, 8)
```
Currently, this results in the coroutine not doing anything at all. Is there a proper way to do it? Thank you in advance.

**Comment by ThePhD** [comment]
Remove `sol::as_args`. It's not needed there to apss those arguments.

**Comment by ThePhD** [comment]
Tha tis, you can pass `variadic_args` without it.

**Comment by LordKettune** [comment]
It still seems to break in the same way without as_args. I've also tried passing specific values into .call(), which have the same effect.

On a side note, do you know how I might have multiple coroutines executing on the same Lua thread? It feels very wrong creating a new thread for every single task, but I had a wide variety of bugs when I kept them all on one. Would it have something to do with saving/restoring the "position" in the coroutine, if that's a thing? I would really appreciate any tips, this has me thoroughly stumped.

**Comment by ThePhD** [comment]
Okay, you need to be more specific now.

What "breaks", and how? Are you not getting "10, 12, 8" on the other side? Does `coroutine.yield()` not do what you think it's supposed to? What's breaking about this and why?

**Comment by LordKettune** [comment]
Ah, sorry, what I meant is that the coroutine just doesn't execute at all. As if it weren't called. I don't get any errors either, just nothing happens. 

i.e., this just results in a black screen, whereas without any parameters it works as expected:
```
local function main(x, y)
  local sprTitle = createSprite("menu/title.png")
  coroutine.yield(20)
  --other stuff
end

startTask(main, 5, 8)
```

Now, if I remove `x, y` from `main(x, y)`, it works, even with the parameters being passed in. It's only when the function itself takes any arguments that it doesn't execute.

I know that I'm getting the right values from Lua in variadic_args, the issue occurs when resuming the coroutine for the first time.

**Comment by ThePhD** [comment]
So, `sol::coroutine` works like `sol::protected_function`. You need to check for errors when they get returned (they return a `protected_function_result`). When I run a mockup similar to what you're describing here, I got a runtime error describing the problem, and worked through it slowly to figure out what I needed to do. Here's a mock-example of your system, working, but BEFORE you run it make sure you pull the latest because there's some extra code in the latest release that will help you get farther:  I made a quick mockup of your example and solved the bug that was related to this. First, grab the latest version here: https://github.com/ThePhD/sol2/releases/tag/v2.15.7

Now, here's how I got something like your code to work:

````
#include <string>
#include "sol.hpp"

#include <iostream>

int main() {
	sol::state lua;
	std::vector<sol::coroutine> tasks;

	lua.open_libraries(sol::lib::base, sol::lib::coroutine);

	sol::thread runner_thread = sol::thread::create(lua);

	lua.set_function("start_task", [&runner_thread, &tasks]( sol::function f, sol::variadic_args va ) {
		// You must ALWAYS get the current state
		sol::state_view runner_thread_state = runner_thread.state();
		// Put the task in our task list to keep it alive and track it
		std::size_t task_index = tasks.size();
		tasks.emplace_back(runner_thread_state, f);
		sol::coroutine& f_on_runner_thread = tasks[task_index];
		// call coroutine with arguments that came from main thread / other thread
		// pusher for `variadic_args` and other sol types will transfer the
		// arguments from the calling thread to the runner thread automatically for you
		// using `lua_xmove` internally
		int wait = f_on_runner_thread(va);
		std::cout << "Wait: " << wait << std::endl;
		// When you call it again, you don't need new arguments (they remain the same from the first call)
		f_on_runner_thread();
	});

	lua.script(
		R"(
function main(x, y, z)
--do something
coroutine.yield(20) --wait 20 frames
--do something else
print(x, y, z)
end
function main2(x, y)
coroutine.yield(10)
print(x, y)
end

	start_task(main, 10, 12, 8)
	start_task(main2, 1, 2)
)"
	);

	return 0;
}
````

Notice here that we have a created thread (to run the coroutine stuff on). It is also important to note that in order to use that runner thread, we have to _retrieve the state related to that thread using the `.state()` function on `sol::thread`. Then, we can "transfer" ownership of `sol::function` `f` from the Main State to the runner thread by using a constructor call which takes the state F and a `sol::reference`-derived object, such as `sol::function`.

Now, after all that set up, you can start and resume the coroutine as you wish. Note that you do not need to pass all the arguments all the time, as the arguments for that function will remain the same after the first time you call it.

This should help you get started. I'm not too good at Lua threading myself -- I much more prefer the clear semantics of the C++ stdlib model right now -- but this should be a decent starting point.

Good luck.

**Comment by LordKettune** [comment]
Ahhh, that all makes sense, thank you so much!
