### ISSUE TITLE
Request: default implementation of to_string metafunction for stl containers in lua. 

### ISSUE THREAD

**Issue by Nomadluap** [ThePhD/sol2#312]

**Comment by ThePhD** [comment]
And what happens when the type `T` of the `vector` or the `map` or any other type isn't properly printable? Do we throw our hands up and don't have it? Do we try to force it by printing addresses?

There's no good default implementation of this that works or scales to the types anyone would need a pretty printer for, as far as I can tell. I'm open to suggestions on how to do this, other than `std::cout << (void*)std::addressof( &container );`.

**Comment by ThePhD** [comment]
I'm going to mark this as "think about later", since there's no good answer for this and no good default format...
