### ISSUE TITLE
Does optional<T> work in class constructor?

### ISSUE THREAD

**Issue by emanuel15** [ThePhD/sol2#316]
I've made a class with this constructor:
`MyClass::MyClass(sol::optional<std::string> a)`
`{`
`	std::string value = a.value_or("nothing");`
`	printf("%s", value.c_str());`
`}
`
and an usertype:
`lua.new_usertype<MyClass>("MyClass",`
`	"new", sol::constructors<sol::types<sol::optional<std::string>>>()`
`);`

In Lua I did:
`MyClass.new("test") -- works fine, prints "test"`
`MyClass.new(nil) -- works fine, prints "nothing"`
`MyClass.new() -- error`

in the last line Sol says "no matching function call takes this number of arguments and the specified types"
shouldn't it automatically be nil if there isn't arguments?

I know I could use other constructor, I just want to know if it's possible to use optional<T> in class constructors. Thanks a lot for the library :)

**Comment by ThePhD** [comment]
It's not possible right now, unfortunately, because it means it would be almost-impossible to differentiate between 2 overloads like:

`MyClass( )`
`MyClass( sol::optional<int> )`

I could try to enable it anyways, hope that it doesn't break anything, but on some basic testing it turns out it ruins a LOT of the overloading and construction assumptions...

**Comment by emanuel15** [comment]
Thanks for the reply, it's okay if you can't add this feature because of the overloading and etc
