### ISSUE TITLE
`wstring_convert` constructor repeat many times unnecessary causes performance degradation

### ISSUE THREAD

**Issue by ljcduo** [ThePhD/sol2#326]
Thank the sol2 has the feature support auto convert lua string to C++ wstring make my job easy.
My program is a GameEngine using lua script to handle lots of game logic(also show lots of text), so I need to convert lua string to C++ wstring very frequent. 
But seems to I find here has a performance problem by VS Profiler, the result show that `locale()` is a heavy opeartor in `wstring_convert` constructor , but sol2 construct `wstring_convert` over and over again. And I check the sol2 source code and found there have many places(such as `stack_push` and `stack_get`) when need to convert lua string to C++ wstring it call a `wstring_convert` constructor causes performance degradation. 
Like:
```
std::wstring_convert<std::codecvt_utf8<char32_t>, char32_t> convert; // seems to no necessary to constuct every time
std::u32string r = convert.from_bytes(str, str + len);
```
So I add a `static` qualifier to `convert` make it construct one time and use it many time, and the performance improve a lot finally. Hope helpful.

**Comment by ThePhD** [comment]
I'll keep this in mind: I don't know if there's anything special the `locale` constructors are supposed to be doing, however, so I'm not sure if I can just make this optimization willy-nilly.

**Comment by ThePhD** [comment]
> Default constructor. Constructs a copy of the global C++ locale, which is the locale most recently used as the argument to std::locale::global or a copy of std::locale::classic if no call to std::locale::global has been made.

The point from above that's important is that the default constructor pulls what the currently used locale is. If we make it static, we no longer get that benefit....

BUT.

UTF16/8/32 conversions are both stateless and -- as far as I know -- do not use locale. We don't support anymore encodings and have no default paths for it, so this should be safe to do.

**Comment by andim2** [comment]
"but sol2 construct wstring_convert over and over again"
Side note: which just goes to show that
it may be a good idea to
keep session instance state as scope-longlived as possible, to
avoid/minimize recurring session state setup costs (in this case of wstring_convert prohibitive due to locale(), according to above explanation).
But since everybody and their dog seem to
favour creating crappy free-running "stateless" ad-hoc C-style functions (yet which then
do proceed with session state setup by
*implicitly* referencing some painful / annoying global state internally!!!), such session state maintaining (recycled class instance) may not be achievable easily.

BTW many thanks for #571 - very very nice explanations!
