### ISSUE TITLE
Get length of a lua string from C++ function

### ISSUE THREAD

**Issue by jeychenne** [ThePhD/sol2#349]
Let's say I have a `regex` class and I want to expose a `match` function such that, in Lua, a user can simply do something like that:

```
re = regex.new("^(..)")
match(re, subject)
```

I'd like to get the C string and its length *without creating an `std::string`*. The best I could come up with is something along these lines:
```
lua["match"]  = [](regex &re, const char *subject, this_state state) {
    size_t len;
    lua_checklstring(state, -1, &len);
    // ...
};
```
This works, but I'm not sure that it's ok to assume that the arguments are still on the stack as I'm doing here. Is there a better way to achieve what I'm trying to do?

**Comment by squeek502** [comment]
Shouldn't `strlen(subject)` work?

**Comment by jeychenne** [comment]
Yes, that's what I did before, but I'd like to avoid recalculating the length since it's linear with the size of the string. Since Lua stores the length of the string internally, I'd like to retrieve it directly.

**Comment by ThePhD** [comment]
Internally, sol uses `sol::string_detail::string_shim`. When we get the string out of Lua, we do `std::size_t sz = 0; const char* ptr = lua_tolstring(L, index, &sz);`. From there, you have everything you need.

Note that when sol2 calls a function, it does not modify the stack until after the function finishes and returns its values. That means you could rely on what you're doing, but be more pointed (e.g., use `lua_checklstring(state, 2, &len);`.

You can also write a customization point that is similar to the `string_shim` in sol. The reason we don't expose this class is because there's a supposed `std::` type coming in C++17 called `string_view` that serves this purpose: when it becomes widespread enough, the goal is to implement a getter/pusher/checker for that, and allow people to use that instead.

In the meantime, `string_shim` looks like [this](https://github.com/ThePhD/sol2/blob/e1329d244a79c95f467eaec97e06e058f492bcde/sol/string_shim.hpp) and the customization point for it looks like [this](https://github.com/ThePhD/sol2/blob/c7deb82535018ed07e4c4f7f20d9551a8ea69e54/sol/stack_get.hpp#L234). You can implement your own lightweight `string_view` for it.

DO NOT use sol2's. It's subject to name changes, namespace changes, or outright removal. It's not documented and it's only for internal work. I cannot stress how important it is you do not rely on `detail` classes.

Finally, here's a simpler solution for you if you just need it for that function:

````
lua["match"]  = [](regex &re, sol::stack_reference subject_ref, this_state state) {
    size_t len;
    const char* subject = lua_checklstring(state, ref.stack_index(), &len);
    // ...
};
````

**Comment by jeychenne** [comment]
Thanks a lot for the detailed and informative answer. Adding my own `string_view` as per your suggestion does exactly what I wanted :+1:. 

Julien
