### ISSUE TITLE
Squirrel port ever possible?

### ISSUE THREAD

**Issue by paulsapps** [ThePhD/sol2#352]
Hopefully this isn't too risky a question ;)

Will there ever be a squirrel port of sol2? I've attempted to write my own binding lib but I'm finding all this template meta programming is actually rather insane :(

Both embedding APIs seem quite similar but due to the template crazies I'm not sure I'd be able to do it myself. If the APIs are near 1:1 then also what about the possibly of supporting both via some compile time option?

**Comment by OrfeasZ** [comment]
Based on my understanding, Sol2 has been written from the beginning with focus on supporting lua and lua only, and not being extensible or pluggable with other scripting languages. On top of that, even though the Squirrel API has a few similarities with the Lua API, they're still inherently different when it comes to offered features, meaning that Sol2 by itself will probably never be able to support both languages in a single library.

With that said however, you can probably start your own fork of sol2 and start wrapping similar lua API calls to squirrel API calls (possibly by introducing an additional header file with macros for lua calls, such as `#define lua_pushinteger sq_pushinteger`, if you don't want to mess with sol's internal code from the get-go). This should be trivial for things that are API compatible, but will become increasingly complex when you start coming across functionality that's either lua or squirrel specific. From that point on you will have to dig into sol2's code and start making changes there, not only to lua calls, but also to implementation specific abstractions.

**Comment by ThePhD** [comment]
If somebody wants to pay me so I don't spend all my time working on Open Source things to make this so I can actually take care of myself and not be a literal zombie, yeah.

... Otherwise, no. I've never used Squirrel, and while I never used Lua before I worked on Sol, I have no desire to do this for other embeddable virtual machines like Python, Javascript, etc. Squirrel's dev, IIRC, might have some interest in making clean bindings. I'm not sure: maybe ask him?

Also, sol2 was designed specifically to encapsulate Lua's functionality specifically. While I'm sure something like 80% of it is basic and what everyone would want from every VM, sol2 isn't exactly made to be a "plug backend and play" interface: it was designed specifically with Lua in mind.

**Comment by paulsapps** [comment]
All right thanks, I might try to be brave enough to fork and make it work with both.
