### ISSUE TITLE
LUA class inheritance example?

### ISSUE THREAD

**Issue by Regday** [ThePhD/sol2#353]
Is it possible to derive a new Lua class from registered by Sol2?
Something like
```
Derived = Class('Derived', BaseClass)
Derived:NewShinyMethod()
    print(self.baseClassVar)
end
```
I'm new at Lua, so for me it's actually not that clear.

**Comment by OrfeasZ** [comment]
Lua by itself does not have OOP semantics and sol2 is just a binding layer, so it doesn't introduce any additional functionality to Lua (compared to say LuaBind). Personally, I use [middleclass](https://github.com/kikito/middleclass) to provide class semantics in my scripts, but I'm not sure if and how one could combine that with sol2 generated metatables (wherever they exist) to implement inheritance on a Lua level.

**Comment by Regday** [comment]
I know about Lua table nature, but Sol2 provides some sort of classes. So I would like to know, is it possible to inherit a new class from them or not.

**Comment by ThePhD** [comment]
Currently, I have no plans on adding a way to add new class features and the like at runtime through a Lua script. Derived classes should be register in C++.

I have been thinking about maybe putting this on the feature list. Problem is, I haven't thought about how I would go about doing the work to make it happen. As it stands, I don't think there's an easy way to enable this, but I'd have to check some interactions with how the Lua script parses out the example code and what metamethods get called. There's also problems like how to define properties, variables, etc. on a 'class type', when Lua has no notion of such a thing...

**Comment by ThePhD** [comment]
Might be added as a "library" type in Sol2, called `sol::lib::lua_classes`: it's a frequent request I've also gotten in person about being able to do this without setting up a bunch of metatable junk...

Implementation will take a while.

**Comment by ThePhD** [comment]
Part of this has been implemented, in that users can define methods at runtime on a predefined class for Lua as shown in [the example now](https://github.com/ThePhD/sol2/blob/develop/examples/usertype_advanced.cpp#L81).

As far as "making a class in Lua", I don't have a syntax for that yet. I need to figure out the proper way of doing that, and how I would handle concepts like base classes and the like. At the moment, it seems unlikely that I would make it do base classes and the like. It's going to take quite a bit of bike shedding to get it right, so don't hold your breath waiting for this one...!

**Comment by OrfeasZ** [comment]
@ThePhD you could look at [middleclass](https://github.com/kikito/middleclass) syntax or [LuaBind](http://www.rasterbar.com/products/luabind/docs.html#defining-classes-in-lua) syntax for inspiration.

**Comment by ThePhD** [comment]
middleclass looks amazing: I definitely will put this on the backburner, if other people already have great libraries like that one...!

**Comment by OrfeasZ** [comment]
Yeah, I've been using it for a while now and it's pretty cool. The implementation is also extremely straight forward.

**Comment by Regday** [comment]
Cool, very useful even at this stage. Much appreciated.

**Comment by ThePhD** [comment]
I spent a lot of time thinking about this. The benefit for classes in Sol is primarily so that userdata can be converted between its `void*` Lua storage and a C++ class while maintaining its layout and other strict invariants. What happens if someone defines a class in Lua at runtime, and then wants to "retrieve" that class later on in C++? Do we tell them to use tables and remove any static safety? Do we try to make it a real class that can have its members laid out in a fashion C++ would expect? How would we go about doing that without having to write what is essentially our own class and method packer? How do we create strong types for things beyond integers, strings, and tables?

There's no good way to do this, and if sol were to provide a "class" abstraction for Lua, it'd essentially be "flavored tables". At that point, there's little benefit to doing it beyond what middleclass already provides, so at this time I'm just going to say use `middleclass` for what you need in Lua. When dealing with C++, however, feel free to use Sol's abstractions to get the most mileage.
