### ISSUE TITLE
How can i get local variables with the same lua_state? 

### ISSUE THREAD

**Issue by stelro** [ThePhD/sol2#354]
I have some questions about the SOL library that documentation cannot answer them.
1st ) It's ok to use the same lua_state to load a bunch of different scripts? or i need for every new script instance of a new lua_state ?

2nd) if i'm load 2 different scripts , say "script1.lua" and "script2.lua" with the same lua_state, how can i get explicitly variable from the second script ("script2.lua") ? I mean how can I get local variables and not the global one ? because I guess if I have the same variable name in "script1.lua" and "script2.lua", there will be a conflict. 

and to be more understandable, say i have some Lua scripts that represents game maps. ex. [ map1.lua, map2.lua, map3.lua ] , those scripts all have some global variables with the same name [ map_width, map_height, etc..], if i want to load those scripts into my engine, should i use for each map a different lua_state to avoid name variables conflict ? 

Tahnk you.

**Comment by squeek502** [comment]
@ThePhD will be able to give you a better answer, but it seems like you're talking about Lua environments. See [the Lua 5.1 reference manual](https://www.lua.org/manual/5.1/manual.html#2.9) or [the Lua 5.3 reference manual](https://www.lua.org/manual/5.3/manual.html#2.2) or [Programming In Lua](https://www.lua.org/pil/14.html).

Note that loading a file is something of a convenience method for doing the following:
 - Reading the file
 - Loading the read file into a function
 - Calling the function

So, you could run each loaded file in a completely separate environment by changing the environment that the loaded function is called in (use `load_file` instead of `script_file` and then modify the environment of the returned function). Then you could retrieve the values from each environment.

Local variables might be pretty tricky to get, not sure about that one. I believe most Lua-as-config-file setups rely on global variables rather than locals.

**Comment by squeek502** [comment]
Came up with a working example:

Lua files:

```lua
-- script1.lua
var = "script1"
```
```lua
-- script2.lua
var = "script2"
```

The C++:
```c++
sol::state lua;
lua.open_libraries(sol::lib::base);

// create a table to act as the environment
sol::table env1 = lua.create_table();
// load the script into a function
sol::load_result script1 = lua.load_file("script1.lua");
// use the __index metamethod to give the environment read access
// to the global environment (optional, but its a way to
// the environment access to loaded Lua standard libraries)
env1[sol::metatable_key] = lua.create_table_with(
	sol::meta_function::index, lua.globals()
);

// push the environment table onto the stack to use it as 
// the parameter for setfenv
env1.push();
// call setfenv with the stack index of the loaded function
lua_setfenv(lua, script1.stack_index());

// call the loaded function now that its env is setup
script1();

// get the value of the variable from the environment
std::string str1 = env1["var"]; // str1 will equal "script2"


// do it all again for the second file

sol::table env2 = lua.create_table();
sol::load_result script2 = lua.load_file("script2.lua");
env2[sol::metatable_key] = lua.create_table_with(
	sol::meta_function::index, lua.globals()
);

env2.push();
lua_setfenv(lua, script2.stack_index());

std::string str2 = env2["var"]; // str2 will equal "script2"
```

**Comment by ThePhD** [comment]
The simpler and easier way to handle this is to run "script1.lua", save all the information you need now/later in some actual C++ variables (`int`, `bool`, whatever), and then run "script2.lua" and do the same thing. Wash, rinse, repeat until you're happy.

If there's some reason you can't do your work in a plain sequential order (script1, work on script 1, script 2, work on script 2, ...) then you will need to consider fancy environments like @squeek502 has demonstrated above. I have not written an encapsulation for environments yet, so perhaps this will serve as a good place to bikeshed what that should look like.

**Comment by stelro** [comment]
Ok, thank you both for your answers. 
One more last question, it's ok to have many lua_states in my application? or it's better to handle all the tasks with only one "global" lua_state?

**Comment by squeek502** [comment]
@ThePhD just to give some feedback on what I think would be nice to have for working with environments:

 - `set_env` function for `load_result`, `function`, and `protected_function` that takes a table (although looking at `lua_setfenv`, it looks like `setfenv` can set the env of userdata and coroutines, too). This might be tricky to implement in such a way that it's compatible with both 5.1 and 5.2+, but that's a big part of the reason why it'd be nice to have. For reference, [here's a setfenv implementation for 5.2+ using Lua code](http://leafo.net/guides/setfenv-in-lua52-and-above.html#code). Note that I also might be biased in how I think this should be implemented, as I've only ever used Lua 5.1.
- If you wanted, you could also add convenience methods like `load_file_with_env`, `script_file_with_env`, `load_with_env`, `do_file_with_env`, etc.
- Not completely related, but it'd be nice to add `table::set_metatable`/`table::get_metatable` functions, just so that it's a little more familiar/discoverable than `tbl[sol::metatable_key]`.

**Comment by squeek502** [comment]
@stelro doing some simple tests, it seems worth it, performance-wise, to avoid multiple states if you don't really need them, although there's not a huge difference if you're opening very few Lua libraries in each state.

Doing 10,000 iterations opening all Lua libraries (~3x slower):
```
Many states: 1452833
One state, many environments: 506157
One state, one env: 479721
```

Doing 10,000 iterations opening only `sol::lib::base` (~1.5x slower):
```
Many states: 751087
One state, many environments: 514418
One state, one env: 475749
```

Test code:

```c++
#include <catch.hpp>
#include <sol.hpp>
#include <chrono>
#include <iostream>

using namespace std::chrono;

#define LIBRARIES_TO_OPEN
#define ITERATIONS 10000

TEST_CASE("many states")
{
	high_resolution_clock::time_point t1 = high_resolution_clock::now();
	for (int i=0; i<ITERATIONS; i++)
	{
		sol::state lua;
		lua.open_libraries(LIBRARIES_TO_OPEN);

		lua.script_file("script1.lua");
		std::string str1 = lua["var"];
		REQUIRE(str1 == "script1");
	}
	high_resolution_clock::time_point t2 = high_resolution_clock::now();
	auto duration = duration_cast<microseconds>(t2 - t1).count();
	std::cout << "Many states: " << duration << std::endl;
}

TEST_CASE("one state, many env")
{
	high_resolution_clock::time_point t1 = high_resolution_clock::now();
	sol::state lua;
	lua.open_libraries(LIBRARIES_TO_OPEN);

	for (int i = 0; i<ITERATIONS; i++)
	{
		sol::table env = lua.create_table();
		sol::load_result script = lua.load_file("script2.lua");
		env[sol::metatable_key] = lua.create_table_with(
			sol::meta_function::index, lua.globals()
		);

		env.push();
		lua_setfenv(lua, script.stack_index());

		script();

		std::string str2 = env["var"];
		REQUIRE(str2 == "script2");
	}
	high_resolution_clock::time_point t2 = high_resolution_clock::now();
	auto duration = duration_cast<microseconds>(t2 - t1).count();
	std::cout << "One state, many environments: " << duration << std::endl;
}

TEST_CASE("one state, one env")
{
	high_resolution_clock::time_point t1 = high_resolution_clock::now();
	sol::state lua;
	lua.open_libraries(LIBRARIES_TO_OPEN);

	for (int i = 0; i<ITERATIONS; i++)
	{
		lua.script_file("script2.lua");
		std::string str2 = lua["var"];
		REQUIRE(str2 == "script2");
	}
	high_resolution_clock::time_point t2 = high_resolution_clock::now();
	auto duration = duration_cast<microseconds>(t2 - t1).count();
	std::cout << "One state, one env: " << duration << std::endl;
}
```

**Comment by ThePhD** [comment]
I would note that if you're opening multiple states, you're usually not opening the state, calling the script, getting the environment, and then closing the state: that's extremely wasteful. If you do have multiple states, you pre-allocate the number you need, and then execute one script on the state.

**Comment by ThePhD** [comment]
I don't think I'll be able to safely provide an Environment of sorts. `lua_setfenv` and `lua_getfenv` have been deprecated in Lua 5.2 and the function no longer exists in Lua 5.3 (in the C API). I cannot make a new 'lib' for this, as its problematic and would have inconsistencies across implementations on the C++ side. Ultimately, someone would need to manage their own environment using Lua code: doing it in C++ is problematic and error prone, as far as I can tell from trying to use the functions in 5.3 and reading the manual.
