### ISSUE TITLE
Checking if a userdata value is a certain usertype?

### ISSUE THREAD

**Issue by squeek502** [ThePhD/sol2#356]
I'm not sure how best to go about this. I'd ultimately like to be able to do something like one of the following (with `thing` bound as a usertype):

```lua
local inst = thing.new()

-- one option, member function on the type
assert(inst:is_a(thing) == true)

-- another option, helper method
assert(is_usertype(inst, thing))

-- third option, reference somewhere in the userdata
assert(inst.__usertype == thing)
-- or
assert(getmetatable(inst).__usertype == thing)
```

In looking through the Lua objects at runtime, I couldn't find a foolproof way to check the relation between a userdata instance and a usertype table--the only things shared are the values of the userdata's metatable key/value pairs and the usertype's key/value pairs (but the metatable is not `==` to the usertype).

I hacked up a helper method version in Lua, but it's prone to error/false positives:
```lua
-- if there is a matching key/value pair between the inst's metatable
-- and the usertype, then assume they match
function is_usertype(inst, usertype)
  if type(inst) ~= "userdata" then return false end
  if type(usertype) ~= "table" then return false end
  local mt = getmetatable(inst)
  for k,v in pairs(usertype) do
    if mt[k] and v == mt[k] then return true end
  end
  return false
end
```

Any ideas on how this sort of thing could be achieved?

**Comment by ThePhD** [comment]
Write a function in C++ when you register your usertype to do the check, if it's that important:

```
lua.new_usertype<thing>( "thing",
     ..., ....
     "is", []( sol::stack_object something ) { return something.is<thing>(); }
);
````

If you're asking how you would do that in Lua, you kind've don't? Metatable implementation is an currently opaque right now, save for the memory guarantees about where the usertype stuff is. It's still subject to change because it's not full-featured yet (see the open issue #266) and we need to make sure we get all the features we can. Plus, we employ some meta-table optimizations based on what gets serialized, so guaranteeting a representation would screw everyone out of optimizations.

Write the methods you need in C++ to check this. Lua isn't very strongly typed and trying to force it to be is probably not the best idea.

**Comment by squeek502** [comment]
Alright, I was hoping to avoid having to bind a method to/for every usertype, but that works. Thanks for the response.

**Comment by ThePhD** [comment]
You can use a template free function to make things easier to bind:

````cpp
template <typename T>
bool is_check ( sol::stack_object something ) {
     return something.is<T>();
}
````

Then, when binding...

````cpp
lua.new_usertype<thing>( "thing",
     ..., ....
     "is", &is_check<thing>
);
````

**Comment by ThePhD** [comment]
A bit of a necro on this issue here, see #506 and maybe drop your opinion.
