### ISSUE TITLE
Compilation errors when registering usertype member function returning pointer

### ISSUE THREAD

**Issue by atbigelow** [ThePhD/sol2#363]
Really hard to explain what is going on, so I'll try to include as many relevant details as possible. I have the following structure (there's MORE, but trying not to dump my whole codebase here):

```
class SequenceFrameset : public Component {
public:
	SequenceFrameset(uint16_t duration, std::map<std::uint16_t, SequenceFrame*> frames);
};

class SequenceComponent : public Component {
public:
	SequenceComponent(std::string name);

	SequenceFrameset* add(std::string type, SpriteComponent* sprite);
};

flux.new_usertype<flux::Scene::Sequence::SequenceComponent>("Sequence",
	sol::constructors<sol::types<std::string>>(),

	"add", &flux::Scene::Sequence::SequenceComponent::add,

	sol::base_classes, sol::bases<flux::Scene::Component>()
);
```

I get a massive amount of errors when I include the "add" method for Sequence. All it does in C++ land is return a pointer to a new SequenceFrameset. If I alter my code and definitions for `add` to *not* return that pointer type, it compiles fine. However, these are the errors I get when it's returning:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'value_type': is not a member of 'flux::Scene::Sequence::SequenceFrameset'	flux	c:\projects\nmq\flux\include\sol.hpp	11342	
Error	C2039	'iterator': is not a member of 'flux::Scene::Sequence::SequenceFrameset'	flux	c:\projects\nmq\flux\include\sol.hpp	11341	
Error	C3646	'I': unknown override specifier	flux	c:\projects\nmq\flux\include\sol.hpp	11341	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	flux	c:\projects\nmq\flux\include\sol.hpp	11341	
Error	C2039	'value_type': is not a member of 'flux::Scene::Sequence::SequenceFrameset'	flux	c:\projects\nmq\flux\include\sol.hpp	11342	
Error	C2146	syntax error: missing '>' before identifier 'value_type'	flux	c:\projects\nmq\flux\include\sol.hpp	11342	
Error	C2146	syntax error: missing '>' before identifier 'value_type'	flux	c:\projects\nmq\flux\include\sol.hpp	11342	
Error	C2065	'I': undeclared identifier	flux	c:\projects\nmq\flux\include\sol.hpp	11345	
Error	C2059	syntax error: '>'	flux	c:\projects\nmq\flux\include\sol.hpp	11345	
Error	C2672	'std::declval': no matching overloaded function found	flux	c:\projects\nmq\flux\include\sol.hpp	11345	
Error	C2783	'add_rvalue_reference<_Ty>::type std::declval(void) noexcept': could not deduce template argument for '_Ty'	flux	c:\projects\nmq\flux\include\sol.hpp	11345	
Error	C2062	type 'unknown-type' unexpected	flux	c:\projects\nmq\flux\include\sol.hpp	11345	
Error	C2238	unexpected token(s) preceding ';'	flux	c:\projects\nmq\flux\include\sol.hpp	11345	

```

Little too advanced for me to sort through. Sorry.

Forgot to mention: sol 2.15.9 with VS2015.

**Comment by ThePhD** [comment]
You're running into the problem of `SequenceFrameset` [being treated like a container](http://sol2.readthedocs.io/en/latest/api/containers.html), since it seems to have `begin` and `end` functions (which triggers Sol to go checking around if its a container type) probably taken from its base class, Component.

The fix is on the page linked above, namely that you need to tell Sol to [not treat that type like a container](http://sol2.readthedocs.io/en/latest/api/containers.html#too-eager-container-detection).

**Comment by ThePhD** [comment]
As a side-note to myself: I should perhaps look into container typedef detection to further strengthen the requirements, so that less code runs into this problem when returning random types. There's no real commonality between all the `std::` C++ containers save for `begin`, `end`, and maybe a typedef or two. I'm not sure what I'd disqualify if I started demanding things like `value_type` be there...

**Comment by atbigelow** [comment]
The parent class `Component` definitely doesn't have `begin`, but does have `end`. I have a handful of other usertypes being registered with the same inheritance chain without issues. But I don't believe any others are **returning** usertypes in the same way, so that could be why.

Regardless, I have used the code in the docs to force it not to attempt it to be a container. Thanks!

**Comment by ThePhD** [comment]
Returning the usertype means it has to `push` it into the system, hencewhy it triggers this codepath and the fix is necessary.

I'm glad it works for you. Best of luck!
