### ISSUE TITLE
Lua saves copies of `shared_ptr` when passing through

### ISSUE THREAD

**Issue by Grant1219** [ThePhD/sol2#365]
I realize Lua will increment the reference count when a `shared_ptr` is copied into the `sol::state` table but I am wondering if it is normal for Lua to hold onto `shared_ptr` even when it is only passed into a Lua function.

Here is the C++ I am using to test this behavior:
```c++
#include <string>
#include <memory>
#include <iostream>

#include <sol2/sol.hpp>

class Entity {
    public:
        std::string GetName() {
            return "Testing";
        }
};

int main(int argc, char** argv) {
    auto ent = std::make_shared<Entity>();
    std::cout << "Ref count before Lua: " << ent.use_count() << std::endl;

    sol::state lua;
    lua.open_libraries(sol::lib::base, sol::lib::math, sol::lib::string, sol::lib::io);

    lua.new_usertype<Entity>("Entity",
        "new", sol::no_constructor,
        "get_name", &Entity::GetName
    );

    lua.script_file("test_script.lua");

    sol::function my_func = lua["my_func"];
    for (int n = 0; n < 5; n++) {
        my_func(ent);
    }

    std::cout << "Ref count after Lua: " << ent.use_count() << std::endl;

    return 0;
}
```

Here is the Lua script:
```lua
-- test script

function my_func(entity)
    print("Inside Lua function:", entity:get_name())
end
```

When I run this I get the following result:
```
> ./sol_test 
Ref count before Lua: 1
Inside Lua function:	Testing
Inside Lua function:	Testing
Inside Lua function:	Testing
Inside Lua function:	Testing
Inside Lua function:	Testing
Ref count after Lua: 6
```

When the `sol::state` is destructed all instances passed to Lua are destructed as expected, but I wish there was a way to avoid the copies hanging around for an unknown amount of time.

The reason I ask is because I am using Lua functions as callbacks for events in my game, and reference counts for `shared_ptr` objects can reach the thousands which has me concerned about resource usage.

**Comment by ThePhD** [comment]
I am not sure I can change the behavior in this case.

When you pass a `std::shared_ptr<T>` by name like that, I recieve `std::shared_ptr<T>&`. Is that meant to be a reference? Or is it a value? Safe semantics say that it should be copied, since I don't know what it's supposed to be or whether or not the user (especially in Lua land) will keep referencing it. If I don't, I run the risk of memory leaks springing up very late in people's systems.

The fix for this is using `std::ref(...)`. Sol is geared to take a reference to the pointer value at that point: however, be warned. If the shared pointer gets changed and you use `std::ref(...)`, then you run the risk of having dangling pointers lurking your system. Use `std::ref(...)` if you know the thing is never going to be copied / saved in places beyond the duration or lifetime of the original object (e.g., the usual lifetime concerns):

````
#define SOL_CHECK_ARGUMENTS 1

#include <sol.hpp>
#include <string>
#include <memory>
#include <iostream>

class Entity {
public:
	std::string GetName() {
		return "Testing";
	}
};

int main(int argc, char** argv) {
	auto ent = std::make_shared<Entity>();
	std::cout << "Ref count before Lua: " << ent.use_count() << std::endl;

	sol::state lua;
	lua.open_libraries(sol::lib::base, sol::lib::math, sol::lib::string, sol::lib::io);

	lua.new_usertype<Entity>("Entity",
		"new", sol::no_constructor,
		"get_name", &Entity::GetName
		);

	lua.script(R"(
function my_func(entity)
    print("Inside Lua function:", entity:get_name())
end
)");
	sol::function my_func = lua["my_func"];
	for (int n = 0; n < 5; n++) {
		my_func(std::ref(ent));
	}

	std::cout << "Ref count after Lua: " << ent.use_count() << std::endl;

	return 0;
}
````
![Shrug](http://i.imgur.com/W2fuGR0.png)
