### ISSUE TITLE
sol::protected_function not throwing an exception when user code is broken

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#375]
Probably introduced in v2.15.9, a `sol::protected_function` will never throw an exception, regardless of the whether the code it's referring to is working as intended or not.

Here's some example code:
```cpp
sol::state lua;
lua.open_libraries();

lua.script(R"(
	function test()
		return (john.doe * 123)[jane.doe]
	end
)");

sol::protected_function test = lua["test"];

try
{
	test();
}
catch (std::exception& ex)
{
	std::cout << "Protected function: " << ex.what() << std::endl;
}
	
sol::function test2 = lua["test"];

try
{
	test2();
}
catch (std::exception& ex)
{
	std::cout << "Unprotected function: " << ex.what() << std::endl;
}
```

One would expect the program to print `Protected function: attempt to index a nil value (john)` or so and then for the app to call `abort()` (or similar) when calling `test2()`. However, here's what ends up happening:

![](http://i.nofate.me/tknwzBfRPQ.png)

**Comment by OrfeasZ** [comment]
Here's another interesting observation. Changing the `test()` calling code to the following:
```cpp
std::string x = test();
std::cout << "Test result: " << x << std::endl;
```
Produces this output:
```
Test result: [string "..."]:3: attempt to index a nil value (global 'john'
```

**Comment by ThePhD** [comment]
This is by design. If you coerce the result to a bad type without checking `.valid()`, then you may as well be using `sol::function`/`sol::unsafe_function` instead. Sol does not throw by default to indicate errors like this: with `SOL_CHECK_ARGUMENTS` defined it will call `luaL_error`, which will call the `panic` function in this case (of which Sol's default implementation throws), but otherwise the point of `sol::protected_function` is to give you a chance to handle the error gracefully by checking `.valid()` or using any of the other `sol::optional<error>`, `sol::optional<result_type>`, etc that come with it.

If you want the library to be throw-happy and super-check all arguments, define `SOL_CHECK_ARGUMENTS`. Sometimes, it's useful to leave it on for development and shut it off in production if neckbreaking speed is a huge concern -- albeit, it shouldn't really slow down the code too noticeably compared to usual application bottlenecks.
