### ISSUE TITLE
A few possible memory leaks with error handlers

### ISSUE THREAD

**Issue by codecat** [ThePhD/sol2#395]
Take this code for example:

```c++
#include <cstdio>

#include "sol.hpp"

int main()
{
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	printf("%u\n", lua.memory_used());
	for (int i = 0; i < 5; i++) {
		printf("%d:\n", i);

		// Remove comments to test individual cases
		lua.script("", &sol::default_on_error); // Leaks
		//lua.script("print(1)", &sol::default_on_error); // Leaks

		//lua.script(""); // Does not leak
		//lua.script("print(1)"); // Does not leak

		//try { lua.script("1"); } catch (sol::error &err) { (void)err.what(); } // Leaks

		printf("  %u\n", lua.memory_used());
		lua.collect_garbage();
		printf("  %u\n", lua.memory_used());
	}
	getchar();
	return 0;
}
```

The output for this on the latest develpment single-header file is this:

```
4860
0:
  5081
  5049
1:
  5221
  5189
2:
  5361
  5329
3:
  5501
  5469
4:
  5641
  5609
```

**Comment by ThePhD** [comment]
Thanks for reporting this. I left crap on the stack like an idiot: it's fixed now and was backported into 2.17.0:

https://github.com/ThePhD/sol2/releases/tag/v2.17.0

**Comment by codecat** [comment]
That fixes the first issue, thank you!

What about this line leaking? (I think you read over it)

```
try { lua.script("1"); } catch (sol::error &err) { (void)err.what(); }
```

**Comment by ThePhD** [comment]
It didn't leak in my tests (I tested on LuaJIT 2.1 and Lua 5.3.4) after the fix.

**Comment by ThePhD** [comment]
Also, I was a badcakes and introduced a new bug when I fixed the last one, so you'll have to re-download this if you need it to work properly...! Sorry!

https://github.com/ThePhD/sol2/releases/tag/v2.17.0

**Comment by codecat** [comment]
Thanks for the heads up.

Here's my test case for the mentioned leak:

```
#include <cstdio>

#include "sol.hpp"

int main()
{
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	printf("%u\n", lua.memory_used());
	for (int i = 0; i < 5; i++) {
		printf("%d:\n", i);

		try { lua.script("1"); } catch (sol::error &err) { (void)err.what(); } // Leaks

		printf("  %u\n", lua.memory_used());
		lua.collect_garbage();
		printf("  %u\n", lua.memory_used());
	}
	getchar();
	return 0;
}
```

Outputs:
```
4860
0:
  5329
  4919
1:
  5388
  4978
2:
  5447
  5037
3:
  5506
  5096
4:
  5565
  5155
```

**Comment by ThePhD** [comment]
The last one leaks because `luaL_error` uses the C technique of `longjmp` to communicate its errors, unless you build in C++ mode. That means that errors thrown by the system are typically caught a default `lua_panic` function, and therefore the Lua state is probably in a semi-broken or mostly-broken state where no hard guarantees can be made about the validity of the its virtual machine, unless you check them.

As such, a bunch of crap remains on the stack that probably shouldn't be left there, and you've also probably violated 20 different ABI boundaries by throwing through a C function, even if that function comes from a statically compiled lib.

The default behavior here should be to log and crash, as explained [in the docs](http://sol2.readthedocs.io/en/latest/errors.html#catch-and-crash). Balancing the stack is the least of our concerns here, though I could try to patch something in that will soothe the 'leak' a little bit?

**Comment by codecat** [comment]
Got it. I was wondering if this was even a real issue (script errors should be fixed, anyway). So it's not a huge problem. I am starting a project that will require a small memory footprint though, so if I happen to run into any issues I will let you know.

**Comment by ThePhD** [comment]
Well, as a safety precaution I now completely level the stack (in the case of when you catch an error and it gets tossed later): https://github.com/ThePhD/sol2/releases/tag/v2.17.0

Good luck.
