### ISSUE TITLE
Casting from base to derived class?

### ISSUE THREAD

**Issue by master4523** [ThePhD/sol2#396]
As I understand from the [documentation](http://sol2.readthedocs.io/en/latest/api/usertype.html#inheritance), it is not currently possible to downcast from a base class to a derived class, is there any particular reason why this isn't possible? (please forgive my ignorance)

Here is an example of what I'm trying to do:

```C++
#include <string>
#include <iostream>
#include <sol.hpp>

class BaseClass {
};

class DerivedClass : public BaseClass {
public:
    int foo() { return 123; }
};

sol::state lua;

void test(BaseClass* cls) {
    sol::protected_function f = lua["handler"];
    sol::protected_function_result result = f(cls);
    if (!result.valid()) {
        sol::error err = result;
        std::cout << err.what() << std::endl;
    }
}

int main (int argc, char* argv[]) {
    lua.open_libraries();
    lua.new_usertype<BaseClass>("BaseClass"
                                );

    lua.new_usertype<DerivedClass>("MyAwesomeDerivedClass",
                                   "foo", &DerivedClass::foo,
                                   sol::base_classes, sol::bases<BaseClass>()
                                   );

    lua.script(R"(
function handler (cls)
    print(cls:foo()) -- gives an error with ''attempt to call method 'foo' (a nil value)'' instead of printing ''123''
end
)");
               
    // Instantiate derived class and pass it to test(BaseClass*)
    DerivedClass* derived = new DerivedClass();
    test(derived);
}
```

Obviously, if I change the signature of _void test(BaseClass*)_ to _test(DerivedClass*)_ it works just fine, but it defeats the purpose of what I'm trying to achieve.

I was thinking of something like _test(sol::cast_userdata("MyAwesomeDerivedClass", derived))_ which would wrap the derived class object into a sol object that would be passed to the protected_function and then mapped to the correct usertype (in this case: MyAwesomeDerivedClass)

Please let me know if you need more informations, or if there is absolutely no way to achieve this.

Thanks! 🙂

**Comment by squeek502** [comment]
This works, not sure if it's exactly what you want:

```c++
void test(sol::object cls) {
    sol::protected_function f = lua["handler"];
    sol::protected_function_result result = f(cls);
    if (!result.valid()) {
        sol::error err = result;
        std::cout << err.what() << std::endl;
    }
}

// Instantiate derived class and pass it to test()
DerivedClass* derived = new DerivedClass();
test(sol::make_object(lua, derived));
```

**Comment by ThePhD** [comment]
Your original code doesn't work because you've stripped the relevant type information from the class by casting it to a `BaseClass*`. sol2 can guess what derived classes it is, but it can't really do that without Runtime Type Information and simply trying a `dynamic_cast` to every possible derived class it can think of and seeing which one works.

Problem 1: `dynamic_cast` only works if RTTI is on. sol2 comes without RTTI.
Problem 2: How do we know what all the derived classes of `BaseClass` are? How do we bake this compile-time information into a Runtime System like Lua? How do we perform this cast at runtime and, once we do, how do we make sure we do it compatible to the compiler's ABI?

Problem 2 is solved if someone turns on RTTI. But at this point, the problem is still untenable: Lua stores a `void*` pointer in its system. In other words, we have NO idea what exactly the pointer type is when we get it out on the other side. We just sort of hope it's the right type and we have some basic checks to ensure you're not destroying the memory or killing yourself.

At this point, you're better off tracking that stuff yourself, taking a `sol::object` or a `BaseClass*` in C++, and then casting appropriately in a C++ method so you don't destroy the world.

**Comment by master4523** [comment]
Converting it to a sol::object worked! I ended up adding a virtual method in both classes, which returns a sol::object.

I forgot to mention that I already was keeping a track of the "type" internally, but I have no current need to cast it back anyway, so I guess it's fine.

Sorry for the dumb issue and thanks to both of you guys for the help, love this lib :-)
