### ISSUE TITLE
issues with new_usertype with std::bind and std::mem_fn

### ISSUE THREAD

**Issue by MansurBM** [ThePhD/sol2#400]
This is my first github post, so sorry if I'm posting at the wrong area, or posting wrongly.

Hi, today I was hit with a rather frustrating bug that took quite a bit of my time. I managed to fix it on my side so I thought I should post it here so that you might perhaps give a more elegant bug-proof solution, or perhaps allow others googling with the same problem to see this.

so I wanted to add in a member function(GameObjectManager) to a different class (GameObject) as a static lua function but I got into some issues.

**I have my function as follows:**
`std::size_t GameObjectManager::Create()`

**This is my initial approach:**
`m_pLuaState->new_usertype<GameObject>("GameObject",
			"Create", std::bind(std::mem_fn(&GameObjectManager::CreateGameObject), std::ref(*pGameObjectManager))
);`

So the issue is that this function returns a nil, probably due to the return type of std::bind having issues with the binder. The expected return type is an std::size_t

**This is my fix:**
`m_pLuaState->new_usertype<GameObject>("GameObject",
			"Create", std::function<std::size_t()>(std::bind(std::mem_fn(&GameObjectManager::CreateGameObject), std::ref(*pGameObjectManager)))
);
`
I basically encapsulates everything into an std::function so it returns the correct thing, which in this case is std::size_t

**Comment by ThePhD** [comment]
`std::bind` and `std::mem_fn` are terrible tools for an outdated age. They also don't work very well with most systems due to their unspecified return type, making it impossible for me to anticipate what they are and how to properly get into its machinery.

Bind as follows:
````
m_pLuaState->new_usertype<GameObject>("GameObject", 
     "Create", []() { return pGameObjectManager->CreateGameObject(); }
);
````

The above syntax created a closure called a [lambda](http://en.cppreference.com/w/cpp/language/lambda). It's an exceedingly improved version of `std::bind`, and in all honesty `std::mem_fn` and `std::bind` should be deprecated in favor of lambda usage.

I might look into why this is not behaving properly later, but honestly I would suggest using a lambda for now.

Have fun!

**Comment by ThePhD** [comment]
So it's impossible to figure out the `result_type` properly from a `std::bind` because (according to C++17) that member type definition has been deprecated. This means that I can't properly figure out how to infer the return type for the called function, since there's no way it will give it to me even if I use `std::is_bind_object` to detect that you're using `std::bind`.

Sure, I could use it and depend on broken stuff, but it's not exactly a good idea to rely on stuff that we know is going to be thrown out at some point in C++ history.

Again, I would recommend the Lambda approach. It is superior in binding, argument rearrangement, and formatting as compared to `std::bind`. If you'd ___really___ want me to, I can attempt to work out a way to dig into `std::bind` and `std::mem_fn`, but it's not going to be a pleasant or pretty patch to the library.

**Comment by MansurBM** [comment]
Ahh okay. I wasn't aware that std::bind is depreciated. I've been so used to using it for all kinds of situations that lambda didn't even come to mind when I was looking for a solution. Thanks for the info. I guess I'll start using more lambda, and avoid using std::bind in my codes from now on.
