### ISSUE TITLE
Compile Error When use gcc

### ISSUE THREAD

**Issue by djbhsys** [ThePhD/sol2#407]
I'm trying to use sol2 in my project,and it's all fine in Visual Studio 2015,but when I try to compile in Linux using gcc,it's get error below:
--------
>/home/cm/RoomServer/Server/GameServer/Box2D/../sol.hpp:9976:4:   required from ‘sol::proxy<Table, Key>& sol::proxy<Table, Key>::set_function(Args&& ...) [with Args = {void (&)(b2World*, sol::basic_table_core<false, sol::reference>&, int)}; Table = sol::basic_table_core<true, sol::reference>&; Key = const char (&)[16]]’
/home/cm/RoomServer/Server/GameServer/Box2D/../sol.hpp:9982:23:   required from ‘sol::proxy<Table, Key>& sol::proxy<Table, Key>::operator=(U&&) [with U = void (&)(b2World*, sol::basic_table_core<false, sol::reference>&, int); typename std::enable_if<sol::meta::all<std::integral_constant<bool, (! sol::is_lua_reference<typename sol::meta::unwrap_unqualified<Fx>::type>::value)>, sol::meta::is_callable<typename sol::meta::unwrap_unqualified<Fx>::type> >::value, sol::meta::enable_t>::type <anonymous> = (sol::meta::type)0; Table = sol::basic_table_core<true, sol::reference>&; Key = const char (&)[16]]’
/home/cm/RoomServer/Server/GameServer/CppRoom.cpp:21:25:   required from here
/home/cm/RoomServer/Server/GameServer/Box2D/../sol.hpp:7345:13: error: invalid initialization of non-const reference of type ‘sol::basic_table_core<false, sol::reference>&’ from an rvalue of type ‘sol::basic_table_core<false, sol::reference>’
    return fx(std::forward<Args>(args)...);
             ^
make[2]: *** [CMakeFiles/gs.dir/GameServer/CppRoom.cpp.o] Error 1
make[1]: *** [CMakeFiles/gs.dir/all] Error 2
>
---

and the gcc compiler version info is :
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/5.4.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../gcc-5.4.0/configure --disable-multilib
Thread model: posix
gcc version 5.4.0 (GCC)

--------
I'm trying to change the code that error shows,but can not success,So can anyone tell me how to fix error or which way should i go to tack this error down?
Thanks some much.

**Comment by ThePhD** [comment]
Show me some relevant code which triggers the error so I can understand how to help you.

**Comment by djbhsys** [comment]
Thanks for your reply.
Here is the code on CppRoom.cpp:21 :
```
lua["world"] = RequestPhyWorld;
```
here is the define of function *RequestPhyWord*:
```
void RequestPhyWorld(b2World* world,sol::table& room,int id)
```

**Comment by djbhsys** [comment]
PS: The type of var **lua** is sol::state& .

**Comment by ThePhD** [comment]
> `void RequestPhyWorld(b2World* world,sol::table& room,int id)`

Your problem here is `sol::table&`. When `sol::table` (or `sol::object`, or any [`sol::reference`-based type](http://sol2.readthedocs.io/en/latest/api/reference.html)) is retrieved from Lua, it is retrieved as a value (without the `&`).

Take it as a value (`sol::table room`), making the signature:

> `void RequestPhyWorld(b2World* world, sol::table room,int id)`

Any code which is like that will suffer the same problem, so make sure to change it everywhere. All `sol`-types that come from `reference` or `stack_reference` are implicitly references to some internal Lua value and are generally on the cheap side to copy: passing them by reference does not buy you much in the first place because all operations are done through a Lua handle (what's contained in `sol::reference`).

**In-Depth explanation about the error**:
The reason your code works in Visual Studio is because VC++ (the Visual Studio default compiler) has a non-standard extension which allows a non-const reference to be constructed temporarily from a temporary: AKA, a value of `sol::table&&` and `sol::table` can be temporarily converted to a `sol::table&` per construction rules and kept alive for the duration of an evaluated expression with some extended lifetime rules. This is non-standard and often causes problems like you described, where individuals who port code get bitten by this kind of thing daily.

Nothing I can do to help you there: it's just VC++'s 'helpful' extensions at work.
