### ISSUE TITLE
Nested non-copyable vector in usertype

### ISSUE THREAD

**Issue by nyorain** [ThePhD/sol2#409]
Hey, sorry to bother again (but thanks for maintaining this so well).
Although non-copyable usertype members work now, wrapping them up in a vector (or some similar container probably) still produces a compile time error since creating the usertype already seems to instanciate a template that tries to copy it:

```cpp
#include <sol.hpp>

struct SomeNonCopyable {
	SomeNonCopyable(SomeNonCopyable&& other) noexcept = default;
	SomeNonCopyable& operator=(SomeNonCopyable&& other) noexcept = default;
};

struct A {
	std::vector<SomeNonCopyable> b;
};

int main()
{
	sol::state state;
	state.new_usertype<A>("A",
		"b", &A::b); // adding sol::readonly here does not compile as well
}
```

**Comment by ThePhD** [comment]
**Fix**: 
[Download the latest sol2 release, and use `sol::readonly`](https://github.com/ThePhD/sol2/releases/tag/v2.17.4).

**In-depth explanation:**
This bug is unfortunately semi-unfixable.

When you bind a `std::vector` as a member variable, I perform a check to see if it's possible to write into that member variable (e.g., `std::is_copy_assignable<T>`), and perform the `b = ArgFromLua` assignment there. The problem is, even if `std::vector::vector( const std::vector& )` is ill-formed because of the internal type `T` (in this case, T == 'SomeNonCopyable`), `std::is_copy_assignable<T>` isn't picking it up. `std::vector` technically has a copy constructor, even though it fails compilation because it calls other functions inside of it which demand that the type is copyable.
