### ISSUE TITLE
quick ‘n’ dirty tutorial issues/errors

### ISSUE THREAD

**Issue by 1j0e** [ThePhD/sol2#411]
Not sure if this is the place to say this, but the "quick ‘n’ dirty" tutorial and its code (on sol2.readthedocs.io) has a few issues.

In the following, script2( ) returns void, not sol::protected_function_result:
```
// load string without execute
sol::load_result script2 = lua.load("a = 'test'");
sol::protected_function_result script2result = script2(); //execute
```

In the following, create_table_with is missing an 'i':
```
// make a table
lua["some_table"] = lua.create_table_wth("value", 24);
```

Also when I run the following code, I'm getting this message:
"lua: error: [string "print(dog.tailwag)"]:1: attempt to index a sol.Doge value (global 'dog')"
```
#include <iostream>
#include <sol.hpp>

struct Doge
{
	int tailwag = 50;
};

int main( int argc, char* argv[ ] )
{
	sol::state lua;
	lua.open_libraries( sol::lib::base );

	lua[ "dog" ] = Doge{ };

	try
	{
		lua.script( "print(dog.tailwag)" );
	}catch( std::exception& e ){
		std::cout << e.what( ) << std::endl;
	}

	system( "pause" );
}
```
Run in Visual Studio 2017, x64, in Debug and Release configurations

**Comment by ThePhD** [comment]
Thanks for pointing out the errors.

*For the first:*
`script2()` does not return void. It returns `sol::protected_function_result`. You are getting a red squiggly because the compiler frontend that analyzes the code and provides red squigglies is not the compiler itself (and it is unfortunately kind of dumb). That code compiles, on all platforms.

*For the second:*
Thanks, I'll fix it now.

*For the third:*
You need to create a new_usertype in order to access the members and specifically bind what members you want. See https://github.com/ThePhD/sol2/blob/develop/examples/usertype.cpp for an example, and https://github.com/ThePhD/sol2/blob/develop/examples/ for a bunch of examples in the usertype category (all usertype examples start with `usertype`... in the name).

**Comment by ThePhD** [comment]
Fixed.
