### ISSUE TITLE
Iterating custom container of usertype from Lua is off-by-one

### ISSUE THREAD

**Issue by RaptorFactor** [ThePhD/sol2#412]
When iterating over a custom container of some usertype (but not an equivalent std::vector of the same type, nor if the type is e.g. int) the iteration will be off-by-one (advanced one position too far). I've uploaded a contrived test case [here](https://gist.github.com/RaptorFactor/19f1c03f2c53eaa6e8b5c5c511944c37). I expect 0 -> 99 to be printed, instead I see 1-99 followed by '-1' (which is the off-the-end value).

Using Lua 5.3.4 and latest sol2 from develop (acee4dbbc9f94a82985637ffd05a6ecbf2cead51). Same behavior observed with both MSVC (Visual Studio 2017 - 15.2) and GCC (7.1, MinGW-w64).

**Comment by ThePhD** [comment]
Your code breaks because your iterator returns a `const MyInt &`, and sol2 returns that through literally. It then performs a `++` afterwards: but, since sol2 is capturing the return value of `*it` directly and returns the reference as-is without forcing a copy, when it gets changed the underlying also gets changed and thusly the print function prints out the value of what's stored in the iterator (which is +1 position from what you want).

To be honest, I don't know how to handle your proxy-iterator that returns a reference and not a value that's implicitly convertible to `value_type`. I could force the code to push a copy, but that might have ramifications for other things... I'll need to try some containers with different types in them to test the semantics of each idea.

**Comment by RaptorFactor** [comment]
Sorry the value_type being 'int' instead of 'MyInt' was actually an error on my part which I introduced while testing what failed and what didn't. The correct test case should have value_type set to 'MyInt'. (It still fails with that change, I just wanted to clear up my scenario.)

**Comment by ThePhD** [comment]
As expected when running tests, several things break when I attempt to force a copy in this scenario. With your iterator being an `input_iterator` and returning a reference to a value stored by the iterator, it is affected by doing things like `++` after doing `*it`. My initial reaction is to tell you to return by-value if you're going to keep the value inside of your iterator.

However, `std::istream_iterator` exhibits the same deficiency in sol2 as well (since it keeps the value stored inside of the iterator type). I have no way to detect "this iterator has a garbage implementation and thusly I need to copy to be safe, but all the others should be fine". I don't know if checking `std::iterator_traits<It>::iterator_category` and then forcing a copy of the `value_type` into sol2 is necessarily a good idea, but I very well may do that just to avoid this _specific_ issue while I think of a better way to handle it internally.

**Comment by RaptorFactor** [comment]
I'm not sure I agree/understand. Isn't that the entire point of input iterators? I haven't tested it, but how about something like std::filesystem::recursive_directory_iterator? It's an input iterator which doesn't have an associated container, and it seemingly returns a reference and a pointer to its underlying value.

http://en.cppreference.com/w/cpp/filesystem/recursive_directory_iterator/operator*

I mean, it only makes sense to me to return a reference in operator* if I'm returning a pointer in operator-> (unless you have a better return type suggestion there?), right? Or maybe not. If I have the mental model for this all wrong I'll happily be educated. :)

**Comment by ThePhD** [comment]
Yes, as I mentioned `std::istream_iterator` has the same issue (it's an input iterator). That doesn't really change that I think its a bit of a garbage iterator, but that's just my lame opinion and not really any kind of fact or worth any sort of educational value.

Either way, I hammered at the code to -- in the case of a input iterator -- serialize a copy into Lua, rather than store a reference. This should alleviate any troubles you have (just make sure `value_type` is present on the container / iterator).

Pull from the latest to have the fix.
