### ISSUE TITLE
Bounds check negative index in std::array

### ISSUE THREAD

**Issue by jzrake** [ThePhD/sol2#417]
``` C++
#define SOL_CHECK_ARGUMENTS
#define SOL_SAFE_USERTYPES
#include "sol.hpp"

class MyData
{
public:
    std::array<int, 3> three_integers;
};

lua.new_usertype<MyData> ("MyData", "three_integers", &MyData::three_integers);
```

``` Lua
local my_data = MyData.new()
my_data.three_integers[1] = 7 -- OK, great
my_data.three_integers[2] = 7 -- OK, great
my_data.three_integers[3] = 7 -- OK, great
my_data.three_integers[4] = 7 -- OK, throws Lua exception
my_data.three_integers[0] = 7 -- BAD, silent memory error
my_data.three_integers[-1] = 7 -- BAD, same
```

Compiler:

> Apple LLVM version 7.0.2 (clang-700.1.81)
> Target: x86_64-apple-darwin14.5.0
> Thread model: posix
> 

sol.hpp:

> Generated 2017-05-04 07:17:19.632331 UTC
> This header was generated with sol v2.17.1 (revision 7b78558)
>

**Comment by ThePhD** [comment]
There's no real precedent for behavior here, since Lua tables will just attempt to insert the value as best it can (and succeed because they're associative dictionaries with a loose definition for what encompasses a sequence, and it will snap that definition in 2 and return to being an associative dictionary if you look at it funny).

What I can do is -- at the very least -- prevent memory errors by swallowing those inputs and performing no changes on the underlying container. But what kind of exception should I throw...?

**Comment by ThePhD** [comment]
Added a few errors if SOL_CHECK_ARGUMENTS is defined, I guess. This should be good enough for your case (since you're defining the safety features), but for other people who like the speed and live on the edge, they can enjoy having no errors if they don't care about safety.

https://github.com/ThePhD/sol2/tree/develop/single/sol

**Comment by jzrake** [comment]
Thanks for looking into this. My two cents are that `std::array` is a user data, not a table. So its behavior under `newindex` need not emulate that of a Lua table. In fact, I would prefer 0-based indexing on the array, rather than 1. Safely disregarding out-of-range indexes seems OK to me.

But, is it really only "living on the edge" to allow users of your application to modify arbitrary memory addresses? This sounds to me like it's asking for major vulnerabilities; what happens if I do

```Lua
for i = 0, 10000000 do
  my_data.three_integers[-i] = 999
end
```

?

**Comment by ThePhD** [comment]
My only assumption is that the user knows what they're doing, at all times. They can forfeit this burden of responsibility by defining `SOL_SAFE_USERTYPES` and `SOL_CHECK_ARGUMENTS`.

All example code is written with the safety features on `SOL_CHECK_ARGUMENTS`. I've also gone through most of the documentation and all complete examples include

````
#define SOL_CHECK_ARGUMENTS
#include <sol.hpp>
...
````

or similar. I would love to have safety -- for arguments, for functions, for return types, for userdata -- be always on, but I have a demographic that is keenly interested in having these checks omitted because they A) perform the checks themselves by writing loops that iterate over specific bounds B) use the `pairs` abstraction afforded to them in Lua 5.2+ C) have a vested interest in high performance and D) type-pun and bit-twiddle to emulate old hardware and low-level VMs.
