### ISSUE TITLE
Runtime performance cost of simple_usertype

### ISSUE THREAD

**Issue by Zeblote** [ThePhD/sol2#429]
I've read in the docs that using simple_usertype has a small runtime performance cost, but it's not clear to me what this means. It could be 2 things:

1. Binding is slower, because adding all the functions one by one simply isn't as fast as adding all at once. This would be mostly irrelevant though, binding only happens rarely.
2. Lua code actually runs slower. This wouldn't make sense to me, aren't the generated metatables identical in the end?

Can you clarify this?

**Comment by OrfeasZ** [comment]
From my understanding and experience `simple_usertype` has the following differences when compared to a `usertype`:
- Native binding code for `simple_usertype` compiles faster and is smaller. That's because `usertype` makes aggressive use of template metaprogramming and therefore generates more code. `simple_usertype` is more runtime-based.
- Lua code using `simple_usertype` is slightly slower compared to `usertype`. Again, that's because of `usertype`'s use of template metaprogramming, as that allows to generate necessary metatable indexing/etc functions during compile time. `simple_usertype` on the other hand relies more heavily on runtime look-ups for resolution.

As a side-note, last time I checked, `usertype` performed slightly worse than `simple_usertype` under specific usage scenarios (ie. having a boatload of registered properties and functions).

Keep in mind all of this might no longer be the case. @ThePhD will be able to verify.

**Comment by ThePhD** [comment]
Benchmarks were actually updated well after August 2016, but they are still a bit old since they don't take into account new changes made to usertypes more recently: http://sol2.readthedocs.io/en/latest/benchmarks.html

`simple_usertype`'s page in the docs also provides some links to graphs. The difference in timing under the tested scenarios is nanoseconds at this point, and most likely not worth looking into except for the most strenuous of performance concerns (in which case, you should be looking into `sol::c_call` and other things in the documentation). `simple_usertype` is primarily a way to get around compiler limitations and ridiculously long compile-times. The performance overhead is minimal, if it's there at all anymore.

I have to re-do the lua benchmarks but I'm also in the middle of trying to write noexcept benchmarks... problem is, I can't publish those accurately because only g++ 7.1 can trigger the noexcept changes and I need to really clean up the `lua-bench` repo to build on not-Windows without this hacked-together makefile I have laying around.

It's.... it's a lot of work and I'm tired.

**Comment by ThePhD** [comment]
As a side note: the generated metatables are _not_ identical. They need to be handled differently because of how things are serialized: regular usertypes serializes all members in one giant tuple and provides an obscene amount of compile-time wrapping and computation around it to keep things fixed in memory with no type-erasure; simple usertypes dump everything into Lua as soon as it can and keeps the state around in Lua: everything is erased behind Lua objects, and variable calls are also stuffed behind virtual function call wrappers. The compiler may be allowed to perform a small amount of de-virtualization for the purposes of speeding up function calls, but I haven't tested or measured if the compiler is doing this or not.

**Comment by Zeblote** [comment]
Thanks for the detailed responses! Basically I shouldn't be worrying about it because the difference is negligible. Not like we have much of a choice here anyways, with how huge the Unreal API is.

Since we're generating all the binding code automatically, would there be any reason to not wrap everything in a `sol::c_call`? Only tradeoff seems to be that the code is a little ugly.

**Comment by ThePhD** [comment]
`sol::c_call` supports less features (since the functions need to be available at compile-time for this to work, as the (member) function/variable value is passed as a compile-time argument). That's the only real restriction.
