### ISSUE TITLE
function and protected_function (documentation)

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#438]
The reference states that `sol::protected_function` does all kinds of error checking that `sol::function` does't do, but is not very explicit about the following things, which I wish to be clarified:

* Is it enough to wrap a `sol::function` call in a `try...catch(sol::error)` block to achieve the same safety as with `sol::protected_function`?
* Does a `sol::protected_function` call need to be wrapped in a `try...catch(sol::error)` block at all? Or can we only check for errors by checking `valid()` on the return value?

**Comment by ThePhD** [comment]
From the docs:

> ... with heavy protection and a potential error handler for any Lua errors and C++ exceptions

So, no. You don't need to wrap it in anything, unless you know for a fact that the function you called is something you're managing yourself (by pushing a `int my_function(lua_State* L)` free function into Lua through sol2, which it considers to be a [raw function](http://sol2.readthedocs.io/en/latest/errors.html#raw-functions)).

Finally, we go into detail about why what you describe in your first bullet is unsatisfactory for dealing with Lua on the [error page in the docs](http://sol2.readthedocs.io/en/latest/errors.html#catch-and-crash). Particularly:

> However, in almost all cases, when Lua calls lua_atpanic and hits this function, it means that something irreversibly wrong occured in your code or the Lua code and the VM is in an unpredictable or dead state. Catching an error thrown from the default handler and then proceeding as if things are cleaned up or okay is NOT the best idea. Unexpected bugs in optimized and release mode builds can result, among other serious issues.

Also keep in mind the following (from the docs):

> Lua is a C API first and foremost: exceptions bubbling out of it is essentially last-ditch, terminal behavior that the VM does not expect.

This means that an exception bubbling out of the code -- even when Lua is built as C++ -- will result in undefined or explosive behavior. Please use `valid()` from `protected_function` if you do not have 100% perfect control of your script. You may also force `sol::function` to default to its protected form by adding defines described on [the safety page](http://sol2.readthedocs.io/en/latest/safety.html) (`SOL_SAFE_FUNCTIONS`).

Finally, I decided to clobber this and a bunch more information about this into a single page, since people kept missing it in the `protected_function`, `function`, `errors` and `function tutorial` pages: http://sol2.readthedocs.io/en/latest/functions.html
