### ISSUE TITLE
create_table_with and functions

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#439]
This is either a bug or a lack of documentation.

The following breaks:
```
sol::state lua;
sol::table foo = lua.create_named_table("foo",
    "bar", lua.create_table_with(
        "func", []() { OutputDebugString("Hello world!"); }
    )
);
lua["foo"]["bar"]["func"](); // boom, "attempt to call a sol.ScriptManager::{ctor}::<lambda_9b241a4ca3e65bf00371ee21ae024d10> value"
```

But this works:

```
sol::state lua;
sol::table foo = lua.create_named_table("foo",
    "bar", lua.create_table_with(
    )
);
sol::table bar = lua["foo"]["bar"];
bar.set_function("func", []() { OutputDebugString("Hello world!"); });

lua["foo"]["bar"]["func"](); // okay!
```

Shouldn't a function inserted into a table via `create_table_with` behave just the same? I am trying to create tables that kind of represent my C++ namespace via create_table_with, and having to set the functions manually outside the `create_table_with` call would make things very untidy. So I hope this is just a bug that can be worked around.

**Comment by ThePhD** [comment]
It's not a bug.

A lambda is a struct with a `return_type operator()( args... )` signature somewhere in it. When you do `create_table_with`, sol2 has NO idea if that's a regular struct that just happens to have a `operator()` on it, or whether that's a lambda (and there's no way to tell). The second blurb of code works because `set_function` provides context to sol2: it tells you that it's a function, so even if you had me an object, I know it's a function.

This _is_ mentioned in the documentation, in the function tutorials, but I just moved it and much other information to a top-level "functions" category on sol2's page so that it's more visible for people who don't read the tutorials: http://sol2.readthedocs.io/en/latest/functions.html#working-with-callables-lambdas

**Comment by sagamusix** [comment]
Thanks for the clarification. I kinda of expected to find this information in the table section rather than the function section, so maybe mentioned there (a cross-reference with a link would be enough) would be a good idea.

**Comment by ThePhD** [comment]
I will add that now.

Note that you can also use `create_table_with`, but wrap your function-types with `sol::as_function( my_func )` to disambiguate.

**Comment by ThePhD** [comment]
This information is noted and linked now under the `set` documentation and `create_table` documentation for both table and state: http://sol2.readthedocs.io/en/latest/api/table.html#set-value

**Comment by sagamusix** [comment]
Thanks, `create_table_with` combined with `sol::as_function` is precisely what I needed. With that hint in the table section in place, I would probably have figured it out on my own. :)

**Comment by ThePhD** [comment]
Do let me know if there's any other things in the docs that don't make sense: most of them I write by forging them through what users understand. Since I am the one who created sol2, what's obvious to me or in the right place for me is often nowhere near where it should be for the average user.
