### ISSUE TITLE
get<std::string> does not work for booleans

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#442]
```
sol::state lua;
lua.script("a = true");
lua.script("b = 2");
auto s1 = lua["a"].get<std::string>();
auto s2 = lua["b"].get<std::string>();
```
`s1` is empty, `s2` is "2". Kind of asymmetical behaviour and I would expect `s1` to contain "true".

**Comment by rohlem** [comment]
I can't speak for sol's design goals in these aspects, but under the hood Lua has a lot of facilities for treating numbers as strings and vice-versa (see [`the 5.3 manual` on the topic](https://www.lua.org/manual/5.3/manual.html#3.4.3)), so the current behaviour is probably a remnant of that behaviour. Boolean is a separate type however, which does not exhibit such behaviour built-in.
From a Lua-side, turning _anything_ into a string is usually done via the global function [`tostring`](https://www.lua.org/manual/5.3/manual.html#pdf-tostring). Explicitly requesting the conversion should be fairly trivial, along the lines of (untested):
```
std::string get_as_string(sol::state_view& lua, sol::object o) {return lua["tostring"](o);}

sol::state lua;
lua.script("a = true");
std::cout << "Boolean converted to string: " << get_as_string(lua, lua["a"]) << std::endl;
```

**Comment by sagamusix** [comment]
Well, I noticed that the Sol2 code already implemented such conversions in other places (e.g. `luaL_tolstring`) which already turns booleans into "true" and "false" strings, hence I was thinking that this is most likely an omission in the `get()` implementation.

**Comment by ThePhD** [comment]
boolean -> string is not something the Lua C API does by default.

Automatic number-to-string conversions are the C API's devil that it needs to maintain, and yes it does produce a surprisingly poor expectation when it comes to other "conveniently stringable" types.

If you turn on `#define SOL_CHECK_ARGUMENTS` (see the (safety features)[http://sol2.readthedocs.io/en/latest/safety.html]), the string -> number thing is not allowed by sol2 at all, and only direct 1-to-1 translations are permitted (strict type-safety). Your scripts would fail and you wouldn't develop this idea to begin with.

For new projects, we encourage you turn on `SOL_CHECK_ARGUMENTS` while you get development going. It might seem a bit stifling at times but it will certainly keep you from making mistakes. You can turn it off when you're doing optimized builds and non-debug builds.

sol2 inherits from the C API, with minor feature enhancements here and there. The Lua C API itself does not call `tostring` automatically. The conversion we do is based off `luaL_tolstring`, but that C API function ONLY converts numbers to strings and strings to strings: it does not perform any other conversion. As @rohlem pointed out, this is a conversion hard-baked into the Lua language, since Lua 5.1.

If you want to `tostring`, then you should write a function that takes a `sol::object`, then inspect its `get_type()` return value, and then convert that way. OR, you can attempt to call the `tostring` function from Lua on it and see if it returns what you want.

**Comment by ThePhD** [comment]
Finally, I don't think `lua_tolstring` does what you think it does: the documentation [states very clearly that it only works for numbers and strings](https://www.lua.org/manual/5.3/manual.html#lua_tolstring).

Despite having `to` in its name, it doesn't actually coerce any values to a string (except for numbers, which the reason for that was discussed in other posts). It's slightly deceptively named, certainly, but unfortunately it doesn't behave like, say `boost::lexical_cast` or your typical `tostring` from Lua.

**Comment by sagamusix** [comment]
Okay, so just to be sure, would this be a sensible implementation for overriding Lua's print then? (The goal is to display the text in my GUI more or less the same way as Lua's print would do.)
```
sol::state lua;
(...)
lua.set_function("print", [this](const sol::variadic_args &va)
{
	std::string text;
	for(const auto &a : va)
	{
		text += ToString(a.get<sol::object>()); // was: text += a.get<std::string>();
	}
	text +="\n";
	AddToHistory(text);
});
```
Where ToString is defined as
```
std::string ToString(sol::object o) const
{
	return lua["tostring"](o);
}
```

**Comment by ThePhD** [comment]
Sure. Just remember that tables will print strangely (some internal pointer id) and userdata will often just print out their pointer value (unless the `__tostring` metamethod is overridden).

Your thing will glue everything together without any kind of whitespace inbetween. You should be careful of that.

**Comment by sagamusix** [comment]
Yeah, I already figured out that tables don't look very nice, so I think I will add a work-around for that. My usertypes already have __tostring overrides.

> Your thing will glue everything together without any kind of whitespace inbetween. You should be careful of that.

Whoops, thanks for noticing! :)

**Comment by ThePhD** [comment]
I should probably add this here. We have support for allowing numbers to be made into strings (but not booleans still, sorry!). You just have to define `SOL_STRINGS_ARE_NUMBERS`, as written about here: http://sol2.readthedocs.io/en/latest/safety.html#config

**Comment by sagamusix** [comment]
Ah, cool, I'll keep that in mind. Currently my Lua stuff is on hold but it should be useful soon-ish.
