### ISSUE TITLE
for...in with custom containers?

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#443]
I built a custom container, and I can use it like this without problems:
```
for k,v in pairs(mod.samples) do print(k, "=", v.frequency) end
```
I have to admit I'm not very experienced in actually writing Lua code so I'm not sure where the difference is, but suppose I just want to iterate over the data itself, this gives an error:
```
for v in mod.samples do print(v) end
> ERROR: attempt to call a sol.Scripting::SampleListProxy* value
```
However, there are library functions such as `io.lines()` where you can just iterate over an array exactly like that. Is my container implementation missing something for this to work, or is it something that could be added automatically by sol2 when binding my container, or do I have to do it myself (how)?

**Comment by rohlem** [comment]
The `for ... in ... do` syntax is a part of Lua and has not a lot to do with sol2 in particular; see the Lua reference manual for your version for details ([here's the relevant part for 5.3](https://www.lua.org/manual/5.3/manual.html#3.3.5))
As the manual explains (second half of chapter `3.5.5` for 5.3):
`for var_1, ···, var_n in explist do block end` 
`explist is evaluated only once. Its results are an iterator function, a state, and an initial value for the first iterator variable. ` (see [`next`](https://www.lua.org/manual/5.3/manual.html#pdf-next) for details on iterator functions, might be a bit tricky to get right)
For this reason alone the construct you presented cannot work, because mod.samples is only ever a single value according to Lua's syntax rules. That is why the `pairs` function and similar utilities exist (the old `in <table>` syntax was a special case and deprecated back in 5.1 I think). As you've found, `io.lines()` returns values that accord to those required specifications.
You could write your own wrapper function, possibly supply it as part of your usertype's methods using sol2, and then iterate with method calling syntax, f.e. as `for k,v in mod.samples:data_iterator() do --[[...]] end` .

**Comment by rohlem** [comment]
All that being said, I'm not strictly familiar with the `pairs` implementation in sol2 (haven't used it yet), however `pairs` is intended to iterate over _all_ `key`-`value` pairs of your collection.
So if you `just want to iterate over the data itself` then `pairs` is probably the way to go anyway... if some data _doesn't_ show up, please further explain your code setup etc. in a reproducible manner.

**Comment by sagamusix** [comment]
> So if you just want to iterate over the data itself then pairs is probably the way to go anyway... if some data doesn't show up, please further explain your code setup etc. in a reproducible manner.

No, it does work as expected, I was just wondering if the other syntax could be used for brevity in this particular example. As said, I'm not very familiar with Lua yet, so I'm not exactly sure how some things work there or what the best practices are.

**Comment by ThePhD** [comment]
I need more information to solve your problem.

What is the type of `Scripting::SampleListProxy` ? If it has `begin` and `end` functions that have iterators it should push as a type that's identified as a `container_usertype`.

**Comment by rohlem** [comment]
To clarify, `for k,v in pairs(mod.samples) do ... end` works without issue.
The version without a call to `pairs` doesn't work, as the object (here a `SampleListProxy*`) is interpreted as an iterator function (and called with the second value, not provided therefor defaulting to `nil`).
The only fix for that I could think of were if sol additionally overloaded the `__call` metamethod of the usertype to return a stateful iterator function that accepts `nil` as initial parameter... which might lead to confusion in other use cases.
