### ISSUE TITLE
Any way to set overloaded methods bound with an instance?

### ISSUE THREAD

**Issue by free-easy** [ThePhD/sol2#445]
I would like to set some overloaded class methods as global function in lua.

By reading the documentation I've seen that in order to set overloaded functions I can do something like this
```cpp
class A
{
public:
	void func(int, int);
        void func();
	void registerFunctions();

private:
	sol::state lua_;
}

...

void A::registerFunctions()
{
	lua_.set_function("func", sol::overload(static_cast<void (A::*)()>(&A::func),
						static_cast<void (A::*)(int,int)>(&A::func)));
}
```

But with this implementation I would have to pass an instance of the class in lua
```lua
func(instance, number1, number2)
func(instance)
```
Instead the kind of configuration file that I'd like to have is this
```lua
func(number1, number2)
func()
```
I've tried to pass `*this` to  `set_function` but it doesn't work
```cpp
void A::registerFunctions()
{
	lua_.set_function("func",
			  sol::overload(static_cast<void (A::*)()>(&A::func),
				        static_cast<void (A::*)(int,int)>(&A::func)),
			  *this);
}
```
Is there anything I've missed in the documentation or is there any trick to accomplish this?

If this is not the right place for this kind of questions please pardon me!

**Comment by rohlem** [comment]
You can use lambdas to pass the instance along with the function, like so:
```
void A::registerFunctions()
{
	lua_.set_function("func",
			  sol::overload([this]()            {this->func();},
				             [this](int a, int b){this->func(a, b);});
}
```
For more about lambdas (a pure C++ feature in and of itself, not directly related to sol), see [here](http://en.cppreference.com/w/cpp/language/lambda).
(Note that this stores a reference to the object, via the `this` pointer, so you need to make sure your `A` object is still alive when you call those functions, which is however a given, because the lua state itself is owned by the `A` object. Starting with C++17 you can alternatively capture separate copies by writing the capture as `[*this]`.)

**Comment by free-easy** [comment]
@rohlem It works! Thank you so much!!
