### ISSUE TITLE
UB using thread-local Lua contexts

### ISSUE THREAD

**Issue by oxidase** [ThePhD/sol2#458]
OSRM uses thread-local Lua contexts to parse OSM tags in parallel.

After updating dependencies, https://github.com/Project-OSRM/osrm-backend/pull/4304 introduces a line https://github.com/ThePhD/sol2/blob/504f49f3c71d7309c640bfddc51980ba01680f51/sol/state.hpp#L69
that leads to a data race UB because creating a new thread-local Lua context modifies and shares a global state via [`h`](https://github.com/ThePhD/sol2/blob/504f49f3c71d7309c640bfddc51980ba01680f51/sol/protected_function.hpp#L34)

Is there any way to avoid the global state sharing in Sol2?

**Comment by ThePhD** [comment]
This was something I was actually afraid of when the feature was requested.

The feature-request was so that people could set a "default handler" for their protected functions. This worked for 99% of people using a single Lua state that did the heavy lifting.

`static sol::reference h`'s initialization is defined by the C++ standard to be thread-safe upon creation, but since I don't return a copy reading/writing can produce a data race.

As of right now, I don't know how to keep the feature-request alive and solve this problem. There's 2 options.

- Ripping out the default handler and forcing the user to specify a handler each time they create a protected_function. Slightly annoying.
- Store a map from `lua_State*` to `sol::reference` I will need to change the interface so that a user passes the `lua_State*` (or a sol::reference) upon performing a `get` operation for the handler, and then provide a map-lookup from `lua_State*` to `sol::reference` that contains the default handler. This will allow each state to have its own handler, and I can mutex the internal operation and prevent data races by returning a copy.

**Comment by oxidase** [comment]
@ThePhD i think the first option with an explicit call of `set_default_handler` outside of `state::state` to set a default handler can be ok, but still will not be a thread-safe solution if protected calls will be used within multi-threaded process. The second option requires a thread-safe global map.

**Comment by ThePhD** [comment]
This might also be made easier if I could find a place inside of the `lua_State*` where I could store a "this is the default handler sol2 will look for when not given one". The Lua C Registry doesn't quite cut it, as it's supposed to have integral keys only and not special string keys. I could create a semi-invisible table on construction of the `sol::state`, too. All of these seem a little bit heavier than what's required, however...

I'm sure there's somewhere in the `lua_State*` I can store this so I don't have to rely on a static, mutex-protected hash map from `lua_State*` to default handlers.

**Comment by sagamusix** [comment]
> I'm sure there's somewhere in the lua_State* I can store this

Maybe using lua_getextraspace would work? Users might already store their own stuff in there though (I do), so to keep that possiblity alive, sol2 would probably have to add extra functions for the user to set and get their extra data. The extra space could point to some data managed by sol2 which contains whatever you need, plus an extra pointer that can be used by the user.

**Comment by ThePhD** [comment]
Unfortunately, `lua_getextraspace` is 5.3 tech only.

I think my best solution is just to look for a global variable that has a name that's more or less impossible for someone to write in a standard script. It's how sol2's usertype metatables are stored into Lua as well, so I might as well follow suit.

**Comment by ThePhD** [comment]
This is now part of the tests (in a basic form, I have no idea if it will work completely) but it should be "thread clean" and not cause a data-race crash:

https://github.com/ThePhD/sol2/commit/104485bebd6908d3eeff2825d7f686e9632fb9e6

specifically: https://github.com/ThePhD/sol2/blob/104485bebd6908d3eeff2825d7f686e9632fb9e6/sol/protected_function.hpp#L60

The solution chosen was by making a special key that sprinkles some dopey unicode characters into a (short) key, and every time we need the default handler we access a unicode-garbage key that's supposed to live in the global table. If one never gets set, then it's no skin off anyone's back. `sol::state` continues to set one by default on construction, but it's local to the state (and every `lua_State*` is meant to belong to a single thread, unless you lock access to everything in the first place).
