### ISSUE TITLE
Cannot casting from sol::object to sol::proxy

### ISSUE THREAD

**Issue by longlt3** [ThePhD/sol2#469]
Hello sol2 team,
Thank you a lot for this library, I really love it from the first time I see it.
Maybe it's not an issue, then I'm not sure here is the place to ask (if not, forgive me).
How:
`lua["obj"]["lua_func"]();`
to:
**`sol::object obj = lua["obj"];`**
**`obj["lua_func"]();`**

Please let me know does sol2 support this feature ?

BTW, I'd like to notice that, in case we want to pass an usertype object into a function like this:
`CppClass cpp_obj;
lua["obj"]["lua_func"](cpp_obj)`

We have to call it like this: 
`lua["obj"]["lua_func"](lua["obj"], cpp_obj)`

Because in Lua (I'm sorry, I'm new Lua also), in order to call `function CppClass:lua_func(a_obj)` 
we have 2 options:
1. `obj:lua_func(cpp_obj)`
2. `obj.lua_func(obj, cpp_obj)`

And it seems `lua["obj"]["lua_func"](cpp_obj)` uses option `#2`
I cannot find any info about this in your tutorial.

Thank you for amazing lib!

**Comment by ThePhD** [comment]
`operator[]` access is allowed on `sol::table` and `sol::proxy`. It's also allowed on `sol::userdata`. You can convert a `sol::object` to something more suitable to call functions on or similar by using `is<T>()` and `as<T>()`, or just by setting the proxy directly to what you need:

````cpp
sol::userdata obj = lua["obj"];
userdata["lua_func"]();
````

Table access is not supported for `sol::object`, as in safety-mode object can be literally anything and has no guarantees about how a query will or will not work.

For your second question, no. You must use `lua["obj"]["lua_func"](lua["obj"], cpp_obj);` or something that is equivalent. The Lua C API does not automatically infer the "self" argument: you must provide it explicitly. The tutorial does not mention this because there is only one way to have it work when calling from C++. A full example:

````cpp
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	struct cpp_object {
		int value = 5;
	};

	struct test {
		int value = 0;

		int func(const cpp_object& obj) {
			std::cout << "func\t" << obj.value << std::endl;
			value += obj.value;
			return value;
		}
	};

	lua.new_usertype<cpp_object>("test",
		"value", &cpp_object::value
	);
	lua.new_usertype<test>("test",
		"func", &test::func
	);
	lua.script("function test:lua_func(obj) print('lua_func', obj.value) end");

	lua["obj"] = test{};
	cpp_object cppobj;

	lua["obj"]["func"](lua["obj"], cppobj);
	lua["obj"]["lua_func"](lua["obj"], cppobj);

	lua["test"]["func"](lua["obj"], cppobj);
	lua["test"]["lua_func"](lua["obj"], cppobj);

	// crashes
	//lua["obj"]["func"](cppobj);
	//lua["obj"]["lua_func"](cppobj);

	// crashes
	//lua["test"]["func"](cppobj);
	//lua["test"]["lua_func"](cppobj);
````

**Comment by ThePhD** [comment]
I will try to find a place to add this example so that there's less ambiguity.

**Comment by longlt3** [comment]
Thanks for your fast response
