### ISSUE TITLE
calling lua functions with variable amount of arguments (at runtime)

### ISSUE THREAD

**Issue by mrgreywater** [ThePhD/sol2#471]
In lua you can do something like that:
`print(table.unpack({"test", "test2"}))`
to dynamicall call a function with a variable amount of arguments only known at runtime. This doesn't seem to be possible with sol, you need to know the number of arguments at compile time. The only thing that looked like it could've worked, doesn't: 
```
    lua.set_function("printmultiple", [](sol::this_state L) {
        sol::state_view lua(L);
        sol::variadic_results results;
        results.push_back(sol::make_object(L, "test"));
        results.push_back(sol::make_object(L, "test2"));
        lua["print"](results);
    });
```

**Comment by ThePhD** [comment]
http://sol2.readthedocs.io/en/latest/api/variadic_args.html

**Comment by ThePhD** [comment]
Oops, I didn't quite understand what you were asking.

If you are trying to capture things from Lua, then `variadic_args` (linked above) is what you want. If you want to take a typical container and turn it into arguments to a function from C++, use [`as_args`](http://sol2.readthedocs.io/en/latest/api/as_args.html).

Finally, your code above _should_ work, but there was a slight bug in sol. There's a fix in the repo now but I'm still writing docs for the new container stuff...! I might push anyways so that you have access to the fixed stuff anyways...

**Comment by mrgreywater** [comment]
The docs don't say how to call a function from c++ with variadic_args ...

**Comment by ThePhD** [comment]
`variadic_args` will work for you if you are taking arguments from Lua and need to "pass them through" to another `sol::function` or function-alike in sol. For example:

````cpp
int main () {
    sol::state lua;
    lua.open_libraries(sol::lib::base);

    lua.set_function("my_print", [](sol::this_state L, sol::variadic_args args) {
        sol::state_view lua(L);
        lua["print"](results);
    });

    lua.script("my_print(1, 2, 3)");
    lua.script("my_print("bark", 24)");
    lua.script("my_print()");
}
````

If you need to build up the arguments from C++, then you can use `sol::as_args` with a preexisting container. `sol::variadic_results` (as you're using there) isn't exactly meant for what you're using, but in _should_ work (it doesn't right now because of a bug, and I'm trying to get rid of GCC warning errors before I push to the repo again with a fix for that and several other things).

**Comment by mrgreywater** [comment]
Thanks alot for fixing it, haven't checked sol::as_args, but it sounds like that's what I needed. Would love it if you could add documentation for that behaviour ;)
