### ISSUE TITLE
Access violation (protected_function_result - script)

### ISSUE THREAD

**Issue by mar-kub** [ThePhD/sol2#497]
Access violation if protected_function_result is used as return.

**Tested with:**
Mac OS 10.12.6
- Clang and sol 2.17.5
- G++-7 and sol 2.18.1
- Lua 5.2 & 5.3

**Test Case:**
```
#define TEST_SOL_ACCESS 1

#include <sol.hpp>
#include <catch.hpp>

TEST_CASE("sol/badScript", "[sol][nullptr]")
{
    sol::state lua;

    // protected_function_result
    // -> Access violation in struct getter<detail::as_value_tag<T>> (Line 6246 in 2.17.5):
    // "void* udata = *pudata;"
    // (pudata is nullptr)
    sol::protected_function_result resultA = lua.script("function a (b) end");

    // works
    lua.script("function a (b) end");

    // works
    sol::function_result resultB = lua.script("function a (b) end");
}
```

**Comment by ThePhD** [comment]
`script` returns a `sol::function_result`. It is not implicitly convertible to a `sol::protected_function_result`: by calling `script` in this manner you forego any safety because we discard any safety checks and other things.

The problem, of course, manifests as an access violation because `function_result` (and other proxy types, including `protected_function_result`) have an implicit converter to everything (and it might technically be legal).

If you want a `protected_function_result`, use `safe_script` for the time being while I work on a fix.

**Comment by ThePhD** [comment]
Eh, I added some new constructors with inline-implementations later.

https://github.com/ThePhD/sol2/releases/tag/v2.18.1
