### ISSUE TITLE
Functions in tables

### ISSUE THREAD

**Issue by ScruffyFurn** [ThePhD/sol2#501]
Is it not possible to have a function as an element of a table?
I.E 
intro = {
	say = 'Hello I am the Helper NPC',
	choices = {
                 choice1 = 'HELP ME',
                 choice2 = "LEAVE ME ALONE"
    },
	**f = function done() return 1 end**	
}

**Comment by Nava2** [comment]
Could you provide a full example, the one listed here should work with no concerns. 

Also, please see [Mastering Markdown](https://guides.github.com/features/mastering-markdown/) to aid in formatting.

**Comment by ScruffyFurn** [comment]
I thought so too, this is the full example really, I can not get the script to work with the function as part of the table. 

```lua
intro = {
	say = 'Hello I am the Helper NPC',
	choices = {
                 choice1 = 'HELP ME',
                 choice2 = "LEAVE ME ALONE"
    },
	onSelection = function selected(  )
	-- do stuff
        end
}
```

**Comment by Nava2** [comment]
You mean you can't execute the function?

**Comment by ScruffyFurn** [comment]
The script was throwing an error on load. Not sure if it was line endings or some voodoo, but after a reboot, clean and rebuild, the code above no longer errors ...

**Comment by ThePhD** [comment]
As a side note, your syntax was wrong. You can't give a function a name and also set it inside of a table. The error I receive when I run your code is this: `sol: syntax error: [string "..."]:8: '(' expected near 'selected'`

What that means is this
````
	onSelection = function selected(  )
	-- do stuff
        end
````
is illegal, because you are giving a name to the function when you're just trying to make a regular function object that gets set into `onSelection`. In the future, remove the name of the function if you're going to put it into a table. Please also read the free-to-find Programming In Lua book that's available online to familiarize yourself with Lua concepts, and be sure to read the errors sol2 provides you with.
