### ISSUE TITLE
Consider using clang-format

### ISSUE THREAD

**Issue by Nava2** [ThePhD/sol2#502]
In the [CONTRIBUTING](https://github.com/ThePhD/sol2/blob/develop/CONTRIBUTING.md) you have specification about the code style. Might be smart to utilize clang-format to auto-format/enforce formatting for code contributions.

Documentation: https://clang.llvm.org/docs/ClangFormat.html

**Comment by ThePhD** [comment]
I'm going to be perfectly honest: I never used clang format and I never actually formatted my code when I worked on sol2. Back in the original sol, the guidelines were set out by the progenitor -- Rapptz -- and I've more or less kept them intact (though now I think I freely use tabs and not spaces, aha).

I might actually remove that part of the CONTRIBUTING, since I sort of don't really care too overtly much about it (and I'll likely hit any pull request with my formatting anyhow before I make a release out of it).

**Comment by Nava2** [comment]
I found it really useful to keep consistency. Additionally, you can easily hook up Travis to check for compliance.

**Comment by ThePhD** [comment]
We have a shiny file. I haven't used it yet: https://github.com/ThePhD/sol2/blob/develop/.clang-format

**Comment by ThePhD** [comment]
I've clang formatted the hell out of everything.
