### ISSUE TITLE
shared_ptr runtime cast base class casting

### ISSUE THREAD

**Issue by Ung0d** [ThePhD/sol2#505]
I recently updated to the latest sol version (from an old version half a year old). The following error occured when trying to compile existing code (that worked before). 

The problem is that sol seems to be unable to perform runtime casts form shared_ptrs of derived classes to shared_ptrs of base classes, like in the following example. It throws an error when passing a shared_ptr< derived > to a method then expects a shared_ptr< base >.

```
#include "sol.hpp"
#include <memory>

struct A {};

struct B : public A {};

int main()
{
    sol::state lua;

    lua.new_simple_usertype<A>("A");
    lua.new_simple_usertype<B>("B", sol::base_classes, sol::bases<A>());

    lua.set_function("test", [] (const std::shared_ptr<A>& aptr) {});

    std::shared_ptr<B> b_ptr = std::make_shared<B>();
    lua["b_ptr"] = b_ptr;

    lua.script("test(b_ptr)"); //throws error

    return 0;
}

```

**Comment by ThePhD** [comment]
It throws an error now because that code is wrong, in the sense that Sol2 doesn't actually know how to do that cast in the slightest.

With no safety in that particular case sol2 was just `reinterpret_cast`ing a blob of `void*` from the original `shared_ptr<B>` to the `shared_ptr<A>`. Put more clearly:

````
// fine enough
std::shared_ptr<B> b = std::make_shared<B>();
void* ptr_to_B_shared_ptr = static_cast<void*>(static_cast<std::shared_ptr<B>>(std::addressof(b)));
// sometime later...
...

// oh god
std::shared_ptr<A>* ptr_to_A_shared_ptr = 
     static_cast<std::shared_ptr<A>*>(ptr_to_B_shared_ptr);
const shared_ptr<A>& aptr = *ptr_to_A_shared_ptr;

test_lambda(aptr); // oh my god please no aaah
````

That it managed to work for a year and a half for you is beyond surprising: you should have segfaulted at least 5000 times if you had any code depending on that behavior with any non-trivial class layout. I'm almost curious as to see what the classes looked like for that code to have worked for so long...!

**Comment by Ung0d** [comment]
Hmmm baited indeed.
My actual codebase is really just a more complicated version of the code sketch above, but works basically the same. I initially though that sol did a static_pointer_cast before, but not in the more recent version.
Anyway, why can't sol do such a pointer cast for me and what would be a solution to the problem?
I mean a solution other then just replacing the method(base pointer) with method(derived pointer) for each derived type.

**Comment by ThePhD** [comment]
# Short Answer
Use a raw pointer, we can check those:

````
#include "sol.hpp"
#include <memory>

struct A {};

struct B : public A {};

int main()
{
    sol::state lua;

    lua.new_simple_usertype<A>("A");
    lua.new_simple_usertype<B>("B", sol::base_classes, sol::bases<A>());

    lua.set_function("test", [] (A* aptr) {});

    std::shared_ptr<B> b_ptr = std::make_shared<B>();
    lua["b_ptr"] = b_ptr;

    lua.script("test(b_ptr)"); // :+1:

    return 0;
}
````

# Long Answer

sol2 keeps track of what the core type of something is. By "core type", I mean every single type is uniquely identifiable by its own metatable with a name based on its class name (C++ class names are unique, so this is a fairly decent metric).

When you push a `shared_ptr` (or a `unique_ptr`), we classify it as a "unique usertype": http://sol2.readthedocs.io/en/latest/api/unique_usertype_traits.html

We can uniquely identify these types on the per-object level in Lua because we store a deleter with them that has a unique function pointer in memory: http://sol2.readthedocs.io/en/latest/api/usertype_memory.html#for-std-unique-ptr-t-d-and-std-shared-ptr-t

This allows us to check if something _is_ of one type or another type. The problem grows more complex, however, when you want to enable casting unique usertypes. `std::shared_ptr<B>` does not derive from `std::shared_ptr<A>`. How do we know your special type is castable to that type? The answer is we really don't, at all.

In my example, all of that code is laid out for you in one lexical scope. You can reasonably say "well let's just do the cast". I don't have that liberty: What Lua does conceptually is start me off here:

````
void* blob = lua_touserdata(state, stack_index); // uh, what are you exactly?
````

This means we have to store a modicum of type information at runtime and perform the necessary checks for safety. Performance further degrades when we do base class support, as we have to query this runtime information and essentially do a linear shotgun check against every single potential base class you specify with `sol::base_classes`.

We would need to automatically expand this system for every type that is considered a `unique_usertype`. Now consider that we have to do this at runtime. And remember, we don't get the benefit of knowing if your class is "compatible": we start from a `void*`, we check a metatable that's based on type `T`, know that it's fuzzily of type `T`, and then there's a bunch of garbage that MAY exist after it. We can directly check that what you're asking for is a `shared_ptr<T>`, but we don't know if it's a `shared_ptr<U>` or a `shared_ptr<V>`. We would need to insert class-specific casting knowledge to go from `void*`, to `shared_ptr<Derived>`, to `shared_ptr<Base>`. And we'd need to make sure to do it to the _internals_ of the unique usertype.

Furthermore, you run into problems: `A` may be copyable, but `std::unique_ptr<A>` is not. What if someone tries to take a `const std::unique_ptr<A>&` ? How do you support the casting situation for that?

This is essentially a nightmare to support. And it doesn't seem logically feasible. Just use a raw pointer: Lua owns the memory anyways and taking a `const shared_ptr<T>&` as an argument is kind of useless to begin with: just take a raw pointer.

**Comment by Ung0d** [comment]
Well that totally makes sense. Thx for taking the time and writing the long answer. I totally share your confusion now why this worked in the first place. :D

Unfortunately the short answer is no valid solution for me. I'm writing a script embedding for a gui-library, where widgets are stored as shared_ptrs and I need the existing shared-ptr to add a widget to the gui. So if I don't find a way to get rid of the shared-ptrs in every peace of code that touches lua at all, there is no other solution than write the addWidget(shared_ptr< derived >) method for every derived type, am I right?

**Comment by ThePhD** [comment]
Unfortunately, that's your only UB-clean way of doing it. Since it's tedious, you could write some template functions to make generating the derived versions easier.

````
template <typename T> void add_widget ( gui_type& g, std::shared_ptr<T> derived ) {
     g.addWidget( derived ); // or whatever it is
}
````

Then you spam that wherever it's needed. Asides from that? Maybe a macro you can dump out to do something similar to the above, and you have to manually add a type to it each time. I don't know: tackling the "this is a wrapper but it's totally a derived wrapper that can be converted to a base wrapper oh and we have no idea what type it truly is good luck hehehehe" is not a problem I can solve with what C++ offers me at the moment. It would take some serious thinking and architecting on my part not to send the system's performance to the garbage bin over this one feature.

If you're brave/foolish, you can also turn off `SOL_CHECK_ARGUMENTS` and all other type safety and just... let it do what it did before. Not exactly recommended, however...

**Comment by ThePhD** [comment]
I took some time to try some implementations and think about this. The ultimate problem is that the conversion from `shared_ptr<derived>` to `shared_ptr<base>` is a compile-time one, and one that works on value-types no less: there's no way for me to return one properly in sol2.

You'll have to use the above suggestion, or some other cleverness, to get what you need. Sorry. :(
