### ISSUE TITLE
Sol2 binding C++ function to table

### ISSUE THREAD

**Issue by lost-guadelenn** [ThePhD/sol2#512]
Hi.

That's probably not a bug. I have some difficulties using the library.
My use case is a basic one, so I must miss something.
However, the documentation doesn't help.

Below is my crosspost from stackoverflow.

***

I'm using sol2 library as a lua wrapper in my C++ code.
Everything works fine.
However, I fail to understand how to bind a C++ function to a table.

Sol2 documentation has many examples of how to bind a function to the global table.
But I can't find any example of binding functions to a non-global one.

This is how you are supposed to bind a function to the global table:

	sol::state lua;
	lua.set_function("DoLog", &TestClass::DoLog, testObj);

Then you call it from lua as simple as:

	function TestTable:testFunc()
	    DoLog("test string")
	end

This works as expected: TestClass::DoLog func gets called and "test string" parameter is properly passed.

Now I want to create several lua tables based on TestTable and bind a separate C++ object to each created lua table.
I have the following lua code, which allows me to instantiate lua tables:

    TestTable = {}

    function TestTable:create()
        local new_inst = {}
        TestTable_mt = { __index = TestTable }
        setmetatable( new_inst, TestTable_mt )
        return new_inst
    end

    function TestTable:testFunc()
        self:DoLog("test string")
    end

Next, I use the above code like this:
	test1 = TestTable:create()
	test2 = TestTable:create()

	test1:testFunc()
	test2:testFunc()

Now, I want C++ function to be bound to "test1" table.
I write 
    lua["test1"].set_function("DoLog", &TestClass::DoLog, this);
But this gives me compilation errors.

A second attempt:
    lua["test1"]["DoLog"].set_function(&TestClass::DoLog, this);
Now, &TestClass::DoLog gets called, but no arguments are passed!

What am I missing?

Thanks!

**Comment by ThePhD** [comment]
Your second attempt is correct in what it's supposed to be doing. However, it is fundamentally flawed in the thinking of what would happen.

`TestTable` is not a C++ class. You pass `self` to `DoLog` by using the syntax `self:DoLog()` in `testFunc`. Remember that anything of the syntax `obj : func( params... )` expands to `obj . func( obj, params... )`. Not only that, but when you do `lua["test1"]["DoLog"].set_function( &TestClass::DoLog, this );` you **already explicitly bind the `this` parameter**. This means that you cannot -- and should not -- use the syntax `self:DoLog`, because you've already bound the `self` expression.

Change the code in Lua to just be `DoLog("test string")` and you should see the expected output. Or, simply use `self.DoLog( ... )` (notice the lack of a colon, `:`).

You get no arguments / get _bad_ arguments -- and no errors happen -- because you do not turn safety on. If you check at the top of all the examples and documentation, this code would have crashed/error'd on you with a descriptive type failure if you had `#define SOL_CHECK_ARGUMENTS 1` before you included sol2. See the safety page to learn more about how you can catch several classes of programmer errors (at the expense of performance): http://sol2.readthedocs.io/en/latest/safety.html

**Comment by ThePhD** [comment]
As a side note, I updated the `namespacing` example in the Quick 'n' Dirty tutorial and in the examples folder to include binding a function under a table (e.g., it's 'namespace'): https://github.com/ThePhD/sol2/blob/develop/examples/namespacing.cpp

It does it from the C++ side, but the concept is much the same.
