### ISSUE TITLE
Issue compiling sol on OSX (xcode 8.2.1, LLVM 8.0). 

### ISSUE THREAD

**Issue by pjohalloran** [ThePhD/sol2#516]
I wonder if someone could help me. This is likely something  on my end.

Im trying to use sol2 with luajit. Previously using lua worked fine. I add the header like this:

`
#define SOL_USING_CXX_LUA

#define SOL_USING_CXX_LUAJIT

#include <sol2/sol.hpp>
`

I get an error in compilation:
`.../include/sol2/sol.hpp:2082:10: Cannot initialize return object of type 'char *' with an rvalue of type 'int'`

It seems strerror_r returns an int, not as expected a char *. Should i be using those 2 defines when trying to use luajit?

Thanks!

**Comment by mrgreywater** [comment]
you can probably workaround it by defining `#define COMPAT53_HAVE_STRERROR_R_XSI 1`
Seems like this line is not triggered when it should: https://github.com/ThePhD/sol2/blob/61d610bb70dfafb5b043b472b8afca53bc5d1171/sol/compatibility/compat-5.3.c#L38

**Comment by ThePhD** [comment]
# Short Story

I'm going to automatically turn on COMPAT53_HAVE_STRERROR_R_XSI when I detect apple-clang builds with XCode, probably using `__APPLE__` checks or similar.

# Long Story

This is a crappy problem that unfortunately I will continue to have to put glue and spit on to hold together because there is no good solution in standard C code.

The compatibility wrapper is taken from keplerproject/lua-compat-53 at the behest of another user. I had originally jerryrigged my own compatibility header from an older version, and it worked, but we wanted to "Live at Head" of the lua-compat-53 repo. I said yes, I changed the compat code, and now I defined this monstrosity of `strerror_r`/`strerror_s` to deal with dumb C std writers who decided never to standardize a reentrant `strerror` without making it an "optional extension" that, for some reason, everyone hates to implement.

In C++, I can solve this problem using overloading:

````
int check_strerror ( char* ) {
   // GNU strerror_r
}

int check_strerror( int ) {
    // POSIX strerror_r
}

int main () {
     check_strerror(strerror_r(0, nullptr, 0));
}
````

Unfortunately, the new compat headers are written in pure C. I don't get to use C++'s overloading, or type facilities, to avoid this problem. So now all I do is sit around and wait for these bug reports and start slapping on a million `#ifdef SOME_CRAP` until it builds.

As a side note, can you dump all the preprocessor symbols for me for your code? This is usually done with `clang++ -dM -E - < /dev/null`. Make sure to pass an input file containing a Short, Compilable example with your error in it, so I can know what preprocessor symbols to slap in.

**Comment by ThePhD** [comment]
Looks like __APPLE__ will do the trick: https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/strerror_r.3.html

**Comment by ThePhD** [comment]
Pull the single from latest and try again. Thanks for reporting.

**Comment by pjohalloran** [comment]
Wow amazing! Thanks for the quick response!

So I gave that a go using latest on the develop branch and compile error was fixed. Sweet!

I encountered a linking error then. I had a lot of lua related symbols missing. I found I had to wrap the luajit headers using extern "C" in order to successfully link. Does that sound right ?

So now when i run my program, I get a crash when creating the sol state on line [6222](https://github.com/ThePhD/sol2/blob/e36b9b3ab57b921f7f161ebde48b637feecd5d85/single/sol/sol.hpp#L6222). The lua state is null? 

Anyways thanks so much for the help so quickly.

**Comment by pjohalloran** [comment]
> As a side note, can you dump all the preprocessor symbols for me for your code? This is usually done with clang++ -dM -E - < /dev/null. Make sure to pass an input file containing a Short, Compilable example with your error in it, so I can know what preprocessor symbols to slap in.

Sorry @ThePhD, do you still want me to do this?

**Comment by ThePhD** [comment]
It probably won't be necessary anymore as the main lua-compat-53 repo has a more workable fix for `strerror_r` and all of its terrible versions, so I'll likely be pulling that to save myself the headache for all eternity.

Finally, I think what you should be doing is removing:
```
#define SOL_USING_CXX_LUA
#define SOL_USING_CXX_LUAJIT
````

Because unless you're Compiling Lua (not your program) in C++ mode, these are unnecessary. After that, you should remove the `extern "C"` wrappers, because what you're doing is essentially re-implementing the same work we do for you when you define (or not define) those 2 macros.

Finally, what is "your program"? I can't test what's going on if you don't give me a short, compilable example demonstrating your problem, or even a hint of a program that can let me create one to reproduce the problem for you.

**Comment by pjohalloran** [comment]
Cool thanks. I removed both those includes and still getting a crash.  I made you a minimal repo case so hopefully you can see it too [here](https://github.com/pjohalloran/sol2_crash_minimal).

Best not to show you with my project as its in a state of flux at the moment and too broken/difficult to demo there.

**Comment by ThePhD** [comment]
Like I said, I don't have a Mac, so I couldn't compile your XCode stuff. But,

````
#include <sol.hpp>

int main(int argc, char** argv) {
	sol::state* lua =new sol::state();
	return 0;
}
````

That compiled and ran fine for me (ignoring the fact that it's a memory leak). The modified version that does not leak:

````
#include <sol.hpp>

int main(int argc, char** argv) {
	std::unique_ptr<sol::state> lua(new sol::state());
	return 0;
}
````

Also does not crash for me. Any mac users in the mix who can confirm this for me?

**Comment by pjohalloran** [comment]
Ah yes, my bad on the leak.

**Comment by pjohalloran** [comment]
Here is a screenshot of the crash in Xcode. Trying to figure out how to send you a stack trace at the moment 👍 

![screenshot 2017-10-01 22 39 02](https://user-images.githubusercontent.com/2094081/31059397-69d4aa56-a6f9-11e7-8fb1-3896d2a416c6.png)

**Comment by pjohalloran** [comment]
Im guessing its not a sol2 problem, more a problem with how i have built luajit. It looks like `luaL_newstate()` is returning NULL.

**Comment by pjohalloran** [comment]
Tried building luajit as a dynamic lib as in the original luajit repo i cloned (https://github.com/LuaDist/luajit) but getting same crash. Feel free to close issue if you like. Not sure this is a genuine sol2 problem.

**Comment by mrgreywater** [comment]
Maybe we could at least throw an exception/assert that the result of lua_newstate is != nullptr to make debugging in the future easier. Reading from the documentation it's allowed to return a null pointer if you're out of memory.

**Comment by ThePhD** [comment]
@pjohalloran Try using vanilla Lua and see if the problem persists: then there's other things at play.

@mrgreywater If you're out of memory you have bigger problems than `luaL_newstate()` returning null, but anyone's welcome to add additional safety checks behind `SOL_CHECK_ARGUMENTS`.

**Comment by pjohalloran** [comment]
Will do, cheers for looking into this. Will report back this time tomorrow.

**Comment by pjohalloran** [comment]
Tried using vanilla lua and it works fine. No crash where i said. Any ideas ? I guess i could try linking with official luajit and not that cmake altered one?

**Comment by pjohalloran** [comment]
Im happy to use lua in my personal project.

But I could help you guys out with investigations of this if it is indeed a valid issue and you do not have access to a OSX machine to test?

**Comment by ThePhD** [comment]
If you don't need performance (you probably don't at this stage), I would simply recommend making the problem go away by using Vanilla Lua 5.3.

If you want to try and trouble-shoot your stuff, I would suggest building LuaJIT manually following its instructions and outputting the desired library. I do not remember if it has instructions specific for OSX. In any case, this looks a lot like a linking and library-building error than a sol2 one, so I'm not sure I can troubleshoot for you.

Best of luck.

**Comment by pjohalloran** [comment]
That’s cool.

It might be something like this:
https://github.com/PowerDNS/pdns/issues/4295

I’m curious what it is so I’ll luck more and let you know.

**Comment by pjohalloran** [comment]
LuaJIT crash I reported here was also reported in issue https://github.com/ThePhD/sol2/issues/530.

Using luajit flags LUAJIT_LINK_FLAGS fixed the issue in that case.

**Comment by ThePhD** [comment]
That's good to know. Thanks for getting back to me here: I'll add this to the documentation.
