### ISSUE TITLE
Define own type, made using `typedef`

### ISSUE THREAD

**Issue by egordorichev** [ThePhD/sol2#517]
Hi! I have a type, defined by `typedef`:

`typedef std::bitset<8> byte;`

How do I bind it to lua, so I can use functions with `byte` type, like:

```c++
void cls(byte color) {
	color &= 0xf;
	color = color << 4 | color;
	memset(VRAM_START, (byte) color, VRAM_SIZE);
}
```

Thank you!

**Comment by ThePhD** [comment]
Ditch the typedef and work from the bitfield example instead:

https://github.com/ThePhD/sol2/blob/develop/examples/usertype_bitfields.cpp

**Comment by ThePhD** [comment]
Ooh, disregard my last comment about the bitfield example, I misunderstood what you were trying to do exactly.

Still, I say "ditch the typedef" because `byte` is a common term that usually aliases to an integral type. `std::bitset` does not satisfy all the requirements of a typical integral type, and you're likely to start a fire if you carry that thing around for long. If you need exactly 8 bits in a byte, use `std::uint8_t` as your byte typedef, then perform all the same operations.

Finally, you can bind that function to work on your own type in Lua by doing:

````
struct bits {
     std::bitset<8> color;
};

void cls(bits& my_bits) { // notice the reference here
	my_bits.color &= 0xf;
	my_bits.color = color << 4 | color;
        int memset_value = static_cast<int>(my_bits.color.to_ulong());
	memset(VRAM_START, memset, VRAM_SIZE);
}

int main (int, char*[]) {
     sol::state lua;
     
     lua.new_usertype<bits>( "bits",
          "cls", &cls
     );

     lua.script("my_bits = bits.new()"); // or however you want to create it with Lua
     lua.script("my_bits:cls()"); // notice the colon : to pass 'self' here
}
````

If you want to bind a usertype to `std::bitset<8>`, you can. And it will apply above all things, but it won't bind to the "typedef" name. It binds to the original name after all the typedefs are stripped away. So you'd be making a "usertype" for everybody's `std::bitset<8>`, which is prooobably not want you want to do.

**Comment by egordorichev** [comment]
Ammm, you got me wrong :D `cls` shouldn't be a method of class. `cls` is api function. I just need to be able to use `byte` (8 bits) instead of `unsigned int` here.

**Comment by ThePhD** [comment]
If you're stuck with that function signature and API, then all you need to do is this:

````
typedef std::bitset<8> byte;

void cls(byte color) {
	color &= 0xf;
	color = color << 4 | color;
	memset(VRAM_START, (byte) color, VRAM_SIZE);
}

int main (int, char*[]) {
     sol::state lua;
     
     lua.set_function( "cls", &cls );

     lua["some_bits"] = byte(0x2); // or something
     lua.script("cls(some_bits)"); 
}
````

Noticeably, `std::bitset` is transferred as a userdata through Lua. This means that it's not trivially usable with a function that takes an integer. If you need more flexibility, you can attempt to define a customization point, but that should be enough to get you going.

Also note that even in the example from the last comment, you don't necessarily have to bind "cls" as a member function, either:

````
struct bits {
     std::bitset<8> color;
};

void cls(bits& my_bits) { // notice the reference here
	my_bits.color &= 0xf;
	my_bits.color = color << 4 | color;
        int memset_value = static_cast<int>(my_bits.color.to_ulong());
	memset(VRAM_START, memset, VRAM_SIZE);
}

int main (int, char*[]) {
     sol::state lua;
     
     lua.new_usertype<bits>( "bits" );
     lua.set_function("cls", &cls );

     lua.script("my_bits = bits.new()");
     lua.script("cls(my_bits)"); basically the same thing
}
````

The only different now is how you use the syntax (free function versus colon-based `self:`-call).
