### ISSUE TITLE
(Strongly-typed) enums and constructor overloading

### ISSUE THREAD

**Issue by mutex36** [ThePhD/sol2#518]
I have three strongly-typed enums:

```
a_State.new_enum("KeyboardMapping",
				"W", CrKeyboardMapping::W,
				"S", CrKeyboardMapping::S,
				"A", CrKeyboardMapping::A,
				"D", CrKeyboardMapping::D);

			a_State.new_enum("MouseMapping",
				"X", CrMouseMapping::X,
				"Y", CrMouseMapping::Y,
				"Scroll", CrMouseMapping::Scroll);

			a_State.new_enum("GamepadMapping",
				"LX", CrGamepadMapping::LX,
				"LY", CrGamepadMapping::LY);
```

And a type that has constructor overloads for all three:

```
			a_State.new_usertype<CrAxisMapping>("AxisMapping",
				sol::constructors<
					CrAxisMapping(CrKeyboardMapping, float),
					CrAxisMapping(CrGamepadMapping, float),
					CrAxisMapping(CrMouseMapping, float)>(),
				"Scale", &CrAxisMapping::scale);
```

The problem: sol always uses the first ctor and implicitly casts the arguments. Is there any way, if necessary by writing a thin wrapper, to have sol pick the right overload? What about `sol::overload`? Is ctor overloading implemented the same way?

**Comment by ThePhD** [comment]
"Strong Typing" for enums only exists in C++. They do not exist in Lua. When you do `new_enum`, you're creating a table of a specific key/name you pass as the first argument, plus a bunch of `string` -> `integer` lookup values. In other word, `GamepadMapping.LX` in Lua is just an integer.

Obviously, this becomes glaringly apparently when you try to overload based on those enums (because they're just integers, not real types). Here is a fix I can think of:

* Introduce a `strong<T>` template, where `T` is the name of the enum.
* Add a function to each and every `new_enum` that needs this, in the form of `"strong", [](CrMouseMapping value){ return strong<CrMouseMapping>( value ); }`
* Use it in Lua like `MouseMapping.strong( MouseMapping.X )`

There's probably some finagling you can do to make the syntax a little more bearable or something. I'm not exactly sure. Best of luck!
