### ISSUE TITLE
Protected call crashes on protected function result destructor

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#520]
Not sure if this is happening because of something I'm doing, but in some rare instances I'm getting an access violation exception inside the destructor of `soll:protected_function_result`, after calling a `sol::protected_function` like so:

```cpp
sol::protected_function_result result = someFunction(...);

if (!result.valid())
{
	std::string error = s_Result;
	std::cout << error << std::endl;
}
```

It should be noted that the corresponding lua function does **not** return a value.

**Comment by ThePhD** [comment]
`std::string` is not the error type. In debug mode that code will throw an error. Use `sol::error` to inspect the error instead.

Do you have any other information about this? Is this a statically held function? A statically held result value? Do you have a stack trace? Does this happen at application runtime, or at exit? On garbage collection? Also, `s_Result` is not the same as `result`. Asides from that, no repro:

````
int main(int, char*[]) {
	sol::state lua;
	lua.script("function f () if (a == 1) then error('fug') end end");
	sol::protected_function some_function = lua["f"];
	
	std::size_t correct_count = 0;
	std::size_t error_count = 0;
	for (std::size_t i = 0; i < 1000000; ++i) {
		lua["a"] = i % 2;
		sol::protected_function_result result = some_function();
		if (!result.valid()) {
			if (i < 2) {
				sol::error error = result;
				std::cout << "an error occured (as expected)" << error.what() << std::endl;
			}
			++error_count;
		}
		else {
			if (i < 2) {
				std::cout << "all good :+1:" << std::endl;
			}
			++correct_count;
		}
	}

	std::cout << "correct_count: " << correct_count << std::endl;
	std::cout << "error_count  : " << error_count << std::endl;

	return 0;
}
````

![All good](https://i.imgur.com/phVVsTW.png)

**Comment by OrfeasZ** [comment]
Sorry, `s_Result` is a typo, it was supposed to be `result`. I changed my code to use `sol::error` instead, but I'm still encountering this. It seems to trigger a few random errors, in no particular order, some with empty "what" causes and some with "call", and then crashes at the same point.

I should note that this is under x86.

Is there a possibility that using sol across module and thread boundaries (though in a synchronized manner) could be causing this behavior?

**Comment by ThePhD** [comment]
I'm using x64.

If you're throwing exceptions and expecting those to be caught by sol2 and propagated properly, you're treading dangerous, swampy lands (especially in x86). This sounds like an exception is crossing boundaries, you're trying to catch it and then continue quietly, and it's blowing up in your face. What Lua version are you using, are you on LuaJIT? These are all important questions to answer.

I don't know about module implementations, those were supposed to still be experimental.

sol2 provides no threading safety; neither does Lua. People have used sol2 in threaded environments before with synchronized access and everything worked out fine. If you're having problems with coroutines in particular, see the threading page for information about it: http://sol2.readthedocs.io/en/latest/threading.html#working-with-multiple-lua-threads

This is the most I can do for you, since I have no other information for you.

**Comment by OrfeasZ** [comment]
The problem is, I don't think there's any exceptions being thrown inside the lua code. The lua function that I'm calling (`someFunction`) is empty.

**Comment by ThePhD** [comment]
I ran the above code on x86, nothing happened either. I removed the function body and left it empty, nothing happened on x86 or x64. What Lua version, what platform, is this function called inside of a DLL, from multiple threads at the same time? Multiple calls into a single Lua state is an absolutely bad idea because the Lua stack is essentially a shared global variable: using sol2 types or Lua C API functions from multiple threads without locking every operation around the ENTIRE state will result in you screwing up the stack with data races or -- worse -- things working just in time and leaving the expectations for Lua's stack subtly changed.

If you have multiple threads that need to share a Lua state, you need to lock every single operation for the entire state, including interacting with the results of function calls (because they are, like everythnig else, based on the stack).

**Comment by OrfeasZ** [comment]
Lua 5.3.4, MSVC140, x86 target using the x64 toolset. 

I do call these functions multiple times from multiple threads and from within a DLL, but all calls are protected by a mutex (`CRITICAL_SECTION` in this case, I'll try using `std::mutex` to see if it makes a difference). I noticed that I had an empty if statement in one of those functions. Removing that if statement just makes my app freeze but I haven't had much time to debug that yet.

**Comment by ThePhD** [comment]
You can't just protect the function call. You need to protect the **entire** block:

````
std::lock_guard guard(my_mutex);
{
     sol::protected_function_result result = someFunction();
     if (!result.valid()) {
          sol::error err = result;
          std::cout << "error occurred: " << err.what() << std::endl;
     }
}
````

If you protect just the call, then access using `protected_function_result` and its destrutor will not be synchronized (the stack is accessed in the object's destructor).

**Comment by OrfeasZ** [comment]
I have protected the entire block. Anything calling into or out of lua is inside a function that can only be exclusively accessed.

**Comment by ThePhD** [comment]
I still have not been able to repro this, and I can't get it to die on x86, x64 with various kinds of functions and setups. I haven't tried putting the code in a DLL and tossing things.

**Comment by OrfeasZ** [comment]
I've started to believe that this is indeed a concurrency issue. It seems that there's an edge case where the execution path calls into lua without proper synchronization. Currently working on figuring out what that code path is. Will update if I have any updates.

**Comment by ThePhD** [comment]
Let me know if anything else goes awry. 🤷‍♂️
