### ISSUE TITLE
How to register a lua function and call the lua function later in c++

### ISSUE THREAD

**Issue by ryancheung** [ThePhD/sol2#528]
Give I'm developing a game. There're many game event, e.g. player log-in, logout, etc.
I may need to register a lua function for the logout event. When player log out, it calls the registered lua function.

I've read the tutorial, not sure how to do this. 

Appreciate for the helps.

**Comment by ryancheung** [comment]
```cpp
#include <sol.hpp>

EventBindings["player"] = {};

std::string RegisterPlayerEvent( int event, std::function func) {
    // store the lua function and then call func if event happens
    EventBindings["player"].push_back(func);
}

void OnPlayerLogout(Player* player)
{
    for (auto func: EventBindings["player"])
        func(1, player);
}

int main () {

        sol::state lua;

        lua["RegisterPlayerEvent"] = RegisterPlayerEvent; // way 1

        lua.script("RegisterPlayerEvent(1, function (event, player) ; // Do something for player. end)");
}
```

Maybe something like this?

**Comment by ThePhD** [comment]
It looks like you've gotten a good handle of it. I'm glad you're doing well!

Best of luck out there.

**Comment by ryancheung** [comment]
@ThePhD I want to store the registered functions in a map, and add `RemovePlayerEvent(func)` method to remove the function from the map. 

I know we can set sol::function as key in the map, but `sizeof(sol::function)` is 16, which seems too big and wasteful, I wonder if we can set any unique integer reference as map key?

**Comment by ryancheung** [comment]
Oops! 
```cpp
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/unordered_map:369:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:1952:21: error: no matching function for call to object of type 'hasher' (aka
      'std::__1::__unordered_map_hasher<sol::basic_function<sol::basic_reference<false>, false>, std::__1::__hash_value_type<sol::basic_function<sol::basic_reference<false>, false>, LuaEvent *>, std::__1::hash<sol::basic_function<sol::basic_reference<false>, false> >,
      true>')
    size_t __hash = hash_function()(__k);
                    ^~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/unordered_map:1436:21: note: in instantiation of function template specialization
      'std::__1::__hash_table<std::__1::__hash_value_type<sol::basic_function<sol::basic_reference<false>, false>, LuaEvent *>, std::__1::__unordered_map_hasher<sol::basic_function<sol::basic_reference<false>, false>,
      std::__1::__hash_value_type<sol::basic_function<sol::basic_reference<false>, false>, LuaEvent *>, std::__1::hash<sol::basic_function<sol::basic_reference<false>, false> >, true>, std::__1::__unordered_map_equal<sol::basic_function<sol::basic_reference<false>,
      false>, std::__1::__hash_value_type<sol::basic_function<sol::basic_reference<false>, false>, LuaEvent *>, std::__1::equal_to<sol::basic_function<sol::basic_reference<false>, false> >, true>,
      std::__1::allocator<std::__1::__hash_value_type<sol::basic_function<sol::basic_reference<false>, false>, LuaEvent *> > >::__emplace_unique_key_args<sol::basic_function<sol::basic_reference<false>, false>, const std::__1::piecewise_construct_t &,
      std::__1::tuple<const sol::basic_function<sol::basic_reference<false>, false> &>, std::__1::tuple<> >' requested here
    return __table_.__emplace_unique_key_args(__k,
                    ^
/Users/Ryan/MoltenCore/MoltenCore/src/game/LuaEngine/ElunaEventMgr.cpp:88:17: note: in instantiation of member function 'std::__1::unordered_map<sol::basic_function<sol::basic_reference<false>, false>, LuaEvent *,
      std::__1::hash<sol::basic_function<sol::basic_reference<false>, false> >, std::__1::equal_to<sol::basic_function<sol::basic_reference<false>, false> >, std::__1::allocator<std::__1::pair<const sol::basic_function<sol::basic_reference<false>, false>, LuaEvent *> >
      >::operator[]' requested here
        eventMap[eventId]->SetState(state);
```

sol::function cannot be a key of `std::unordered_map`

**Comment by ryancheung** [comment]
I have a class like this:
```cpp
struct LuaEvent
{
    LuaEvent(sol::function _funcRef, uint32 _delay, uint32 _repeats) :
        delay(_delay), repeats(_repeats), funcRef(_funcRef), state(LUAEVENT_STATE_RUN)
    {
    }

    void SetState(LuaEventState _state)
    {
        if (state != LUAEVENT_STATE_ERASE)
            state = _state;
    }

    uint32 delay;   // Delay between event calls
    uint32 repeats; // Amount of repeats to make, 0 for infinite
    sol::function funcRef;    // Lua function reference ID, also used as event ID
    LuaEventState state;    // State for next call
};
```

And a map:

```cpp
    typedef std::unordered_map<sol::function, LuaEvent*> EventMap;
```

**Comment by ryancheung** [comment]
The use case is simple: I registered a lua function and store it somewhere with other informations like delay/repeat count. So I need a map. How can we do this?

**Comment by ThePhD** [comment]
# Short Answer

Create a table in Lua and use that as your EventMap.

# Long Answer

Each `sol::reference` derived type (which includes `sol::function`, `sol::protected_function`, `sol::userdata`, `sol::table`, etc...) keeps a reference to the `lua_State*` and an integer key representing its storage in the registry. However, these keys are not unique to the item being references, even if they reference the same element:

````
sol::state lua;
lua["f"] = []() {};
sol::function f1 = lua["f"];
sol::function f2 = lua["f"];
// true
assert(f1 == f2);
// NOT TRUE!
// assert(f1.registry_index() == f2.registry_index());
````

This begs the question "how do we uniquely identify a single object?". The answer is using a Lua C API function called `lua_topointer`. If two objects are the same, they have the same `lua_topointer` value. Otherwise, they are different.

The problem is that storing it in C++ is a **BAD** idea. Lua is a garbage collected language: there is nothing stopping the virtual machine from changing the location of the function in memory after an operation is performed in the VM. Any storage of the `const void*` that comes from `lua_topointer` and trying to use that as the "identity" of the type will resort in bad sorting (for `std::map`) and bad hasing (for `std::unordered_map`).

The solution is to use a Lua table. Lua tables are hashmaps that are aware of its own internal implementation details. This means you do not have to poke at it or figure out the best way to store it. Lua can have functions be keys (it can have anything be a key), so it will more effectively solve your problem than trying to battle it out with sol2 or the Lua C API.

**Comment by ryancheung** [comment]
OK, and this means i have to implement the event processor(find and execute events) in lua, right?
e.g.: Expose a update method of event process class to C++, and let c++ call the update method.

**Comment by ThePhD** [comment]
I would recommend you do it in Lua, yes. You will likely save some amount of performance, especially if the function is readily available in Lua.

**Comment by ryancheung** [comment]
Thank you so much for helping, thank you~
