### ISSUE TITLE
SIZE_MAX was not declared in this scope

### ISSUE THREAD

**Issue by VaderY** [ThePhD/sol2#536]
Hey,

We got multiple error of `'SIZE_MAX' was not declared in this scope` while including the most recent single header version (6738ceedae7e2bea8882565a4fe6f5e9cd3c8bc8) of the lib using C++14 with GCC 5.2 in lines:
```
sol.hpp:1057:63
sol.hpp:11126:80
sol.hpp:11129:83
```
by defining the following macro before including sol2 we are currently bypassing the problem:
```
#include <limits>
#define SIZE_MAX std::numeric_limits<size_t>::max()
```
Please change from using `SIZE_MAX` to `std::numeric_limits<size_t>::max()`?

As always, Thank you for your hard work and dedication.

**Comment by ThePhD** [comment]
We must use `SIZE_MAX` because of `constexpr` constraints.

**Comment by ThePhD** [comment]
Pull from the latest release and try again. You should be fine.

**Comment by VaderY** [comment]
std::numeric_limits<size_t>::max() is a constexpr function

I tried your fix and it seams that in our compiler (which is ATM is: g++ (GCC) 5.2.1 20150902 (Red Hat 5.2.1-2)) is missing this define from <cstdint>

**Comment by VaderY** [comment]
g++ (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3) has the same issue

**Comment by ThePhD** [comment]
This sounds like a platform problem.

My push-back here is that `std::numeric_limits<blah>::bleh(...);` is not constexpr across compilers, even in C++14 mode. So I either pick the `SIZE_MAX` poison, or tell everyone below certain compiler versions to sod off.

I think at this point you should simply put the patch in front of your sol2 include. I can't do things like define `SIZE_MAX` (since it's standard) and trying to fill the holes in bad distributions are really difficult to keep up with.

We test with GCC 5.4, and the problem doesn't persist. Perhaps it's time to upgrade minor versions? GCC 5.4 is the default gcc-5 for all of ubuntu.

**Comment by ThePhD** [comment]
If you can find out if redhat defines SIZE_MAX anywhere (say, erroneously in `<climits>`), I can drop that define in there.
