### ISSUE TITLE
usertype value not being destructed if constructed outside lua VM?

### ISSUE THREAD

**Issue by chrsm** [ThePhD/sol2#537]
Hiya, thanks for sol2! I'm a huge fan of lua and new to actually writing C++, so this has been extremely fun to play around with. My apologies in advance if this is a really stupid question outside of the scope of sol2.

Code that highlights my issue: https://gist.github.com/chrsm/46e3a1335a66da46dce7534c3033ac2e

Essentially, I have a type `data_container` that can return either a `data_val` or `nullptr` on a call to `data_container::next`.

When creating/destroying `data_vals` in pure lua, the dtor is called as I'd expect.
When using a `data_container` created in lua and calling `next`, however, `data_val` dtor is never called, even after calling `collect_garbage` via sol::state. As a result, valgrind/etc say I am leaking memory.

How should I ensure that these values are being cleaned up properly from sol?

Compiler: clang++ 5.0.0
Build system: CMake

**Comment by ThePhD** [comment]
You *are* leaking memory. Every single time you directly call `next`. Your code leaks because you are manually using `new[]`/`new` and `delete[]`/`delete`. sol2 is very clear about it's ownership semantics, and what happens with Raw pointers. That is we DO NOT DELETE raw pointers, because raw pointers do not tell sol2 (me) what your intentions with that pointer are. Are you going to pass it off? Is it just a reference you don't intend to delete? Is it an array that needs `delete[]`, or a regular value that needs `delete` ? We talk about this here:

http://sol2.readthedocs.io/en/latest/tutorial/ownership.html

I am going to post your code back at you, with the necessary adjustments made to stop leaking memory. Notice that there is no raw `new` or `delete` within the code. We instead use wrapping, 0-overhead, lightweight classes called `std::unique_ptr` and `std::vector` to appropriately capture the semantics of your code while being resistant to memory leakage.

````
#include "deps/sol2/sol.hpp"
#include <cstdlib>
#include <iostream>
#include <string>
#include <cstdint>

#include <vector> // std::vector

struct data_val {
    data_val();
    ~data_val();

    std::vector<uint32_t> crap;
};

// initializing 10 elements with a value of 0
data_val::data_val(): crap(10, 0) {
// if you don't like the "constructor initialization" syntax, you can resize after 
// the member and base constructors run by putting statements
// in the constructor body
/* e.g.:
* crap.resize(10); // and anything else you want
*/
}
data_val::~data_val() {
    std::cout << "crap vector deleter called\n";
}

struct data_container {
    std::unique_ptr<data_val> next();
};

std::unique_ptr<data_val> data_container::next() {
    // can be null, but for simplicity's sake...
    std::unique_ptr<data_val> d(new data_val());
    return d;
}

int main(int argc, char *argv[]) {
    sol::state lua;
    lua.open_libraries();

    lua.new_usertype<data_container>("data_container", "next", &data_container::next);
    lua.new_usertype<data_val>("data_val",
        sol::constructors<data_val()>(),
        "crap", &data_val::crap
    );

    // properly deleted when created in lua
    lua.script("local d = data_val.new();\n"
        "d = nil\n"
        "collectgarbage()\n"
    );

    // not deleted when returned from data_container?
    lua.script(
        "local container = data_container.new()\n"
        "local done = false\n"
        "local d = container:next()\n"
        "d = nil\n"
        "print(\"set data_val to nil\")\n"
        "collectgarbage()\n"
        "print(\"not deleted?\")\n"
    );

    return 0;
}
````

Note that you can "tighten" the requirements here, if possible. For example, we use `std::vector` because most individuals need a resizable array. If your array is fixed in size and you want the minimal overhead but still have painless creation/deletion, use `std::unique_ptr<uint32_t[]>( new uint32_t[10] );`. You can store the size (`10`) in a `static const std::size_t crap_size = 10;` global constant so you're not using magic numbers everywhere, or just remember the number (global constants are preferred over just remembering the number and sprinkling `10` all over the place, which leads to overflows and bugs when you change the number in 9 places but forget the 10th spot).

Finally, since the array is very small in size, you _could_ ditch the heap allocation altogether and simply do [`std::array<uint32, 10> crap`](http://en.cppreference.com/w/cpp/container/array). No `unique_ptr` or `new` required.

Finally, since we're already running a train of unsolicited advice here: there are easier ways to iterate over a container that come from C++, especially if it's already a `std::vector` or any of the many [`std::` library containers](http://en.cppreference.com/w/cpp/container). sol2 explicitly supports iteration, so you don't have to make up a "next" scheme and flag `done`:

````
#include "deps/sol2/sol.hpp"
#include <cstdlib>
#include <iostream>
#include <string>
#include <cstdint>

#include <vector> // std::vector
#include <numeric> // std::iota

struct data_val {
	data_val();
	~data_val();

	std::vector<uint32_t> crap;
};

// initializing 10 elements with a value of 0
data_val::data_val()
: crap(10, 0) {
	// http://en.cppreference.com/w/cpp/algorithm/iota
	std::iota(crap.begin(), crap.end(), 5);
}
data_val::~data_val() {
	std::cout << "crap vector deleter called\n";
}

struct data_container {
	std::vector<data_val> values;

	data_container(int num_vals = 1);

	// required definition
	typedef typename std::vector<data_val>::value_type value_type;
	typedef typename std::vector<data_val>::iterator iterator;
	typedef typename std::vector<data_val>::size_type size_type;

	// begin/end iterators
	iterator begin() {
		return values.begin();
	}
	iterator end() {
		return values.end();
	}

	size_type size () const {
		return values.size();
	}
};

data_container::data_container(int num_vals /* = 1 */) : values(num_vals) {
}

int main(int argc, char* argv[]) {

	{
		sol::state lua;
		lua.open_libraries();

		lua.new_usertype<data_container>("data_container",
			sol::constructors<data_container(), data_container(int)>()
		);
		lua.new_usertype<data_val>("data_val",
			sol::constructors<data_val()>(),
			"crap", &data_val::crap);

		/* This:
		R"delim(
			...
		)delim";
			is known as a raw string literal. You can
			stuff a bunch of content in it
			note that it will take your code literally as it is between the 2 delimeters,
			whitespace (identtation and newlines) included
		*/
		lua.script(R"lua(
local container = data_container.new()
-- perform iteration
for index, value in pairs(container) do
	print("printing container's " .. index .. " index'd value:")
	local crap = value.crap
	-- iterate on 'crap'
	for value_index, num in pairs(crap) do
		-- show me
		print(value_index, ' = ', num)
	end
end	
		)lua");
	}

	return 0;
}
````

This is all powered by C++'s `begin` and `end` iterators on a container. You can also make your own class, and as long as it has proper `begin` and `end` functions that return [iterators of some kind](http://en.cppreference.com/w/cpp/iterator), sol2 will iterate it properly. This is tested with nearly every single standard library container in our tests, and with several custom containers in the tests. User code has also relied on this feature and deployed to production.

I hope this helps you.

Thanks for picking sol2. Best of luck on your journey forward.

**Comment by chrsm** [comment]
Heyo - thank you _very much_ @ThePhD for your information here. I genuinely appreciate your advice - I'm definitely a newbie and this has been very informative! You rock.
