### ISSUE TITLE
VS 2015 Express Intellisense stops responding after including sol.hpp

### ISSUE THREAD

**Issue by GekkieHenkie** [ThePhD/sol2#540]
I'm trying to add Lua support to my GameEngine/SDK, and want to use sol2 for the C++/Lua binding. I downloaded sol2 yesterday (sol2.18.3)
Sol2 works and compiles fine within my project libraries, but after I include 'sol.hpp' in my solution, Intellisense stops responding. Mouse hovers or <Ctrl>+<Space> combos do not respond, F12 (Go to definition) does not work (takes literally forever), actually anything Intellisense related does not work anymore.

Reloading the project/solution does not help, restarting Visual Studio does not help, restarting the PC does not help. But once I comment out the line:
 #include "sol.hpp"
Intellisense immediately works again without any flaws.

I've experimented (uncheck and check again) with Intellisense related IDE settings, but this doesn't help. The only thing that resolves the issue is not including sol.hpp anymore :/

My IDE Information:
Visual Studio 2015  Version 14.0.25431.01 Update 3
Microsoft .NET Framework  Version 4.7.02053
Installed Version: Desktop Express
Visual C++ 2015   00325-20000-00000-AA984

**Comment by ThePhD** [comment]
I can imagine that `sol.hpp` is quite a bit hefty on the intellisense compiler since we're using a lot of complicated template techniques. Visual Studio 2017 handles it A LOT better, and I already switched from Visual Studio 2015 (I also have a lot of RAM and an SSD).

If the intellisense exprience is not exactly helpful, there is a [blog-documented macro](https://blogs.msdn.microsoft.com/vcblog/2011/03/29/troubleshooting-tips-for-intellisense-slowness/) called `__INTELLISENSE__`, which is only defined when using the IntelliSense compiler. You can use this macro to guard code the IntelliSense compilation from things it derps on. So, wrap the `#include <sol.hpp>` in it:

````
#ifndef __INTELLISENSE__
#include <sol.hpp>
#endif // Intellisense blocker
````

It's the best I can do for you. Thanks for choosing sol2, and good luck.

**Comment by ThePhD** [comment]
Note to self: add this to docs or something...
