### ISSUE TITLE
Heterogenous operator overload for vector*scalar multiplication

### ISSUE THREAD

**Issue by phlogios** [ThePhD/sol2#547]
Not sure if this is a missing feature or if I'm misunderstanding the documentation, but I can't figure out how to make this work.
You add a usertype based on the glm::vec3 type:
```
lua.new_usertype<glm::vec3>("vec3",
	sol::constructors<glm::vec3(), glm::vec3(float), glm::vec3(float, float, float)>(),
		"x", &glm::vec3::x,
		"y", &glm::vec3::y,
		"z", &glm::vec3::z
	);
```
Then you want support for both `float*vec3` and `vec3*float` multiplications in lua, like this:
```
local a = vec3.new(1.0, 1.0, 1.0) * 5.0
-- or
local b = 5.0 * vec3.new(1.0, 1.0, 1.0)
```
Out of the box, none of these multiplications work, they just crash the application with an assertion error:
```
Assertion failed: ((!(m_counts[index] == 0)) && "Entity ID does not exist"), function get, file /Users/gustav/Development/Others/anax/src/anax/detail/EntityIdPool.cpp, line 73.
```
My solution was to add these multiplication overloads:
```
lua.new_usertype<glm::vec3>("vec3",
	...
	sol::meta_function::multiplication, [](const glm::vec3& v1, float f) -> glm::vec3 { return v1*f; },
	sol::meta_function::multiplication, [](float f, const glm::vec3& v1) -> glm::vec3 { return f*v1; }
);
```
It works, but only for the last overload defined, in this case f*v1. How can I make both of them work?

**Comment by ThePhD** [comment]
http://sol2.readthedocs.io/en/latest/api/overload.html
https://github.com/ThePhD/sol2/blob/develop/examples/overloading.cpp

From [the docs](http://sol2.readthedocs.io/en/latest/api/usertype.html#usertype-regular-function-options):
>  - "{name}", sol::overload( Func1, Func2, ... )
    - Creates an oveloaded member function that discriminates on number of arguments and types.

So,

````cpp
auto mult_overloads = sol::overload(
    [](const glm::vec3& v1, const glm::vec3& v2) -> glm::vec3 { return v1*v2; },
    [](const glm::vec3& v1, float f) -> glm::vec3 { return v1*f; },
    [](float f, const glm::vec3& v1) -> glm::vec3 { return f*v1; }
);

lua.new_usertype<glm::vec3>("vec3",
	...
	sol::meta_function::multiplication, mult_overloads
);
````

Blah blah background
=============

I only generate out-of-the-box operators for those listed in the documentation:

http://sol2.readthedocs.io/en/latest/api/usertype.html

Most notably: comparison operators, call operators, `pairs` lua calls with begin/end on containers, and `to_string` semantics. I cannot do what you want me to do in your case, because when 2 overloads exist for an operator function it is impossible for me to automatically generate that function binding for you.

At most, I could staple the signature of `operator*(const glm::vec3&, const glm::vec3&)` and try to auto-generate that, but it would likely make people confused as other overloads would never be generated by default.
