### ISSUE TITLE
Why sol::state inherit from the unique_ptr instead composition?

### ISSUE THREAD

**Issue by a1ien** [ThePhD/sol2#558]
And maybe instead pass pointer in unique_ptr define class deleter?

``` cpp
	struct lua_closer {
		void operator()(lua_State *lua)
		{
			lua_close(lua);
		}
	};
	std::unique_ptr<lua_State, lua_closer>
```
For saving memory.

And if you choose a composition maybe move unique_ptr to state_view, for saving memory?

**Comment by ThePhD** [comment]
The struct will save us memory if we keep it at the top level in `sol::state`.

If we move the `unique_ptr` to `state_view`, we have to define a deleter that takes a boolean on whether or not the state is "owning", and thusly our deleter becomes stateful and we lose any memory savings defining a struct would have brought to us in the first place.

There is no way to share the `lua_State*` with `state_view` without essentially writing 2 of the same class, which is a colossal waste of time, resources, and would double the source of top-level template instantiations.

As a side note, composition will not save us any memory. In fact, in most cases composition will cost us memory because of alignment requirements and similar. Base classes -- with empty bases -- produce 0 extra space, subject to some compiler-defined (implementation-defined) behavior between the compilers.

**Comment by a1ien** [comment]
I've touched on two topics here.
Inheriting from unique_ptr is not about reducing the size.  It's just weird. We do not need to inherit here.

**Comment by ThePhD** [comment]
When I use composition, I increase `sol::state`s size due to alignment rules and the layout of the `state`'s base class, `sol::state_view`.

When I use inheritance, I decrease the size.

How weird it is doesn't really factor in here: this is an implementation detail because nobody accesses the base to get the lua state: they go through `lua_State* lua_state() const`. We use `std::unique_ptr` here to ensure that things get destructed properly with RAII if something gets thrown in the middle of construction, and that's basically it.

Composition also comes with an implementation cost: because it is a member of `sol::state` and not a base class, I do not have the `lua_State*` ready by the time `state_view` needs to be constructed, which means I must ALSO make `state_view` a composition member. This results in `sol::state_view` no longer being available on `sol::state`'s interface: I need to either duplicate the interface or make it available on the class through a `view()` function. The first is clunky, and the second is a **breaking change**.

A potential benefit of composition is that I can put the raw state into `sol::state_view` and then just have `sol::state`'s destructor perform the deletion by grabbing the `sol::state_view`'s. I would need to be careful if something gets thrown in the constructor as the destructor for the class will not be run, and therefore I would need to either create a custom `std::unique_ptr`-like type to reference and delete the state (probably by making it a base class and then performing a cast to `sol::state*` before using that to get at the `state_view` to perform deletion -- and suddenly we're back to inheritance again, at which point this discussion is once again showing that there is only one right direction for the design here).
