### ISSUE TITLE
sol::error exception luajit x86

### ISSUE THREAD

**Issue by qfrtt** [ThePhD/sol2#561]
Hello i am crashing when sol is supposed to show the error message
here's a screenshot : http://prntscr.com/i0b44z
as you can see the error message is correct
I am using protected_function_result script_file to load my file with a sol::state lua

**Comment by ThePhD** [comment]
Sol is not supposed to show the error message. It will report it to you faithfully, depending on how you call `script_file`. The default `script_file` without any safety defines throws. Unprotected throws crash your application.

You can run `script_file` multiple different ways. They are gone over in the tutorial: http://sol2.readthedocs.io/en/latest/tutorial/all-the-things.html#running-lua-code

Note that the default, commented out in that code, will immediately throw.

Finally, LuaJIT is dangerous on 32-bit architectures because its exception propagation support is nonexistent. That is supposedly changed in LuaJIT 2.1.0-beta3 and onwards, so if you want exceptions through LuaJIT then you should be grabbing [LuaJIT 2.1.0-beta3](http://luajit.org/download.html) and compiling it using the [VS 2017/2015 Tools for x86 Command Line "Developer Command Prompt"](https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs) (commonly known from the cmd prompt as vcvarsall.bat).

**Comment by ThePhD** [comment]
It would behoove you to also turn on `SOL_CHECK_ARGUMENTS`, which triggers a define known as `SOL_SAFE_FUNCTION`. `SOL_SAFE_FUNCTION` makes it so script calls will be even safer than they are before. Details about this can be found here: http://sol2.readthedocs.io/en/latest/safety.html#safety-config

**Comment by qfrtt** [comment]
http://prntscr.com/i0cojo still crashes in the same place and doesn't write the error in the console

**Comment by ThePhD** [comment]
It works for me. LuaJIT 2.0.5, x86 and x64, Visual Studio 2017.

Code:
```
#define SOL_CHECK_ARGUMENTS 1
#include <sol.hpp>

int main() {
	sol::state lua;

	sol::state* sol_L = &lua;
	sol_L->open_libraries();

	auto result = sol_L->script("print(bad.script)", [](lua_State* L, sol::protected_function_result pfr) {
		sol::error err = pfr;
		std::cerr << err.what() << std::endl;
		return pfr;
	});
	
	if (result.valid()) {
		std::cout << "Everything went fine!" << std::endl;
	}
	else {
		std::cerr << "Everything went WRONG! Panic and stuff." << std::endl;
	}

	return 0;
}
```


![x64, Just fine](https://i.imgur.com/oThf4Aa.png)
![x86, Just fine](https://i.imgur.com/3PVuaoG.png)

Note that if you attempt to access `test` (`result` in my code) and it has a problem with it, you will invoke crash behavior under safety modes. The only thinh you can do with a bad `sol::protected_function_result` is get the error and inspect its members for additional information in safety mode.

**Comment by qfrtt** [comment]
Have changed my code to look like yours and wow it's so weird 
http://prntscr.com/i0drjy
getting "Everything went fine"
http://prntscr.com/i0drqo
but the error is still there and the debugger shows it (i still crash)
http://prntscr.com/i0ds24

**Comment by ThePhD** [comment]
`sol::function` is not safe. Use `sol::protected_function` instead.
