### ISSUE TITLE
Idea: Containers with configurable index offset

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#575]
I really don't know if this is a terrible idea or not, but it could be useful in some places. While tables generally start a 1 in Lua, it can make sense to have a different base offset sometimes. Lua already supports this e.g. like this: `array={[0]="zero", "one", "two"}`. Yes, some parts of Lua don't particularly play well with it (e.g. `ipairs`), but the possibility is there.
In my particular case, I want to expose some data that is 0-based through my API - and by that I don't mean that it is 0-based internally (which would be no good reason for doing this), but that the data is represented to use user like this, and having it 0-based in the GUI but 1-based in scripts would be inconsistent.
I know I could just use a getter function, or roll my own usertype or whatever, but I want the API to feel as "natural" to the Lua environment as possible, so I use sol2's container wrapper to make it behave like a table.
Now, my idea is that the container wrapper could look for an optional function or constant in the to-be-wrapped container which specifies the base offset to use for the container. For example, `size_t base_offset() const { return 0; } // this container appears 0-indexed in Lua`. It would then adjust the generated table/userdata to start at the specified offset. Does this sound reasonable at all?

**Comment by ThePhD** [comment]
When you say "container wrapper", you're referring to [this](http://sol2.readthedocs.io/en/latest/containers.html)?

**Comment by sagamusix** [comment]
Yes, exactly.

**Comment by ThePhD** [comment]
I'm not exactly all for breaking convention with Lua. I would rather the GUI simply be changed to work from a 1-based index, since that's how most typical humans work with things anyhow. Of course, if the GUI thing is an established convention...

I believe somewhere in the code for usertypes I do the subtraction for numeric indices automatically. I could change it to add, and then have the default implementation do `static int base_skew(lua_State*) { return -1; }`. That way, you have the full state to do whatever you want (though most people will just change that to `0`.

I'll work on documenting and implementing this, but just remember `pairs`, `ipairs`, and basic iteration functions are going to be extremely cross with you.

**Comment by sagamusix** [comment]
> I'm not exactly all for breaking convention with Lua. I would rather the GUI simply be changed to work from a 1-based index, since that's how most typical humans work with things anyhow. Of course, if the GUI thing is an established convention...

Well, in this case it would break a more than 20-year old convention on the GUI side, which I'd say is worse than having slightly non-Lua-ic (is that a word? at least non-pythonic grew to be one..) array indexing... But thanks for looking into it!

**Comment by sagamusix** [comment]
Thanks a lot, I'm going to test it right away! :)

**Comment by ThePhD** [comment]
Documented now: http://sol2.readthedocs.io/en/latest/containers.html#container-operations
