### ISSUE TITLE
Release version exception 

### ISSUE THREAD

**Issue by marfmotz** [ThePhD/sol2#577]
I use the debug version lua.lib for release version, it links !!!
I try and catch if lua has error in debug version, because some error should be ignored.
However in release version, try can't work !!! and sol throw this thing.

namespace sol {
	inline int default_at_panic(lua_State* L) {
#ifdef SOL_NO_EXCEPTIONS
		(void)L;
		return -1;
#else
		const char* message = lua_tostring(L, -1);
		if (message) {
			std::string err = message;
			lua_settop(L, 0);
			throw error(err);
		}
		lua_settop(L, 0);
		throw error(std::string("An unexpected error occurred and forced the lua state to call atpanic"));
#endif
	}

**Comment by ThePhD** [comment]
Yes. This is exactly expected behavior.

Use [`safe_script`](http://sol2.readthedocs.io/en/latest/api/state.html#state-script-safe) to get errors and handle them appropriately. Use [`sol::protected_function`](http://sol2.readthedocs.io/en/latest/api/protected_function.html#protected-function) to handle errors more gracefully when just calling a Lua function.
