### ISSUE TITLE
new_experimental_usertype: Feature Bikeshed

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#612]
Related to #538.

This is for the bikeshedding of things people want to do with usertypes. Additional runtime extensibility, de-registration, etc. are all apparently things people want to do.

On top of that, people also want to post-modify the usertype table, and do so with things that change how indexing/newindexing works, which is generally fundamentally impossible after statically binding so many pieces. This is going to require an entirely new internal implementation and a lot of finesse in order to make it work and still keep the performance of before, while also decreasing compilation times.

- [x] More fully featured runtime binding (figure out a way to get around problems with needing to accumulate properties and variables in `__index` and `__newindex` entries)
- [x] Create an explicit `metatable` type in the `sol::` namespace to facilitate overloading a function and similar with esay-to-use functions.
- [x] Monitor tuple usage and compile-time usages with the new functionality.

**Comment by OrfeasZ** [comment]
Another request: Provide a mechanism where registered usertypes automatically get a `__type` metamethod bound which returns the name of the usertype (the one passed in `new_usertype`). That way, when someone calls `type(usertypeInstance)` from lua they get back the usertype name instead of `userdata`.

It would also be nice if this was globally and individually controllable (ie. using a pre-processor definition globally or a trait for a specific usertype).

**Comment by OrfeasZ** [comment]
Another feature request: Given a `sol::object`, it would be nice to have the ability to easily check if it represents a registered usertype and get its name string.

Use-case example:
```cpp
void SomeLuaBoundFunction(sol::object obj)
{
    if (obj.is_usertype())
    {
        std::cout << "Passed usertype: " << obj.usertype_name() << std::endl;
        // ...
    }
}
```

**Comment by ThePhD** [comment]
All features except the `usertype_name()` is implemented, mostly because the name you pass in with `new_usertype` is not accessible by us anymore.
