### ISSUE TITLE
How to i get container from lua back to c++

### ISSUE THREAD

**Issue by Yu-da-xia** [ThePhD/sol2#629]
lua side:
test_arr = {[0]=3, 3, 4}

c++:
  std::vector < int > vec = lua["test_arr"];// error

**Comment by Yu-da-xia** [comment]
by using auto get back the lua return type it's:
sol::proxy<sol::basic_table_core<true, sol::basic_reference<false> >&, char const (&) [4]>

**Comment by ThePhD** [comment]
````
sol::as_table_t<std::vector<int>> wrapped_vec = lua["test_arr"];
std::vector<int> vec = wrapped_vec.source; // warning, copies
````
or
`std::vector<int> vec =lua["test_arr"].get<std::vector<int>>(); // or lua["blah"].as<...>();`

With second example, you can use `auto`.

Syntax is not ideal, but this is because C++ has some terrible rules and there's no way for me to get around them. If you want something easier to work with, you can retrieve a `sol::table t = lua["test_arr"];`, but it won't have all the clean properties and contiguous guarantees of a vector.

The type for `auto` is a proxy type that performs the conversion on-the-fly.

**Comment by Yu-da-xia** [comment]
Thanks a lot!
