### ISSUE TITLE
Passing whole doubles to C++ function expecting integer fails with Lua 5.3.4

### ISSUE THREAD

**Issue by snutt** [ThePhD/sol2#631]
Is there a way to allow passing of whole doubles to functions expecting integers without defining `SOL_STRINGS_ARE_NUMBERS`?
```
#define SOL_NO_CHECK_NUMBER_PRECISION
#include <sol.hpp>

int add(int x, int y)
{
    return x + y;
}

void main()
{
    sol::state lua;
    lua.set_function("add", add);
    lua.script("add(1.0, 2)");
}
```
Defining `SOL_STRINGS_ARE_NUMBERS` allows the above code to work, but I'd rather not allow the conversion of string to numbers.

**Comment by ThePhD** [comment]
As per [this help page](http://sol2.readthedocs.io/en/latest/safety.html), you should be able to use `SOL_NO_CHECK_NUMBER_PRECISION` and just let casting / truncating work out. Give that a try and let me know.

**Comment by snutt** [comment]
I tried that without success. I've updated my original example to include the define.

**Comment by ThePhD** [comment]
Ah, right, sorry. The keyword here is Lua 5.3.4: they changed it between Lua 5.3 and Lua 5.2 to make integers a distinct subtype (that you cannot explicitly observe with `lua_type_of`. I'll have to do some manual surgery of the code to get this to work.

I don't really have a good fix for you, in the meantime. It'll be a few days before I can push a fix because I'm working on a huge refactor of sol2...

**Comment by snutt** [comment]
OK, many thanks.

**Comment by ThePhD** [comment]
This should now work properly as of the latest sol2, without any defines or with the SOL_NO_CHECK_NUMBER_PRECISION define. Good luck!
