### ISSUE TITLE
Release link for v2.17.5 might be incorrect

### ISSUE THREAD

**Issue by ketigid** [ThePhD/sol2#633]
The file downloaded from this link https://github.com/ThePhD/sol2/releases/download/v2.17.5/sol.hpp is labelled as v2.18.0 in its comments in the `sol.hpp` file. Not sure which is correct.

I wanted to download v2.17.5 because I'm working a an older compiler.

**Comment by ThePhD** [comment]
The tags are a bit wonky: when I run the `single.py` it generates things on the last tag in the line of commits I'm working from, not necessarily what I have in the repo. That and sometimes it's 1 version ahead or behind because of how it works.

You should try the latest before you try the older version. If the latest works for you, you should use it. As a side note, the latest should still work on Visual Studio 2015. The appveyor tests for VS 2015 seem to be failing for reason unrelated to what it takes to actually compile sol2: I just haven't gotten around to getting my hands on it to know exactly why.

**Comment by ThePhD** [comment]
I checked it over: [v2.20.0](https://github.com/ThePhD/sol2/releases/tag/v2.20.0) is safe to use from Visual Studio 2015.

Best of luck with your project!
