### ISSUE TITLE
function name would be cutting?

### ISSUE THREAD

**Issue by RPG3D** [ThePhD/sol2#635]
![default](https://user-images.githubusercontent.com/7828382/39189024-c9613542-4803-11e8-953f-d25e2dc4ad92.png)

**Comment by RPG3D** [comment]
should I changed some setting to fix this?

**Comment by ThePhD** [comment]
This does not affect your code. It is just so that when Lua does certain things (like report an error), it uses the chunk name to describe it to you, so you know where the error is / what file the error came from. If it bothers, you, you can pass your own string to use for the chunk name, but this does not affect how your code runs.

**Comment by RPG3D** [comment]
thanks, another question, I want to export Unreal class to lua lke this, but it require a class for template parameter, is there some method?

	sol::table StructTable = InLua->create_named_table("tbEngineStruct");
	ForEachObjectOfClass(UObject::StaticClass(),
		[&](UObject* InObj)
	{
		//export each class
		FString ClassName = InObj->GetName();
		//how to do this ?
		sol::new_usertype<>(TCHAR_TO_ANSI(*ClassName));
		UProperty* Prop = InObj->GetClass()->PropertyLink;
		while(Prop)
		{
			FString PropName = Prop->GetName();
			sol::set_usertype(TCHAR_TO_ANSI(*ClassName), TCHAR_TO_ANSI(*PropName));
			Prop = UProperty(Prop->Next);
		}
	};);

**Comment by shohnwal** [comment]
For simple UE4 classes, like Vector, i did the following and its working perfectly fine:
```C++
	this->LuaState.new_usertype<FVector>(
		"Vector",
		sol::constructors<FVector(float, float, float)>(),
		"Size", &FVector::Size,
		sol::meta_function::addition, sol::resolve<FVector(const FVector&) const>(&FVector::operator+),
		sol::meta_function::multiplication, sol::overload(
			sol::resolve<FVector(const FVector&) const>(&FVector::operator*),
			sol::resolve<FVector(float) const>(&FVector::operator*)),
		"Normalize", &FVector::Normalize,
		"X", &FVector::X,
		"Y", &FVector::Y,
		"Z", &FVector::Z
	);
```

And for more complicated classes, like Actors or Ai controllers, i did the registering of the properties i want accessible in Lua manually, like so:
```C++

	auto aitype = serverLua.create_simple_usertype<ACustomAiController>();
	aitype.set("GetMyCharacter", &ACustomAiController::GetCharacter);
	aitype.set("MoveToLocation", &ACustomAiController::MoveToLocation);
	aitype.set("GetMoveStatus", &ACustomAiController::GetMoveStatus);
[...]
	serverLua.set_usertype("CPP_CLASS_CustomAiController", aitype );
```
From that point on pointers to ACustomAiController objects and ACustomAiController-derived objects will be recognized by lua and these registered fields are available.
 
But i guess you want to iterate over all UPROPERTIES and automatically bind all member fields? Possibly even Blueprint classes? I'm not sure if Blueprint-only variables binding to sol2 would work.

Personally, i prefer manual binding of UE4 classes to sol2, since that way you have absolute control over what gets exposed to lua.

Keep in mind though, UE4 automatic garbage collection does not recognize lua-only references, even if it's a UObject. If you create a UObject via lua and don't put in any UPROPERTY-field it'll get garbage collected and accessing it then from lua will probably result in a crash.

**Comment by RPG3D** [comment]
thanks.
I am exporting class mannually now, meet a problem anout export FString


```
tbEngineStruct.new_usertype<FString>(
		"FString",
		sol::constructors<FString(const char*)>(),
		"Len", &FString::Len,
		"IsEmpty", &FString::IsEmpty
		);

	sol::table tbTestLua = LuaAPI::SolState.create_named_table("tbTestLua");
	tbTestLua.new_usertype<LuaAPI>("LuaAPI",
		"SomeFunc", &LuaAPI::SomeFunc,
		"LogText", &LuaAPI::LogText,
		"SetText", &LuaAPI::SetText);

	LuaAPI::DoLuaCode("api = tbTestLua.LuaAPI.new()");
	LuaAPI::DoLuaCode("InWidgetID = tbEngineStruct.FString.new('TextBlock_1')");
       //at this line, the chinese text should convert to TCHAR(UE4)? but the LuaAPI::LogText(FString& InMsg) does not konw called from UE4 or lua
	LuaAPI::DoLuaCode("InText = tbEngineStruct.FString.new('hellow world, 能不能在SolLua FString中使用中文?')");
	LuaAPI::DoLuaCode("api:LogText(InText)");
	LuaAPI::DoLuaCode("api:SetText(InWidgetID, InText)");
	return true;
}

```
bool LuaAPI::DoLuaCode(const FString& InLuaCode)
{
	sol::protected_function_result LuaRet = LuaAPI::SolState.script(TCHAR_TO_ANSI(*InLuaCode),
		[](lua_State* Lua, sol::protected_function_result ret)
	{
		UE_LOG(LogTemp, Warning, TEXT("LuaCode Ret : %d"), ret.valid());
		return ret;;
	}
	);

	return true;
}


void LuaAPI::LogText(const FString& InText)
{
	UE_LOG(LogTemp, Warning, TEXT("%s"), *InText);
}
