### ISSUE TITLE
Calling a Lua function containing errors causes stack overflow.

### ISSUE THREAD

**Issue by JacobStearns** [ThePhD/sol2#65]
Calling a Lua function that contains an error causes a stack overflow and subsequent crash. If you call the function numerous times, it correctly reports the error. Continuing to call the function reports a C stack overflow, followed by "error in error handling". At this point, the lua stack grows in size and eventually, the program crashes. I am using Lua 5.3.

I did a good amount of error handling to be 100% sure that everything was working correctly. The important bit is the try-catch block in the while loop.

main.cpp:
```c++
#include <sol.hpp>
#include <iostream>

int main()
{
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	try {
		lua.script_file("example.lua");
	}
	catch (const sol::error& e) {
		std::cerr << e.what() << std::endl;
	}

	sol::function func = lua["test"];
	while (true)
	{
		// Causes stack overflow when errors are present in the function.
		try {
			if (func.valid())
			{
				func(); 
			}
			else
			{
				std::cerr << "Function is invalid" << std::endl;
			}
		}
		catch (const sol::error& e) {
			// Output the size of the Lua stack and the error message
			std::cerr << lua_gettop(lua.lua_state()) << ":\t";
			std::cerr << e.what() << std::endl;
		}
	}
}

```

These are various lua files that cause the crash.

example.lua:
```lua
function test()
	print(cat.name) -- Indexing a nil table
end
```

example.lua:
```lua
text = "Hello World!"
function test()
	print(text.x) -- Indexing a string
end
```

example.lua:
```lua
local Dog = {}

function test()
	print(Dog.bark()) -- Calling a nil field
end
```

example.lua:
```lua
local Dog = {}

function test()
	print(Dog.owner) -- printing nil fields DOES NOT cause stack overflow, as expected
end
```

Console output reporting the Lua stack size and the exception (Repeat errors omitted):
```
6:      lua: error: example.lua:7: attempt to call a nil value (field 'bark')
6:      lua: error: example.lua:7: attempt to call a nil value (field 'bark')
10:     lua: error: example.lua:7: C stack overflow
6:      lua: error: example.lua:7: attempt to call a nil value (field 'bark')
6:      lua: error: example.lua:7: attempt to call a nil value (field 'bark')
8:      lua: error: error in error handling
10:     lua: error: error in error handling
12:     lua: error: error in error handling
14:     lua: error: error in error handling
```

**Comment by ThePhD** [comment]
I guess I need to go through and exception-safety-proof the entire library. That's going to take quite some work to make sure it works...

**Comment by ThePhD** [comment]
So, after doing some testing on my own, I'm considering leaving this as-is.

If you have a file or function you expect to error and crash, you should be using `sol::protected_function` to have error handling. As I write this comment, I changed the `sol::function` type to `sol::protected_function` in your example, and no horrible stack overflows or explosions are happening.

`sol::function` overflows because it specifically does not handle safety or errors. The exception being throw is from lua's `at_panic` function, at which point the VM is ready to crash/`abort` because it's in a dead/UB state that it can't recover from when assuming the inputs and outputs will be correct.

I think the take-away for me from this is that errors throw from `at_panic` should be a separate type `panic_error`, which will signal that you should probably abort ASAP, or seriously repair the lua VM (if you know how).
