### ISSUE TITLE
Line number in exception

### ISSUE THREAD

**Issue by otristan** [ThePhD/sol2#666]
Hi,

Would it be possible to get the line number triggering an error in default_at_panic ?

I get a nice "stack index 1, expected string, received no value: bad get from protected_function_result (is not an error)"
but no easy way to understand where this is triggered from.

Thanks !

**Comment by ThePhD** [comment]
No, unless you use `protected_function` or the `safe_*` versions of the script runners so you get a traceback.

By the time it hits `default_at_panic`, stack trace information is gone.

**Comment by otristan** [comment]
Ok I understand my mistake.
I hit default_traceback_error_handler before default_at_panic where I can get this line number.

Thanks !

**Comment by ThePhD** [comment]
It is impossible for me to standards-compliantly produce a stack trace from C++. There are libraries for this but I cannot add them into sol2: if you need such a thing, pass in your own panic function and provide a stack trace for when you hit default_at_panic, which can help you with when you make a mistake in C++-land. Otherwise, run a debugger and freeze/trap/breakpoint on `default_at_panic`, before the throw happens.

**Comment by otristan** [comment]
I think I am not grasping the way it should work.

I catch exception to get the error message but those are only thrown in default_at_panic where the message is more cryptic but not in default_traceback_error_handler

Would it make sense to throw as well in default_traceback_error_handler with the complete error message when available ?

**Comment by otristan** [comment]
Looks like in my case there is an error in the lua code that get intercepted by default_traceback_error_handler but then it triggers an error in sol leading to a panic making the original error go away.
Or
It is mandatory to override default_traceback_error_handler  to get the original error message when using only exception error catch.

**Comment by davidchisnall** [comment]
Did you find a solution?  Any error in my Lua code (for example, a typo in the name of a function that I call) results in this message, and the only way of finding the cause is to add a load of print statements.  It would be very helpful of Sol could tell me at least the (Lua) line number that caused the error.

**Comment by otristan** [comment]
Latest version of Sol2 have issue with error reporting.
There is some on going work that my company has paid fo to get this fixed, but I am having trouble getting some ETA
