### ISSUE TITLE
How to get-or-create table?

### ISSUE THREAD

**Issue by TurboLed** [ThePhD/sol2#678]
Is there an easier way to achieve this?
sol::table t = lua["namespace"] = lua.get_or("namespace", lua.create_table());

This would be useful to emulate the luabind::module paradigm, where people can add functions to an existing table without having to check if it needs to be created.

**Comment by ThePhD** [comment]
Maybe `lua["namespace"] = sol::create_if_nonexistent();` and then the regular rigmarole. 

Obviously, the name `create_if_nonexistent` needs better bikeshed.

**Comment by OrfeasZ** [comment]
Maybe `sol::upsert`?

**Comment by Alloyed** [comment]
the love2d codebase uses the word 'insist' to mean 'get it, but create it first if necessary', eg. instead of graphics = getOrCreateGraphics(); it's graphics = insistGraphics(); 
It's a weird bit of jargon that gets a comment at the top of the love.h header file but once you get used to it it's very clear

**Comment by ThePhD** [comment]
I think I'm going to do `lua["namespace"].insist();`

**Comment by ThePhD** [comment]
sol3 now has much better syntax and naming for this:

https://github.com/ThePhD/sol2/issues/766#issuecomment-464393802
