### ISSUE TITLE
Deleting a sol::protected_function during its execution segfaults in sol2

### ISSUE THREAD

**Issue by Hrnchamd** [ThePhD/sol2#687]
Deleting a sol::protected_function while it is being called segfaults at lua.hpp:15090 (sol::basic_protected_function::invoke), during stack cleanup after the pcall. The this reference to lua_state and the error handler are being overwritten by new allocations.

It appears (though I can't be sure) that the sol::protected_function is held by reference to the calling variable, instead of copying. This is contrary to the expected behaviour of function pointers. If this is correct, sol should either copy whatever is necessary to clean up the lua stack after the call, or it should be documented with a warning about the sol::protected_function lifetime.

Repro:
```
#include <map>
#include "sol.hpp"

int main()
{
    sol::state lua;
    std::map<int, sol::protected_function> functions;
    lua.open_libraries(sol::lib::base);

    lua.set_function("callback", [&]() {
        functions.clear();
    });

    lua.script("function f() callback() end");
    functions[0] = lua["f"];

    auto it = functions.find(0);
    (it->second)();

    return 0;
}
```

**Comment by ThePhD** [comment]
This is expected behavior.

Your segfault is because the error handler must be stored inside of the `protected_function`. For the details of `.invoke()`, we use the error handling function (`handler_t handler;`) by-reference in order to not incur a performance penalty. The error handler object stored in the class, therefore, must remain valid so long as you are using it.

I don't think the documentation should be changed.

Your expectation goes against standard C++ practice with resources. You use a `sol::protected_function` -- in particular -- for safety and cleanup after the invocation. Deleting while in flight -- while sometimes supported by some std:: library types such as std::unique_ptr (that has a SPECIFIC note in the standard on how to handle this, it is otherwise not supported) -- is bad practice.

`sol::protected_function` does not look like, feel like, or work like a pointer, or a function pointer. I do not know how you achieved that perception. It is neither written in the tutorial nor the documentation. It is an object. Anything that is an object has a lifetime, and violating that lifetime is expressly an error unless explicitly otherwise. This is the default for any C++ object. `sol::protected_function` is an object.

It is further problematic that you are using an iterator that you then invalidate while it is still in use. If sol2 didn't segfault, your map implementation very well can: it is commonly taught not to modify a collection during its use as you can invalidate its iterators and references and cause all sorts of problems. I'm surprised this did not segfault sooner, or more explosively.

I am not willing to crash performance of the library by forcing a serialization of the handler.

Either save your protected_function to the stack with `sol::protected_function blow_up_iterator = it->second; blow_up_iterator();`, or find a way to not modify the collection mid-flight.

Small side note: if you don't need the safety or a traceback handler / error handler of any kind, `sol::unsafe_function` is probably exactly what you want.
