### ISSUE TITLE
Access violation when sol::function destructs after sol::state

### ISSUE THREAD

**Issue by JacobStearns** [ThePhD/sol2#69]
Allowing a ```sol::function``` to destruct after the ```sol::state``` it was created with causes an access violation. Keeping the state alive works, but that means you have to pay close attention when using ```sol::state``` as a member variable as the order of the variables matters (see example 2).

```C++
#include <sol.hpp>

int main(int argc, char** argv)
{
	sol::function func;
	{
		sol::state lua;
		lua.open_libraries(sol::lib::base);
		lua.script("function func() end");
		func = lua["func"];
		// lua destructs
	}
	// func destructs, causing access violation.
}
```

Or, using ```sol::state``` as a member variable:
```C++
#include <sol.hpp>

class Foo
{
public:
	void loadScript(sol::state& lua)
	{
		lua.script("function func() end");
		func = lua["func"];
	}

private:
	sol::protected_function func;
};

class App
{
public:
	void run()
	{
		bar.loadScript(lua);
	}

private:
	Foo bar;
	sol::state lua; // Swapping these 2 member variables removes access violation
};

int main(int argc, char** argv)
{
	App a;
	a.run();
}
```

**Comment by Nava2** [comment]
It'd be a "big" memory gain to store a shared pointer for the state within each sol type. The docs say that state must always out live any types returned from it. Perhaps better docs are needed? 

Alternately, sol types could hold a weak pointer to the state which is smaller than the unique one and have sol check arguments optionally check if the weak pointer is valid. Just thinking out loud.

**Comment by ThePhD** [comment]
Stepping back, ultimately this question boils down to: "What's the desired behavior if you somehow murder the lua state and then keep calling lua functions on it?"

Convention says you've done fucked up, and thusly you should crash/burn because you're essentially dealing with a "use after free" problem. That's about the best way I can think about it. Everything after this is just ramblings on why any solutions to build use-after-free checks into Sol might not work out for the library.

I will try to identify places in the docs where this kind of warning would be helpful.

__Overhead__: This is the main problem with using a `std::shared_ptr` for storing the state on all of the sol types. Sol types, as they are right now, are cheaply constructible and cheaply destructible. They're not what the C++ standard would call "trivially constructible", but their so cheap to make and destroy (and the `stack_reference` based types, like `stack_function`, `stack_table`, and friends are even CHEAPER because they store nothing in the registry) that we don't expect you to have to forward-allocate anything. Introducing shared_ptr somewhat ruins that, with control block checking for the shared pointer. This can technically be forgiven -- correctness is usually better than speed -- but this also comes at another HUGE problem which I find absolutely unacceptable.

__Lifetime guarantee problems__: Introducing a `shared_ptr` no longer makes visually-verifiable determinism easy; It SEVERELY screws up destruction semantics. Have some `sol` type somewhere you forgot to destruct? Well, even if `sol::state` goes out of scope, the `sol::` type keeps a `lua_State*` alive. If someone `new sol::whatever(...)` somewhere, that's a trainwreck waiting to happen, and an issue opened here that would be impossible to solve.

Weak references and weak pointers could help. But again, that'd require that before use, we check. And check. And check. That's a lot of runtime overhead.

It might not be acceptable to you, but I think you'll just have to be smart about where you put your member state. RAII comes at the cost of having to allocate things in the proper order, but those semantics end up giving you some guarantees you should probably take advantage of.

**Comment by ThePhD** [comment]
Another slight problem with `shared_ptr` is that it REQUIRES we force-strap people into using `sol::state` to keep their state alive (or they MUST have their own shared_ptr equivalent). This ruins `sol::state_view`, which has __all__ of the functionality of Sol built into a non-owning type that can be cheaply destructed and someone's big enterprise system that just depends on the C API can keep trucking along.

**Comment by Nava2** [comment]
What about having the protected variants use the weak checks? If someone is using the protected versions, they've already accepted a performance hit towards safety. 

Additionally, I do think exposing a weak reference to the sol state would be helpful if someone wanted to write their own semantics of this nature. 

I completely agree with your sentiments, @ThePhD; as I already said! I don't think it's logically sound to have a lua-based function called after state goes out of scope. That's asking for trouble and inconsistent memory freeing patterns.

**Comment by ThePhD** [comment]
I mean. Implementing the always-protected version means doing another base class type, and all the work associated with that....

.... <laziness intensifies> Pull requests welcome? :sweat_smile:
