### ISSUE TITLE
Missing C++-side coroutine.yield

### ISSUE THREAD

**Issue by constantcrono** [ThePhD/sol2#697]
I'm looking for the C++ side API to achieve the same result as if I called this from lua:

```lua
coro.yield()
```

I need to call it from the C++ side to implement an API that looks like (lua code):

```lua
fiber.spawn(function(ctx)
  print("Hello")
  ctx.sleep(1000)
  print("World")
end)
```

I managed to do most of the work. Script runs until the end. All fibers created are stored in a `std::vector<sol::coroutine>` to be executed _after_ the script runs until the end. Then I start iterating over the task queue calling each fiber with its own `ctx` variable. If I assign a C++ function to `ctx["foobar"]` and call it from lua, it works okay. But now, from within this C++ function (where I do have access to the proper coroutine and lua state objects), I want to yield the lua code so I can schedule other lua fibers/coroutines to run until the long-running C++ function actually finishes its work.

I've tried to find the `yield` counterpart in C++, but I had no luck. Could you give me a pointer?

**Comment by constantcrono** [comment]
In case such function does not exist yet in `sol`, here is my humble suggestion of API:

```cpp
ctx["sleep"] = [this](int msecs) -> sol::future {
  sol::future fut = sol::create_future(this->coro);
  this->registerTimerFromNow(msecs, fut);
  return fut;
};

// Later on timeout code...
fut.set(sleep_return_value); //< will block to continue script/lua execution
```

This way you won't need to worry about also preserving arbitrary C++ stack from user code because control returns to `sol2` to signalize that the lua stack should be suspended.

**Comment by ThePhD** [comment]
There is no `yield` counterpart in C++ because that is quite literally it's own language / library feature. See the current C++ coroutines TS and the much more viable and today-usable Boost.Coroutine and Boost.Fiber.

Suffice to say, what you're asking for sort of exists in the standard library: it's called `std::future`. You can combine this with `sol::yielding` -- [this issue](https://github.com/ThePhD/sol2/issues/589) describes it best. I forgot if I put a page up in the docs for `sol::yielding`...

**Comment by effolkronium** [comment]
std::this_thread::yield()

**Comment by constantcrono** [comment]
How does [`lua_yield`](https://github.com/ThePhD/sol2/commit/67116a67f952cccc5e62ae5d085bb4ed087ae940?diff=split#diff-fcef02014e96563512fc933e3c84d3faR38) works? This sounds like what I'm looking for.

> `sol::yielding` -- [this issue](https://github.com/ThePhD/sol2/issues/589)

I missed this abstraction. I was using an older release of sol (2.19.0). Now I've updated to 2.20.4 and I see it.

**Comment by constantcrono** [comment]
I've made a test and `sol::yielding` will suit my needs. I don't need a `sol::future` to inform `ctx.sleep(1000)` return value (or other blocking functions' return value). Just passing such return value to coroutine resume on the second call would work.

**Comment by ThePhD** [comment]
`lua_yield` will take your stack C++ stack and blow it up, it won't call any destructors, and probably destroy everything. It only works in C, since it executes a longjmp.

The only thing I'm thinking of adding is a `sol::yielding(...).and_then(...);`, were you get to specify a continuation function. But that's extremely advanced and probably not even worth the effort, so it's not something I'm investing time into soon.

I'm glad `sol::yielding` worked for you. Best of luck with your project!
