### ISSUE TITLE
How to call base class member functions ?

### ISSUE THREAD

**Issue by dualface** [ThePhD/sol2#70]
```cpp
#include "sol.hpp"

class A {
public:
    void say(int v) {
        printf("v = %d\n", v);
    };
};

class B: public A {
};


// ----

sol::state lua;

lua.new_usertype<A>("A", "say", &A::say);
lua.new_usertype<B>("B", sol::base_classes, sol::bases<A>());
lua.script("local a = A.new(); a:say(1); local b = B.new(); b:say(2);");

```

`b:say()` throw error:

```
attempt to call a nil value (method 'say')
```

Do i must list all base members explicitly or i am miss something ?

**Comment by ThePhD** [comment]
You need to have "say" registered for "B". We don't concatenate the metatables together, unfortunately!
````
lua.new_usertype<B>("B", "say", &A::say, sol::base_classes, sol::bases<A>());
````

If you have exceptions turned on, you don't need `sol::base_classes`, it should Just Work™.

**Comment by luoyuxiang2** [comment]
I found the problem too, very headache。We really hope you concatenate the metatables together，sometimes , those case is important and common。

**Comment by Ung0d** [comment]
Any new things made came up since Apr belonging base class member functions? Its unhandy to register every single function again and again just to use it in the appropriate derived class.

I see thats difficult to merge metatables, but I could think about a helper-method that adds the same set of base-class-methods to different derived classes (with the derived class type as template argument). This would require to append functionality to usertypes after constructing the usertype. I dont know whether this is possible?

**Comment by ThePhD** [comment]
That makes registration of usertypes order-dependent and error prone.

````cpp
lua.new_usertype<dervied>( "derived",
     "method", &derived::method
);

lua.new_usertype<base>( "base",
     "func", &base::func
);
````
`derived` was registered before `base`, and most of the information was stuffed into the lua system.  But, since we can get the metatable, we now have a bigger question: which functions should be added to `derived`? What if `base` is private? How do we detect that properly without triggering a deluge of template warnings? Do we demand users register `base` before `derived`? How do we go about concatenating the two tuples based on runtime information (e.g., which constructors get merged, which constructors do not?). Since we can't merge two tuples based on runtime information, we'd need to either transfer this information to runtime with a type-erased map or do some kind of runtime-to-compiletime tag dispatching shenanigans.

It is not worth the effort right now. Hopefully, when the SG on Reflection for C++ gets their fucking shit together, I can just reflect all public methods / variables automatically and nobody will have to deal with this horse shit.

**Comment by ThePhD** [comment]
Also of note is the performance degredation if we try to implement this is a "well, if the method is not on this metatable, just go look in the metatable of base classes".

**Comment by Ung0d** [comment]
It seems like it wasnt clear enough what I meant. (other case is I misunderstood your aswer)
I dont want to merge usertype metatables. I just want to extend them after I constructed them once.

Just wondering whether something like that is possible. What I have:
`
lua.new_usertype<base>( "base",
    //register many base class functions
);
lua.new_usertype<dervied>( "derived",
    //register the same base class methods as above
    //register additional derived stuff
);
`

What I want:
`
createUserType<base>(lua, "base"); //register base class member functions
createUserType<derived>(lua, "derived"); //register base class member functions for derived
lua.appendFunctionality("derived", 
                                       //register derived class member functions only);
`

With some helper method to avoid dublicated code:
`
template<typename T>
void createUserType(sol::state& lua, const std::string& name)
{
     lua.new_usertype<T>(name, 
                          //register base class member functions );
}
`

**Comment by Ung0d** [comment]
Thus, the existence of something like `lua.append_functionality<T>("nameOfRegisteredClass", ...functionality... );` would make my code so much cleaner.

**Comment by ThePhD** [comment]
This is going to be ridiculously hard to implement, and I can't think of a proper way to do it right now. As it stands, even your snippet doesn't make too much sense to me.

`lua.append_functionality<T> ( "name", ... )` -- How do we know what we're appending to? Is `T` set to `derived` or `base`? Fixing that would require `lua.append_functionality<base, derived>( "name_of_derived", /* additional bindings */ )`.

Going into implementation details here, we would again need to create another `usertype_metatable<derived, DerivedTuple>`, and then glue that together with the one created before that contains `usertype_metatable<base, BaseTuple>`, where the two `XTuples` are basically big blobbed lists of what was passed into `new_usertype`. We would need to correctly get out the right metatables in Lua by casting to those exactly right types, and then "append functionality". There is no easy -- or performant -- way to do this.

I understand the need to have this added to your codebase to reduce the amount of copy-paste. The most I could do is MAYBE make a function that allows you to register multiple "similar" usertypes at once, so I can do the appending all in one go for a class hierarchy. But for right now, this is not something worth the time investment.

**Comment by Ung0d** [comment]
I totally understand that. And yes, the append_functionality method as it stands is more an idea than working code. Was not sure about the implementation details of registered usertypes and whether a existing usertype could be found by string identifier or needs a template type too ect. Too bad that extending usertypes doesnt work as easy as I imagined (not really a pro in that lua table stuff).

Anyway, a "register_similar" methods sounds like a good solution for people (like me) with huge base classes that want to register some derived usertypes with just one or two additional methods and then stare at that horrible amount of dublicated code.
