### ISSUE TITLE
please document a pitfall when passing application userdata to sol::function

### ISSUE THREAD

**Issue by thinlizzy** [ThePhD/sol2#73]
After long hours of debugging, I've discovered by trial and error that I should pass the address of my objects to sol::function instances that were intended to modify my data. 
If you don't pass a pointer, the sol::function still works, but a copy is made, instead, so any changes made on the passed object by the function are not visible by the C++ application.

so code like this won't change the enemy object
```
Enemy enemy = enemyFactory(...);
auto action = lua.get<sol::function>("action");
action(enemy);
```
you need to pass a pointer instead:
`action(&enemy);`

set up snippets:
Lua `action = function(enemy) enemy:setVelocity(-3,2,100) end`
C++ `lua.new_usertype<Enemy>("Enemy", "setVelocity", &Enemy::setVelocity);`

**Comment by ThePhD** [comment]
Or `action( std::ref( enemy ) );`, but yes, we use value semantics by default for all C++-facing calls. It's mentioned in the `quick 'n' dirty` [here](http://sol2.readthedocs.io/en/latest/tutorial/all-the-things.html#c-classes-from-c) in the second half.

However, you're right in that it doesn't make it very clear in the rest of the API documentation. I'm also considering, from seeing this, that maybe _specifically_ for `sol::function` we push based on reference semantics instead of value semantics... I'm not sure if that's the right way to go, though?

**Comment by thinlizzy** [comment]
I am totally OK with value semantics as long as this is documented somewhere. Enforcing reference semantics can be a good thing if there are no valid use cases for Lua functions taking objects by value and that seems to be the current behavior of the language (ints, chars, bools by value, tables/userdata by reference).

The pitfall IMO is sol::function will work with either passing the arguments by value or by pointer/reference wrapper, but the side effects will be different according to what the caller does.

**Comment by ThePhD** [comment]
Seeing as `sol::function` is meant to emulate the semantics of the target function it ends up at, I think it stands to reason that it and `protected_function` should have "forwarding semantics". I'll work on this ASAP.

**Comment by ThePhD** [comment]
Note has been added to both table set/get and to function to make it clear what semantics are being used: http://sol2.readthedocs.io/en/latest/api/function.html#function-call-operator-function-call

**Comment by thinlizzy** [comment]
tested here and worked fine. thanks :+1:
