### ISSUE TITLE
Using char array as lua function argument and error C1060

### ISSUE THREAD

**Issue by qweasdd136963** [ThePhD/sol2#732]
**1)** Simple example:
```cpp
int main()
{
	printf("START\n");

	sol::state lua;
	lua.open_libraries(sol::lib::base);

	char str[128] = "";

	lua.script(R"(
	function test(cpp_str)
		if cpp_str == nil or cpp_str == "" then
			print("cpp_str is not exist")
		else
			print("cpp_str exist!")
		end
	end
	)");

	lua["test"](str);

	system("pause");
	return 0;
}
```
When you try to execute this code it will output: `cpp_str exist!`. Although the string is empty.

**2)** When I want to compile [this](https://github.com/qweasdd136963/OXR_CoC/blob/6d776a54bcdfe99ad472e3bb734480f04547e316/src/xrGame/key_binding_registrator_script.cpp#L59) code, build fails with message: `fatal error C1060: compiler is out of heap space.`. How to solve this problem? I tried to use `/Zm` option, but it didn't help.

Thanks!

**Comment by ThePhD** [comment]
` lua.new_enum` is prohibitively expensive on the compiler. You need to wrap each pair of key/value in braces, and then the whole list after the enum name in braces, to create an initializer list. This will drastically reduce compile times and save your heap space.

For 1), I have no idea what's going on.

**Comment by qweasdd136963** [comment]
2) Thanks.

1) String is empty but lua thinks that string is not empty.. I solved this problem adding:
```cpp
if (str[0] == '\0')
				return stack::push(L, lua_nil);
```
before `lua_pushlstring(L, str, N - 1);` [here](https://github.com/ThePhD/sol2/blob/93db30d200b592cee557ba231b053276a4e9c117/sol/stack_push.hpp#L615).

**Comment by ThePhD** [comment]
Oh, right. 

... Ugh, gross.

**Comment by Xottab-DUTY** [comment]
@ThePhD, will you fix the problem like @qweasdd136963 done, or you'll investigate it further?

**Comment by ThePhD** [comment]
The long-term fix is to call `std::char_traits<char>::strlen`. @qweasdd136963 's fix will break if the string has a single character in it. Or 2. Or 5.

The problem is I don't want to conform to the behavior where people treat character arrays as strings. I want to get away from that behavior. The problem is, C++ gives me 0 tools to do that effectively. And it sucks.

So what I'm going to do is tell everyone with embedded nulls to prepare to change their code while I add a `strlen` call in there. It's standards-conforming behavior,

even if it's shit behavior.

**Comment by Xottab-DUTY** [comment]
> `People except that because C++ has conditioned them to expect that. It's still wrong.`

The first thing C/C++ teacher should say about strings is that if the first char is `\0` then the string length is always 0.
Before you said this, I thought everyone knows about that..

**Comment by ThePhD** [comment]
Right, your teacher isn't wrong _as far as C++ is concerned_.

This is a philosophical hill that I'm dying on here, not a practical reality. The practical reality is that Null-Terminated Strings exist and that's how everything behaves. The looking-from-the-outside-in reality is that Null Terminated Strings are bizarre and crazy.

"\0foo" has 4 code units in it. But every abstraction in C++ except ` using namespace std::literals; "\0foosv` will ignore `foo`. Some view that as a feature. I view it as an anti-feature: character arrays should have been separated from what a string is from the beginning, because now I have no benefits.

This is, of course, philosophical. It isn't the reality. The reality is this is expected behavior, it's taught behavior, and it's reinforced by the standard library. It makes the type system weak and ineffectual, it makes it hard to know whether someone is well-behaved and passing in a string literal or they're just doing what the original issue at the top of this thread does: creating a local char array, manipulating it, and trying to treat it as a string.

It's a battle I won't win. But it's a philosophical hill I'd still want to die on.

**Comment by lichray** [comment]
Passing strings with embeded nulls to lua interpreter should be allowed, and let it tells us what does it think.  The standard library is happy with embeded nulls.  std::string can store them, std::string_view can see them, iostreams can print them normally, etc.
