### ISSUE TITLE
Cannot open include file: 'lua.hpp': No such file or directory

### ISSUE THREAD

**Issue by benoves** [ThePhD/sol2#742]
I'm coming from VB6 to C++ because of its native Lua support.

I'm using Visual Studio 2017.

I have built a static Lua library (.lib), version 5.3.0. Followed online tutorial, compiled without errors. File weights 2,103 KB.

Then the issues... I'm at a loss on how to implement this library in my project. I have:

1) added the lib directory in Properties > Linker > General > Additional Library Directories 
2) added the lib file name in Properties > Linker > Input > Additional Dependencies
3) downloaded the single sol.hpp header (743kb) and added it to "Header Files" in my project
4) created test.cpp in "Source Files" and added:

```
#include <sol.hpp> // or #include "sol.hpp", whichever suits your needs

int main (int argc, char* argv[]) {

        sol::state lua;
        lua.open_libraries( sol::lib::base );

        lua.script( "print('bark bark bark!')" );

        return 0;
}
```

... as in your "getting started" guide. But it fails to compile.

Do I need to have all the Lua files in my project as well, despite having a static library? I wish you'd create a project in VS2017 with sol2 and the Lua library bundled & ready to go, with some working examples. Or help me out on what I'm missing here.

**Comment by ThePhD** [comment]
C++ > General > Additional Include Paths, or something like that, for VS2017. Make sure to point it at the right directory with the header file.

**Comment by benoves** [comment]
That was quick, I'm impressed! The error persists. Here's what my project looks like, you can see a highlighted word indicating an issue:

![error](https://user-images.githubusercontent.com/46168450/50456241-46144f00-093a-11e9-9ccd-8dac16cddbc5.png)

**Comment by playmer** [comment]
Did you copy the lua.hpp file into that directory? With C++ it's not (generally) enough to just have the lib, you'll also need the header so you can get the declarations.

**Comment by ThePhD** [comment]
Okay, so `Project1/Project1` doesn't solve your problem here because `lua.hpp` isn't in there. You need the 5 Lua Header Files in order to use the Lua Library from... 5.3.0, you said?

Either way, get the 5 header files that are supposed to come with it, put them in a place your project will know to find them, and then set up that include path. The 5 header files Lua uses are:

- lua.hpp -- this is the one sol calls on
- lua.h
- luaconf.h
- lauxlib.h
- lualib.h

They are typically found in your Lua Source Distribution, so just grab any one of those and yoink those 5 files from the src/ directory.

**Comment by benoves** [comment]
Thanks guys, it compiled without errors after copying the aforementioned 5 files to the same directory as sol.hpp. They didn't need to be included in the project, just copied. I thought it wouldn't be necessary because all the LUA files were compiled into the static library, which is included as a dependency. It turns out I was wrong.

Three questions:

1. Why do I need to include the sol.hpp directory in "C++ > General > Additional Include Directories" if I have already added the file to my project (Header Files)? Seems rather pointless.
2. Why the compiled exe is so light (195kb) when the static library alone weights 2mb? I suppose only the required code(?) is extracted from it when compiling.
3. This is a console application. Can I build a GUI from this project or will I need to add something else? Just point me to the right direction.

**Comment by ThePhD** [comment]
Static librares include everything potentially ever for the binary. When your final executable, the linker knows that you don't need everything, and by default MSVC and other compilers will throw out all the functions you don't call or need (C++ is a compiled language and knows everything you will call before-hand).

You need to include it there because you use `<blah.header.file>`, which means "from the include paths". If you included using `"blah.header.file"`, it also searches the immediate local directory for the file that appears in. This is implementation-defined but all implementations behave this way, so it's de-facto how it works.

GUI applications can have consoles in them: there's nothing that prevents that from being the case. How you do the GUI is up to you, though. For heavyweight things, there's QtCreator and the entirety of the Windows C++ XAML stuff. There's dear imgui. Just look and pick from what seems like the least amount of hassle to use for your project.
