### ISSUE TITLE
Custom libraries and environment

### ISSUE THREAD

**Issue by benoves** [ThePhD/sol2#765]
There's this Lua program where you as an user can write your own custom libraries and put them in the appropriate library folder and they will load on program startup.

Functions not allowed in the environment, which is quite restrictive, becomes available if you use them in a library.

Let's say the developer doesn't add print() to an empty environment, yet a function that uses print() can be used in your custom library and will work in this environment!

----------- mylibrary.lua
function test()
   print("foo")
end
-------------------------

Running a script in this empty environment:

print("hello world") -- doesn't work

test() -- "foo"

How did he achieve this? Libraries are maintained by a few trusted people, whereas scripts are widely available and made by the community. If he didn't come up with this clever arrangement, hackers would easily take advantage and distribute malicious scripts. And yes, print() is allowed lol, I was just giving an example. The dangerous stuff, if you want, can be made available to the program only via the library.

**Comment by ThePhD** [comment]
`sol::environment` needs to be applied to all functions called through sol2. You can apply it to a whole script (and subsequently, all functions it calls) by using the object appropriately: https://sol2.readthedocs.io/en/latest/api/environment.html

It honestly just sounds like the right environment isn't being applied to the loading of the libraries, which is a user error. Make sure you're applying the same environment when loading the library and running the script, otherwise you will have failed sandboxing.

**Comment by ThePhD** [comment]
(If it's your intention to allow this, then by all means just provide the proper environment when loading / calling the library.)

**Comment by benoves** [comment]
It's my intention, yes. The problem is that if you create an empty environment and run a script with lua.script() under said environment, the print() function of the library that I loaded won't work. In other words, the environment is doing its job.

Read my post again, I edited it. Can you guide me on how to do something similar?

**Comment by ThePhD** [comment]
You'll need to write a shim function that calls into C++, loads the new environment, calls the desired function, and then returns control back to the script. (At least, that's the current way I'm thinking about it.)

**Comment by benoves** [comment]
Thanks, you're always helpful.

This is my other question, I'll be quick:

while(true) {
lua.script(R"(
print(var) -- var is a nil value the first time the loop runs...
var = "foo" -- ...but all subsequent runs var prints "foo"
)");
}

What to do to erase the stack(?) so that everytime the above code says var is nil? I don't want to destroy the sol state and create a new one because inside a loop it will produce unnecessary overhead. There must be a simple way to repeat a script ad-infinitum without maintaining variable values.

**Comment by ThePhD** [comment]
Script execution is not independent. Lua has one Virtual Machine, and one Global Table (the default environment, accessible through `lua["blah"];` or `auto g_table = lua.globals(); g_table["blah"];`). Everything has an effect on the global table if you do not explicitly scope it to the script.

For example, throw a `local` on that var, and see what gets printed.

**Comment by ThePhD** [comment]
For the shim function idea, it is a bit involved. You write a sol::environment and override its metatable with a new one that contains a `__index` (`sol::meta_function::index`) entry. Every time someone does `foo()` or `a.b.c`, it is quietly translated to `__CURRENT_ENVIRONMENT.foo()` or `__CURRENT_ENVIRONMENT.a.b.c`. In other others, the `__index` metafunction will recieve `env, key, value` arguments in that order. Get the value of `key` from the global table. Inject the "safe" env. Then call the function. Then return.

That's a very high-level overview, but that's how I would imagine doing it.

**Comment by benoves** [comment]
Overriding metable, translating to current environment, calling and returning. I think the overhead would be considerable, no?

After so many lost hours, a moment ago I had a great idea. It's easy, it's small, it's fast: since the xml settings first load the Lua scripts into strings before executing, I can just check the strings before running them for unsafe functions. In this way, I don't even need to sanitize the environment! If it contains forbidden words, like file:write (or just :write), I can pinpoint the line and say it's a nil value, like the debugger itself does with undefined variables (and functions are just that in the metatable). It will fool the ill-intentioned into thinking they can't harm others with dangerous scripts because the environment doesn't allow, and well, they really can't, but it's not because the environment forbids it! I love the way I come up with elegant solutions to my problems sometimes :D But there's a catch. Can lua.script() run obfuscated Lua code of any sort?

Regarding the previous question about the loop, using local will indeed do the job, but scripters must be told about this good practice, or else the variable will stick on the next loop and may cause problems, though it very much depends on the script.

**Comment by ThePhD** [comment]
I don't know how considerable the cost might be, honestly. I personally don't think it will matter, but I don't have your application: the only way to really know is to test and measure. My inclination is: no, it won't matter at all (especially if implemented in performant C++ code with `sol::c_call` and a raw lua function).

You can solve the loop problem by making a fresh environment for every single run. You can achieve this by clearing the environment after every run, but honestly you should just tell people to use `local` and not pollute the environment.

**Comment by benoves** [comment]
About the loop, clearing the environment would also clear the variables outside the loop, and they exist in the form of Setup variables, and maybe other scripts. I don't want to reload/run them again.

Is it possible to make a copy of the global metatable at the moment the Setup is executed when the sol::state is created, and refresh the metatable with this copy every single loop?

**Comment by ThePhD** [comment]
Create a `setup_table`. Fill it with everything you need. Create and manipulate its metatable so that it is read-only (make __new_index report an error).

Your script is about to run. Create/Cache a new environment (which is, itself, a table). Set the __index method to point to the `setup_table`. Have `__newindex` do what it normally does (set things into the environment). This sets new items into the newly-created environment variable, and passes all entries **for which no key exists in the environment** to fetch upstream in `setup_table` when performing a get.

You can stack this approach ad-nauseum and use metatables to do whatever you want, at this point, so long as you respect metatable rules. Notable: table-with-metatable-whos-index-method-is-another-table is stupid fast. This is special-cased in the Lua VM. sol2 also has an environment constructor which creates a table, takes a 2nd table as the default metatable, and marks it read-only if you so desire, so 99% of the work is done for you.
