### ISSUE TITLE
crash when iterating over std::map in lua

### ISSUE THREAD

**Issue by timofey-babitskiy** [ThePhD/sol2#769]
I'm having an issue in production which manifests itself in either crashing with SIGSEGV or throwing std::length_error or hanging eating up 100% CPU and consuming entire RAM (if left in this state). I narrowed the issue down to the following sample code:

```
#if ! defined(SOL_CHECK_ARGUMENTS)
#define SOL_CHECK_ARGUMENTS 1
#endif

#include <sol/sol.hpp>
#include <map>

struct Source
{
};
typedef std::map<std::string, Source> SourceList;

static SourceList sources()
{
   SourceList sourceList;
   sourceList["a"] = Source{};
   sourceList["b"] = Source{};
   sourceList["c"] = Source{};
   sourceList["d"] = Source{};
   sourceList["e"] = Source{};
   sourceList["f"] = Source{};
   sourceList["g"] = Source{};

   return sourceList;
}

int main()
{
    lua_State* state = luaL_newstate();

    try
    {
        sol::state_view lua(state);
        lua.open_libraries(sol::lib::base, sol::lib::table, sol::lib::io, sol::lib::math,
                sol::lib::string, sol::lib::package, sol::lib::os, sol::lib::coroutine);

        lua.new_usertype<Source>
        (
                "Source"
        );
        lua["sources"] = &sources;

        lua.script(R"(
            local getSources = function()
                local s = {}
                for sourceName, data in pairs(sources()) do
                    s[sourceName] =
                    {
                    }
                end
                return s
            end

            local i = 0;
            while i < 1000 do
                for sourceName, data in pairs(getSources()) do
                    end
                    i = i + 1
                end
        )");
    }
    catch (...)
    {
        lua_close(state);
        throw;
    }

    lua_close(state);
    return 0;
}
```

Although there is a loop in lua code, it won't crash each time, so I run this sample in an endless loop until it crashes or hangs. However if you run it under valgrind - it will find bad accesses right away.

I tested it against latest code and also latest release tag.

My production runs on ARM and uses gcc 8 cross toolchain, but sample above behaves the same on x86 gcc 8.2.0, Lubuntu 18.10.

I read docs about passing std containers to lua and using them, but maybe I just misunderstood something and not doing it right? If so, could you please advise how to use it properly or provide some fix/workaround otherwise? Thanks in advance!

**Comment by dedmen** [comment]
Where does the `sources` variable come from and what type is it and how many entries does it have?
Your sample doesn't compile.

**Comment by ThePhD** [comment]
Agree: what kind of function is `sources`? What is the function pointer you form with `&sources`?

**Comment by timofey-babitskiy** [comment]
oops, sorry, my bad. I was copying the code from my unit testing framework and missed some part of it. Just updated the sample code

**Comment by ThePhD** [comment]
## Short answer

Lifetime issues. You can make this loop work by inserting a `collectgarbage()` statement anytime in the numeric `while()` loop, and I suspect make it work by putting it in the `getSources()` function too, either during or after the loop.

## Long answer
You're creating more temporaries than I can shake a stick at, and Lua doesn't know what to do with them. Indeed: sol2's iterators are userdata, and those userdata need to have their destructor run to destroy the iterators. But, you're creating:

- at least 1000 separate userdata-based containers
- iterating through them, wherein each value is its own userdata-based container
- turning those into (empty) tables
- and then iterating through those

At some point Lua needs to destroy what `sources()` returns. The garbage collector decides to do this for me anywhere from iterations 21 to 25 in debug mode: in release, it spins for infinity and then crashes with OOM because you're creating iterators and tables and tables of tables, spawning memory in memory and the Lua VM can't destroy things faster than you make them. You're not doing it any favors by providing explicit `local` lifetimes to the things you're iterating over either: you're just dumping it right into `pairs(...)` and letting Lua just figure out on its own when it should destroy things.

Hint: it's very bad at figuring this out.

What's also important to note is that the iterators for each userdata container returned by `sources()` returns references to what's inside the container. But the container is a temporary, so you're basically asking Lua to properly deterministically destruct stuff because you have a bunch of temporaries and you're relying on Lua to keep some reasonable order of destruction (all the iterators you make, then `SourceList`, and with it the `Source`s you made).

It's not.

Solutions?

Return a `sol::table` instead of a SourcesList. This will give Lua a better understanding of what's worth destroying:

```
static sol::table sources(sol::this_state ts) {
	sol::state_view lua = ts;
	sol::table sourceList = lua.create_table();
	sourceList["a"] = Source{};
	sourceList["b"] = Source{};
	sourceList["c"] = Source{};
	sourceList["d"] = Source{};
	sourceList["e"] = Source{};
	sourceList["f"] = Source{};
	sourceList["g"] = Source{};

	return sourceList;
}
```

Note that `this_state` is transparent: you don't need to change how you call it in Lua at all: it takes 0 arguments still.

After that, there's probably some shenanigans you can do with `local` to make it work better. I don't know; the table solution seems a lot better anyhow, and probably closer to what you want.

**Comment by timofey-babitskiy** [comment]
Thanks a lot for such a detailed answer! Would the following modification of sources() function be ok either?

```
static sol::as_table_t<SourceList> sources()
{
 SourceList sourceList;
 sourceList["a"] = Source{};
 sourceList["b"] = Source{};
 sourceList["c"] = Source{};
 sourceList["d"] = Source{};
 sourceList["e"] = Source{};
 sourceList["f"] = Source{};
 sourceList["g"] = Source{};

 return sol::as_table(sourceList);
}
```

I will also revise my lua code regarding using explicit local for things I'm receiving from c++

**Comment by ThePhD** [comment]
Yeah, that should work too. You can use auto return type deduction to not specifically mark `as_table_t`, since that's kinda ugly.

**Comment by timofey-babitskiy** [comment]
Thanks again!
