### ISSUE TITLE
Should I re-export meta function in sub class?

### ISSUE THREAD

**Issue by RPG3D** [ThePhD/sol2#772]
In parent class I have exported meta function 
```
int32 ILuaSWidget::Register()
{
	sol::table* SlateTable = FLuaSlateMisc::GetSlateRootTable();

	SlateTable->new_usertype<ILuaSWidget>(
		"SWidget",
		sol::constructors<ILuaSWidget()>(),

		sol::meta_function::new_index, &ILuaSWidget::NewIndex,
		sol::meta_function::index, &ILuaSWidget::Index,

		"SetVisibility", &ILuaSWidget::SetVisibility,
		"SetTag", &ILuaSWidget::SetTag
		);

	return 1;
}
```

seemed, I have to re-export sol::meta_function::new_index/index again in sub class. ILuaSWidget::NewIndex/Index is virtual function.

```
int32 FLuaSButton::Register()
{
	sol::table* SlateTable = FLuaSlateMisc::GetSlateRootTable();

	SlateTable->new_usertype<FLuaSButton>(
		"SButton",

		sol::constructors<FLuaSButton()>(),

		sol::meta_function::new_index, &FLuaSButton::NewIndex,
		sol::meta_function::index, &FLuaSButton::Index,

		sol::base_classes, sol::bases<FLuaSBorder, ILuaSWidget>()
		);

	return 1;
}
```

**Comment by ThePhD** [comment]
This is, perhaps surprisingly, by design.

When sol does inheritance lookup, it can only safely do so for the objects you bind to it with an actual name. If I were to include `new_index` and `index` in this scheme, I would need to make sure that I call -- for every base class -- your lookup function. How would I know that your NewIndex or Index function "found" what it was supposed to and did what it needed to do, so I did not call `index` or `new_index` on the other bases?

The complexity required to make this work is enormous for what I would have to do to the backend. On the bright side, you can keep perpetually binding `ILuaSWidget::NewIndex`/`Index` and it will still call the right (virtual) function, I'm sure!
