### ISSUE TITLE
Problem with string indexing in sol table being corrupted between lua states

### ISSUE THREAD

**Issue by xzores** [ThePhD/sol2#802]
Sooo i just stated using sol2 (it works very nice), but got some really weird issues.
When i try to index a table, it is not valid, but when using the "in pairs" the table index and value show up.

I very simply have this function:
![image](https://user-images.githubusercontent.com/17770917/55511571-31460680-5661-11e9-9e46-272195f9d15e.png)

I pass a table from another lua state:
![image](https://user-images.githubusercontent.com/17770917/55511373-bb419f80-5660-11e9-9da1-2c35ce4fb574.png)

and here is the resault from the first part of the code, showing that it kinda works?
![image](https://user-images.githubusercontent.com/17770917/55511256-6867e800-5660-11e9-8af0-cae8a1167842.png)

here is how i bind the table:
![image](https://user-images.githubusercontent.com/17770917/55511470-fc39b400-5660-11e9-87e5-79b369088c9e.png)

I think there might be created some hidden charecters or something, are someone able to help?

EDIT:
I tried with using numeric indexing, it seems to work fine

**Comment by ThePhD** [comment]
You cannot pass tables, functions, whatever between states. You must explicitly serialize from one to the other, which means saving the value as a temporary (std::string) and then dumping that value out into the other state into a similar table. This question has been answered before for other forms: #750 #786.

Please explicitly serialize so you do not invoke UB;

```
sol::state_view destination_view(state);
sol::state_view source_view(t.lua_state());
sol::protected_function f = destination_view[name];

sol::object from_other_state = my_serialize_function(t, source_view, destination_view);
return f(from_other_state);
```

The `push` function here needs the state to be the same state, otherwise the call is UB (this is purely for avoiding the nullptr problem in the library). I should probably just make that function private so people don't get the wrong idea...

**Comment by xzores** [comment]
Damm that was fast. 
Many thanks, yes that sound like a good idea :)

**Comment by xzores** [comment]
Can I ask you what the difference between creating a sol table like this (without specifying any state)
sol::table some_table = create_table(narr = 0, nrec = 0)

and by passing a state like this:
sol::table some_table = create_table(LuaSate L*, narr = 0, nrec = 0)

will the sol::table without a state be able to be pushed to any state? and will the create_table with the state specified be pushed on the top of the stack?

**Comment by ThePhD** [comment]
https://sol2.readthedocs.io/en/latest/api/table.html#table-create

**Comment by ThePhD** [comment]
All sol2 operations except the ones in `sol::stack` or appropriately named as stack-atomic: everything balances to 0.

Check the examples and docs if you have further questions.

**Comment by xzores** [comment]
yes i will, thanks
