### ISSUE TITLE
Is this a memory leak? (sol2 bound usertype)

### ISSUE THREAD

**Issue by xzores** [ThePhD/sol2#803]
Hello, I am working on including sol2 in my project.
I when testing I saw that my memory went up, so i tested it with this code:
![image](https://user-images.githubusercontent.com/17770917/55667722-771ced80-5860-11e9-82a9-d66c12429523.png)

and came across this:
![image](https://user-images.githubusercontent.com/17770917/55667719-6f5d4900-5860-11e9-930a-c0e944dd0b53.png)

This is how i bind my matrix:
![image](https://user-images.githubusercontent.com/17770917/55667767-18a43f00-5861-11e9-9609-203a9babe507.png)

I keeps going up! (10 gb after 3 min)
So is this a sol2 bug a lua bug or a me bug?

**Comment by ThePhD** [comment]
It's you.

If you called "collectgarbage()" at any point you'd probably reduce the memory usage.

There are some more advanced features, such as "policies", which can help you reduce usage if you're using usertypes which return self-references. Otherwise, you're just making a bunch of new usertypes over and over and over and over and over again: this costs you the space of the matrix, plus the space allocated by Lua to hold the memory that represents the matrix (plus more).

You will need to be more efficient with your matrix operations.

**Comment by ThePhD** [comment]
https://sol2.readthedocs.io/en/latest/api/filters.html

Albeit, filters is an absolutely shit name. I think for sol3 I'll probably rename this to "policies", since that's what LuaBind calls them and it'll probably save me some teaching time.

**Comment by xzores** [comment]
ok, thanks I will take a look at it, but I did read somewhere that calling the garbage collector was not needed in lua?

**Comment by ThePhD** [comment]
Don't know; ask them, not me.
