### ISSUE TITLE
Memory consumption of new_usertype bindings 

### ISSUE THREAD

**Issue by hriekehof** [ThePhD/sol2#807]
Hi,

i wanted to ask this in gitter but i cannot find the channel anymore. So i try here.
I use sol2 in an embedded project and in general it works really great. The problem i have right now is that even small ```new_usertypes``` with only one function binded seem to consume around 4kB of RAM when using Lua 5.3. If the number of functions which are bound increase the memory consumption goes up to 8kB and more.
So my questions is, is there a way to use sol2 more memory efficient in regards to ram usage?

I just use the ```collectgarbage('count')``` function from Lua 5.3 to measure the total memory with different bindings compiled.
Beside that i'm using Lua5.3 and the GNU Arm Embedded Toolchain, arm-none-eabi-g++ 8.2.1

Thanks in advance for any comments :)

**Comment by ThePhD** [comment]
RAM consumption has not been optimized in the latest sol3; I have no advice to give here. The recent overhaul of sol3 tended towards using more runtime bits and RAM to trade off the massive compile-time pain.

Still, the memory usage seems a bit on the high side. I don't have the time right now to conduct a thorough investigation, so this will be put on hold until well into the Summer.

**Comment by ThePhD** [comment]
Also the Discord is the new place to meetup and talk about these things.

**Comment by hriekehof** [comment]
ah thanks for the quick feedback

**Comment by ThePhD** [comment]
(I'm using this place as a scratch pad for ideas.)
- [ ] Micro Space Optimization: use prefix strings for all data to avoid allocating strings with data that is identical for all but the suffix
- [ ] Minor Space Optimization: usertype_base struct is enormous: employ bitset type to reduce structural overhead
- [ ] Minor Space Optimization: references keep their own copy of the state; create a stateless_reference type for use with usertype_base to reduce the overhead by `8 * sizeof(lua_State*)`
- [ ] Major (?) Space Optimization: if the user serializes a non-callable-function, absolutely clear various table storage to reduce Lua footprint
- [ ] Major (?) Space Optimization: Small Buffer Reuse and unions and only fall back to virtual storage in case of absolute failure. NOTE! Must ensure pointers do not change addresses, otherwise breaks invariants and speed optimizations

**Comment by ThePhD** [comment]
(None of these are actionable by you, just my TODO list for things to mess around with after Finals are done.)

**Comment by hriekehof** [comment]
Just as another idea. It would be great if sol would support a const read only user type.
The code and data must be available during compile time and the `.new` constructor would not be available. 
The advantage would be, that there is only little information needed in the lua state to call methods etc. from a read only type. Most code and data could stay in rom which is great for embedded systems since there is often more rom than ram.

**Comment by ThePhD** [comment]
I've been able to program this myself but it's not something I'm interested in putting into mainline sol2. It's niche and requires me to essentially duplicate tons of code; it's the kind of thing I usually reserve for private implementations, or as an "exercise to the reader".

**Comment by ThePhD** [comment]
Small side note: you can get some of this compile-time benefit using `sol::c_call`.: https://sol2.readthedocs.io/en/latest/api/c_call.html

**Comment by ThePhD** [comment]
stateless_reference is implemented

**Comment by ThePhD** [comment]
See #1094. We'll probably be continuing there.
