### ISSUE TITLE
Compilation error in MSVC

### ISSUE THREAD

**Issue by Ok23** [ThePhD/sol2#821]
Error C1001 in file metatable.hpp(164,1).
I've tried compile 3.0.2 and HEAD.
Visual Studio 2019 version 16.1.1

**Comment by OrfeasZ** [comment]
Turn off the permissive flag (/permissive-) and try again.

**Comment by Ok23** [comment]
> Turn off the permissive flag (`/permissive-`) and try again.

Thanks, is there any way to not disable this flag ? My code base very depend this flag

**Comment by OrfeasZ** [comment]
Unfortunately no, at least not right now.

**Comment by Ok23** [comment]
Is very bad. On VS 2017 toolset no error

**Comment by ThePhD** [comment]
Upvote this issue if you want to get more visibility on the issue: it's a Microsoft problem, not exactly something I can fix at this point (I know because I've tried quite a few techniques and tricks to get around it...)

https://developercommunity.visualstudio.com/content/problem/588576/internal-compiler-error-c1001-when-using-sol3-with.html

**Comment by ross-weir** [comment]
I see that the problem should be fixed in the next update. Is the only option until then to use a different compiler? I haven't had any luck with VS2017/VS2019 but clang works fine.

**Comment by ThePhD** [comment]
Turn off the flag.

**Comment by ross-weir** [comment]
@ThePhD It fixes the internal compiler error on VS2017 only, not VS2019.

VS2017 produces a different error after doing so:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C3779	'sol::stack::stack_detail::unchecked_unqualified_get': a function that returns 'decltype(auto)' cannot be used before it is defined	lua-console-test	d:\development\sol2\single\include\sol\sol.hpp	11964	
```

**Comment by ThePhD** [comment]
I've been able to compile my tests and projects in VS by not putting in the `/permissive-` flag. If it still fails on VS 2019 that's its own seperate issue; this one is really out of my hands right now. VS 2019 v16.3 is supposed to have the fix to this issue, but that's not due to be released for some time now.

Sorry I don't have a better answer for you. Best of luck.

**Comment by ross-weir** [comment]
No problems, thanks again for the project.

If anyone else stumbles on this and is unable to compile with `/permissive-`, adding `/Zc:twoPhase-` in addition allowed me to build. (from #828)
