### ISSUE TITLE
Registering Object Instances

### ISSUE THREAD

**Issue by XBog** [ThePhD/sol2#83]
How can i register object Instances and call them in lua as follows:

lua:
`fwoosh = ship.new()
local success = fwoosh:shoot()
local is_dead = fwoosh:hit(20)`

c++:
`lua.set("ship", Ship{ });`
and now the members and functions?

the only method i got working, is with global function calls:
`lua.set_function("v2", &Ship::hit, Ship{  });`
and in lua:
`v2()`

**Comment by ThePhD** [comment]
See the example here: http://sol2.readthedocs.io/en/latest/tutorial/cxx-in-lua.html#player-script-cpp

**Comment by XBog** [comment]
Hi
```
lua.new_usertype<TT>("obj","testInt", &TT::testInt);
lua.set("obj", TT{ 77  });
```
in LUA:
`print(obj.testint)`
gives me a crash in usertype_indexing_function:prelude ..

**Comment by ThePhD** [comment]
Because you spelled it `testint` in the lua code when in the C++ code you spelled it `testInt` (note the capital letter you put in C++, but not in Lua).

**Comment by XBog** [comment]
holy moses! Sry! yes my fault. Took me hours ;)

**Comment by schnitzelK1ng** [comment]
Exiting an application after running a script with a misspelled accessor seems to cause an issue caught by iterator debugging, seemingly related to the alloc-way of destroying the fail_on_error functor during GC. Perhaps because it is using the static error functor, but tries to delete it like a regular one?

Example:
```
class A
{
public:
	int a;
};

solState.new_usertype<A>("A", "a", &A::a);
// RunScript wraps solState.script(..)  by pushing/popping an error function to avoid the luaPanic, instead prints the error.
RunScript("local test = A.new()\ntest.b = 2");
```

The above runs fine, prints the error correctly, but on appExit, iterator debugging catches a dangling pointer read access (0xffffffff) during GC.

```
_ITERATOR_DEBUG_LEVEL = 2
```
