### ISSUE TITLE
Handling of constant containers

### ISSUE THREAD

**Issue by s13n** [ThePhD/sol2#849]
I've now come up with an example of a constant container that actually should be useful to some. This container binds successfully with Sol, however there are several problems which I would like to describe further down. First, the code:

```
// Wrapper for a constant sorted associative array.
template<typename T> struct ConstTable {
    typedef char const *key_type;
    typedef T mapped_type;
    typedef std::pair<const key_type, mapped_type> value_type;
    typedef value_type const &reference;
    typedef value_type const &const_reference;
    typedef value_type const *iterator;
    typedef value_type const *const_iterator;
    typedef ptrdiff_t difference_type;
    typedef size_t size_type;

    struct key_compare {
        constexpr bool operator()(key_type const &a, key_type const &b) const {
            return ::strcmp(a, b) < 0;
        }
    };

    struct value_compare {
        constexpr bool operator()(value_type const &a, value_type const &b) const {
            return ::strcmp(a.first, b.first) < 0;
        }
    };

    template<typename X, size_type N> constexpr ConstTable(X (&a)[N]) : p_(a), n_(N) {}
    constexpr ConstTable() : p_(nullptr), n_(0) {}

    constexpr const_iterator begin() const { return p_; }
    constexpr const_iterator cbegin() const { return p_; }
    constexpr const_iterator end() const { return p_ + n_; }
    constexpr const_iterator cend() const { return p_ + n_; }

    constexpr bool empty() const { return n_ == 0; }
    constexpr size_type size() const { return n_; }
    constexpr size_type max_size() const { return n_; }

    friend constexpr bool operator==(ConstTable const &a, ConstTable const &b) { return std::equal(a.begin(), a.end(), b.begin(), b.end()); }
    friend constexpr bool operator!=(ConstTable const &a, ConstTable const &b) { return !(a==b); }

    constexpr const_iterator find(key_type key) const {
        key_compare c;
        auto it = std::lower_bound(begin(), end(), key, [c](const_reference e, key_type k){ return c(e.first, k); });
        if(it != end() && !c(key, it->first) == 0)
            return it;
        return end();
    }

    iterator insert(const_iterator hint, const value_type&) { return hint; }

    const_iterator p_;
    size_type n_;
};

// Actual sorted raw table, defined so it can be compiled into the readonly text segment.
static ConstTable<int>::value_type const table_raw[] = {
    { "cd", 17 },
    { "exit", 1 },
    { "help", -3 },
    { "lua", 5 },
    { "sort", 666 }
};

// Wrapper applied to raw table, to make it look like an associative container.
static ConstTable<int> const table{table_raw};

// Bind it using Sol.
lua["my_table"] = &table;
```

I hope the intent is clear: The table is sorted in order to use binary search for lookup, which should speed up things if the table is large (much larger than the toy example above). Even though the table is an array of pairs, it is presented to Sol as an associative array, with the expectation that it can be used like other associative arrays, except that it can't be changed.

There are a couple of things wrong with this, i.e. Sol doesn't handle them correctly:

1. A dummy `insert()` member is necessary, even though it can't be used and can't be implemented correctly.

2. The `find()` member isn't being called for ordinary lookup, i.e. when writing in Lua `my_table.help`. Instead, the code iterates through the container from `begin()` to `end()`, which obviously may be slower than using `find()`.

3. The comparison predicate `key_compare` isn't being recognised and used by Sol, therefore key comparison doesn't work when iterating through the container.

4. One would wish to be able to not provide member types `iterator` and `reference`, and have only the const versions. The non-const versions can't be defined any differently anyway, and they shouldn't have any use.

**Comment by OrfeasZ** [comment]
Sol performs some heuristics in order to automatically bind container types into lua as best as possible, and those might not always be suitable for your specific use case. You can see what sol considers when binding a container type [here](https://sol2.readthedocs.io/en/latest/containers.html#container-classifications). 

If you wish to have better control over how sol binds the functionality of your container, you can override its default implementation and provide your own for all supported operations. You can read more about how to do that [here](https://sol2.readthedocs.io/en/latest/containers.html#container-overriding).

**Comment by ThePhD** [comment]
@OrfeasZ This issue was opened as an explicit request from me due to discussion in #847; s13n knows how about the container documentation as they were the original progenitor of the feature to begin with. :D

@s13n Thanks for the write up. Requiring an `insert` seems at least somewhat wrong, since it should just error at runtime rather than enforce that function exists. I don't agree with not having `iterator` and `reference`, because that means I need to write more absolutely fantastic boilerplate gymnastics just to make it work. And I am [already doing way too much of that, to be quite honest](https://github.com/ThePhD/sol2/blob/develop/include/sol/usertype_container.hpp#L478). Someone is allowed to return not-iterator but still have a typedef of `iterator` that points to something they want the iterator to convert to, as far as I understand, and so just applying `decltype(container.begin());` and etc. etc. is wrong.

**Comment by OrfeasZ** [comment]
Woopsies 😅

**Comment by ThePhD** [comment]
I need more information from you.

I call `my_table:find(...)` and I hit the breakpoint in `ConstTable::find`. Same with other functions. What code do you write that exhibits the bad behavior?

**Comment by ThePhD** [comment]
Oh. You use `my_table.help`. Okay.

I've fixed all of it to work as expected. Pull from latest.

Have fun.

**Comment by s13n** [comment]
You are way cool, man! Thanks! I'll try this shortly.

**Comment by ThePhD** [comment]
Yeah. The `iterator` and stuff need to stay, but you can nuke the `.insert()` and you only get a soft error. `.find()` should be preferred for associative containers now too.

I haven't written the docs that really talk about the internal path for what we check because the internals are due one hell of a fat rewrite to go from a bunch of tag-dispatching tests to instead using less-convoluted `if constexpr` chains. It likely won't improve compiler performance because it's just a tree of binary decision making, but that's just something I need to keep on sol3.1's radar.

**Comment by s13n** [comment]
I've only got a vague notion of how complex this stuff is, and what you have done impresses me seriously. Writing generic code at this level in C++ has become easier with newer versions of C++, but it is still damn hard. Kudos!
