### ISSUE TITLE
Sol2 SIGSEGV when trying to copy a shared_ptr in a usertype Lambda.

### ISSUE THREAD

**Issue by Aurailus** [ThePhD/sol2#863]
Hi, I'm running into an issue with the Sol2 API. I'm creating a usertype called "LuaEntity" which derives from a struct called LuaEntity in my C++ code. I create a custom .new() function using a lambda and copy a shared_ptr into the LuaEntity class, and I then get a SIGSEGV error. Here's the relevant code:

```CPP
struct LuaEntity {
        std::shared_ptr<Entity> entity = nullptr;

        void setPos(float x, float y, float z) {
            entity->setPos({x, y, z});
        }
    };

    void entity(sol::state& lua, sol::table &zeus, LocalDefs& defs, LocalWorld& world) {
        auto model = std::make_shared<Model>();
        model->import("/home/aurailus/Zepha/mods/default/models/rabbit.b3d", {defs.textures()["zeus:default:rabbit"]});

        std::shared_ptr<Entity> rabbit = std::make_shared<Entity>(model);
        rabbit->setScale(1.f/16.f);
        rabbit->setPos({0, 40, 0});

        world.addEntity(rabbit);

        lua.new_usertype<LuaEntity>("LuaEntity",
                "new", sol::factories([&](){

                    auto entity = LuaEntity {rabbit}; //The SIGSEGV happens here.

                    return entity;
                }),

                "setPos", &LuaEntity::setPos
        );
    }
```

Tracing the segfault back shows the error is at `__gnu_cxx::__atomic_add`.

**Comment by ThePhD** [comment]
It's because [(WARNING: sound) they're all dead!](https://www.youtube.com/watch?v=GDcKbN7VHH8)

Every variable dead by the time that function is called! ☠️ 

You are capturing all of the current context by reference (that's the `[&]`). `rabbit` has already left the scope: it doesn't matter that its a `shared_ptr`. The actual object itself has been utterly and completely destroyed because the `add_entity` function has exited, and you are holding a reference to a `std::shared_ptr` whose destructor has run. We will ignore for a moment that this is an instance method and not a free function and all of the problems that could entail if you were depending on "this", since I don't see anything depending on `this` and since your function does nothing with `this`. The fix:

```
    struct LuaEntity {
        std::shared_ptr<Entity> entity = nullptr;

        void setPos(float x, float y, float z) {
            entity->setPos({x, y, z});
        }
    };

    void entity(sol::state& lua, sol::table &zeus, LocalDefs& defs, LocalWorld& world) {
        auto model = std::make_shared<Model>();
        model->import("/home/aurailus/Zepha/mods/default/models/rabbit.b3d", {defs.textures()["zeus:default:rabbit"]});

        std::shared_ptr<Entity> rabbit = std::make_shared<Entity>(model);
        rabbit->setScale(1.f/16.f);
        rabbit->setPos({0, 40, 0});

        world.addEntity(rabbit);

        lua.new_usertype<LuaEntity>("LuaEntity",
                "new", sol::factories([rabbit = std::move(rabbit)](){ // save a COPY of the rabbit
                    return LuaEntity{rabbit}; // not accessing dead memory
                }),

                "setPos", &LuaEntity::setPos
        );
    }
```
