### ISSUE TITLE
Bind functions that take a pointer to function as argument

### ISSUE THREAD

**Issue by DaedricSpartan99** [ThePhD/sol2#868]
How can I bind a function that takes a pointer to function as argument? I noticed that this example doesn't compile, then is there an other way or a workaround to do it?
`
// externally
void connect(void (*)(int)) {
     // function body
}

// lua is a sol::state
lua.set_function("connect", &connect);
`

Could std::function be a solution?

**Comment by OrfeasZ** [comment]
You can use `sol::function` or `sol::protected_function`.

**Comment by ThePhD** [comment]
You definitely want to do what @OrfeasZ said and take a `sol::(protected_)function` as the argument.

I realize there are codebases where you can't change that though. However, it's extremely difficult to un-serialize a function pointer after its been put into the Lua system. It would also mean I have to track function pointer type information, which I currently do not have to do right now, in order to make sure certain types of functions can be "converted" back to their original selves. That results in a lot of extra memory usage in a system that already uses quite a bit of runtime space in smaller projects.

**Comment by ThePhD** [comment]
Yeah, I can't do this.

The explosion of memory to track each type of function pointer and safely convert back to a function pointer (or just outright explode and crash if it doesn't match) is so **prohibitively** high. Sorry!
