### ISSUE TITLE
Custom finalizers for usertype bindings in conjunction with std::shared_ptr

### ISSUE THREAD

**Issue by s13n** [ThePhD/sol2#877]
I'm binding a usertype whose lifetime in C++ is managed with `std::shared_ptr`, and the usertype derives from `std::enable_shared_from_this`. I want to run a member function of the usertype in a Lua finalizer when Lua drops the last reference to it. At this point there may still be `shared_ptr` instances within C++ that hold the usertype object alive, so I can't call the destructor of the usertype in the finalizer. The only thing I want is lua dropping its `shared_ptr` after the finalizer has called the userdata member. A code snipped illustrates the idea:
```
struct my_usertype : std::enable_shared_from_this {
    static std::shared_ptr<my_usertype> make() {
        return std::shared_ptr<my_usertype>(new my_usertype, [](my_usertype *p){ delete p; });
    }
    void shutdown();    // implementation doesn't matter for this exposition
private:
    ~my_usertype() =default;
    my_usertype() =default;
};
```
I tried to bind this to Lua using this code:
```
lua.new_usertype<my_usertype>("my_usertype",
        "new", sol::factories(&my_usertype::make),
        sol::meta_function::garbage_collect, sol::destructor([](std::shared_ptr<my_usertype> &p){
            p->shutdown();
            p.reset();
        })
    );
```
but that leads to a runtime error.

I hope it is clear what I want to achieve. My custom finalizer takes a `std::shared_ptr` rather than a bald pointer to the class, because I want to remove the shared pointer, not my object. The object is only supposed to disappear when the last `shared_ptr` goes away, which may not be under Lua's control.

It would all happen automatically if I didn't need to call the separate member function `shutdown()` before Lua drops its last reference. The member function exists to make sure some circular `shared_ptr` references within C++ are broken in order to allow for shutdown to proceed. Not calling it would deadlock the shutdown, because circular `shared_ptr` links would prevent the destructors to be called.

So how is this supposed to be handled? How can I write a finalizer for the `shared_ptr` instead of `my_usertype`?

**Comment by ThePhD** [comment]
You don't, without a lot of effort.

sol2 puts a special deleter with the unique usertype (std::unique_ptr, std::shared_ptr, boost::shared_ptr, etc.) that calls the destructor for the right kind of "special usertype" when it is pushed into Lua. You can achieve your effect by writing a custom pusher that serializes a different function pointer of `void(*)(void*)` to be called later for that shared_ptr. The code to do so will be gnarly and involved, and you will need to ensure your memory layout matches what is shown here: https://sol2.readthedocs.io/en/latest/api/usertype_memory.html#for-std-unique-ptr-t-d-and-std-shared-ptr-t

Note that because you're overriding the deleter, which we use for fast non-DLL comparisons of unique usertypes, you will always compare false against sol2's internal deleter function and will always have slow, name-based lookup if your unique usertype for this case.

Good luck!

**Comment by s13n** [comment]
Ouch.

To put it in simple terms: Custom finalizers don't sit well with smart pointers.

OK, I guess it will be cleaner for me to have an additional handle-type usertype that incorporates the necessary functionality, and bind that to Lua. That separates the Lua-domain better from the C++ domain, instead of beating the Lua-domain into shape.

Thanks anyway, it was helpful nevertheless!
