### ISSUE TITLE
how to use object.is<T>() ?

### ISSUE THREAD

**Issue by sumneko** [ThePhD/sol2#885]
l.script("a = {}");
	sol::object a = l["a"];
	bool x = a.is<UserDataTypeCustom>();
(UserDataTypeCustom is a usertype already registed).
why x is true? Did i do something wrong?

**Comment by ThePhD** [comment]
I mean, maybe. What's the definition of `UserDataTypeCustom` look like? (Or rather, are there any special members on it like `begin()` or `end()` and stuff?)

**Comment by sumneko** [comment]
yes. it has begin and end.

**Comment by ThePhD** [comment]
Check type with `UserDataTypeCustom&`, with the ref qualifier. That might be a quick fix for now while I look into a permanent one.

**Comment by sumneko** [comment]
thx. here is another question:
	auto b = UserDataTypeCustom();
	sol::object a = sol::make_object(l, b);
        bool x = a.is<sol::table>();
x is true. An usertype is a table?

**Comment by ThePhD** [comment]
Yes. Because it behaves _like_ a table when it has `begin()` and `end()`. That is, it can behave like a table (it has accesses, returns `nil` for not-found keys, and similar).

If you want to check and be REALLY sure it's just a lua table, use `a.is<sol::lua_table>()`, which strictly type checks. You can also do `bool x = a.get_type() == sol::type::table;`.

**Comment by sumneko** [comment]
thx， it works
