### ISSUE TITLE
Can only create 8050 lua states?

### ISSUE THREAD

**Issue by xzores** [ThePhD/sol2#888]
After creating 8050 Lua states, creating a new state fails.
Why is this and can I increase the limit? or is it a bug 0-0

`
#if defined(SOL_SAFE_STACK_CHECK) && SOL_SAFE_STACK_CHECK
  
 we failed here ---->	luaL_checkstack(L, 1, "not enough Lua stack space to push this reference value"); 
#endif // make sure stack doesn't overflow
`

**Comment by ThePhD** [comment]
Seems like you're out of memory for that particular Lua state. Don't know what else to tell you?

**Comment by xzores** [comment]
well I am creating 8050 different states? så they should have thier own stack right?

**Comment by xzores** [comment]
We fail in the creation of a sol::state, the passed lua_state* is null, that is why the function fail

**Comment by ThePhD** [comment]
They can all have their own stack, but that doesn't mean the process itself has not run out of memory or that an internal Lua limit has not been reached. I don't know of any internal Lua limit, but if `luaL_newstate` fails then you are fundamentally unable to start another Lua state.

**Comment by zackpete** [comment]
This is the only result on google for this particular problem (not specific to sol2) so I figured I'd explain what's going on: after creating ~8000 Lua states (using LuaJIT 2.0 for me) `luaL_newState` starts failing due to the memory limitations described [here](https://blog.openresty.com/en/luajit-gc64-mode/#The-New-GC64-Mode). Building LuaJIT 2.1 with the `XCFLAGS='-DLUAJIT_ENABLE_GC64'` flag bypasses this limitation.
