### ISSUE TITLE
Crashed when using a sol::object created in corotinue

### ISSUE THREAD

**Issue by sumneko** [ThePhD/sol2#890]
EDIT1: Sorry, this example is incorrect, I'm creating a new example.
EDIT2: I have updated the correct example.
```cpp
	static sol::object oo;
	void UtilsProxy::Save(sol::object obj)
	{
		oo = obj;
	}
```

```lua
function CRASH()
    for _ = 1, 100 do
        collectgarbage()
        coroutine.wrap(function ()
            Utils.Save('abc')
        end)()
    end
end
```

Here I saved a sol::objec in different lua corotinue for serveral times, then Lua crashed.
Is this a bug, or there's something wrong with my usage?

**Comment by Rochet2** [comment]
You save a number and load a string. Maybe that is crashing?

**Comment by sumneko** [comment]
> You save a number and load a string. Maybe that is crashing?

I have updated the example, now it has nothing to do with `Load`.

**Comment by sumneko** [comment]
The following example does not caused a crash:
```lua
function WORKSWELL()
    for _ = 1, 100 do
        collectgarbage()
        coroutine.wrap(function ()
            Utils.Save('abc')
            coroutine.yield()
        end)()
    end
end
```
or
```lua
function WORKSWELL()
    for _ = 1, 100 do
        collectgarbage()
        Utils.Save('abc')
        coroutine.wrap(function ()
        end)()
    end
end
```

**Comment by ThePhD** [comment]
I have 2 guesses for what might be going wrong.

1. `static` objects die sometime after the program has exited. `sol::object` requires that the `lua_State*` (`sol::state`) is alive when the destructor is run at the program's end.
2. The `lua_State*` of the `sol::object` from these calls is likely the `lua_State*` of the coroutine (equivalent to a `sol::thread` and its `.state()` member). If this dies and then the object is overwritten later, it will attempt to deref the string reference you saved in the object against a thread state that is already dead.

Problem 1 is an architecture problem (don't use a `sol::object` in a `static`; that's asking for trouble).

Problem 2 is solved by using `sol::main_reference`, which always refers to the main state, which will outlive any coroutine thread state.

**Comment by sumneko** [comment]
Thanks for your detail answer, I think my issue is problem 2.
I have checked the code and example of `sol::main_reference`, found out the `sol::main_object`.
Now I changed the test code to:
```c
static sol::main_object oo;
void UtilsProxy::Save(sol::main_object obj)
{
	oo = obj;
}
```
then it seems not crashing anymore.

Can I change all `sol:: object` in my project to `sol:: main_object` to solve problem 2?

**Comment by ThePhD** [comment]
It requires any state to be initialized with sol2 or be milled through the sol2 state services: https://sol2.readthedocs.io/en/latest/api/state.html#sol-state-automatic-handlers . This is done automatically for you if you create a `sol::state` the normal way.

It's probably safe. There's a slight bit of overhead using it for EVERY single object (it looks up the main thread with regards to the current state and tests it for non-main-ness): I would recommend only doing it in places where you know you need it. Unless you have enough cycles to spare.

**Comment by EvanBalster** [comment]
After a day and a half of debugging and fact-finding, I've come around around to understanding why writing otherwise correct code in the style of Sol's tutorials leads to heap corruption if the scripts use coroutines.  That is an _enormous pitfall_ with few guardrails (from sol's safeties or otherwise).  The number of coroutine-related issues on this repo make it seem like others are falling in too.

_...Only once I found my way to [this comment](https://github.com/ThePhD/sol2/issues/890#issuecomment-552064783) was I able to find and make sense of the [thread](https://sol2.readthedocs.io/en/latest/api/thread.html) and [threading](https://sol2.readthedocs.io/en/latest/threading.html?highlight=main_object) pages, which conflate the topic with C++ threads a bit and omit any mention of `sol::this_main_state`.  Neither page appears in the table of contents and neither is the page about coroutines.  It took me a while to get my head around the idea that each coroutine has its own lua state, and any references made from those states get invalidated when it completes..._

Anyway...  I'd like to recommend adding a conspicuous link to the table of contents about **how to write coroutine-safe code**.  Not sure if that needs to be a new page.  That's a separate topic from the current coroutines page (which is about managing them from C++).
