### ISSUE TITLE
Debugger for Lua / sol2

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#908]
This is outside the scope of sol2, but I was wondering if you could recommend a Lua debugger that works with Visual Studio Code and supports sol2 well?

**Comment by RussellHaley** [comment]
I haven't tried this yet.

https://marketplace.visualstudio.com/items?itemName=devCAT.lua-debug

There is a lua patch to improve the debuggers performance. I learned about it on the Lua mailing list because someone said it was a considerable improvement. Here is the repo (also in the link above):

https://github.com/devcat-studio/lua-5.3.4-op_halt

They provide a VS 2017 solution file for building Lua as well if your on Windows. 

An excellent all-Lua alternative to VSC is [Zerobrane ](https://studio.zerobrane.com/)and it has a built in debugger. I seem to remember the phd slagging the gui once on the mailing list, but it worked well when I used it on Linux and Windows.  :P

A stand alone debugger is available here: https://luarocks.org/modules/gunnar_z/debug.lua . It's *nix only I think. I used it on FreeBSD successfully.

**Comment by ThePhD** [comment]
I don't think any debugger has built-in sol2 support. I do have some `__type` information on each usertype one can iterate and read to check things, but that's about it?

Debuggers are a bit out of scope for me because each person crafts their own, and the Lua team isn't very happy with adding core bits like `OP_HALT` to have fast, non-obscenely-intrusive debugging, so not much I can do here. Use the raw debug library intermingled with sol2 primitives and stack operations: good luck!

**Comment by Leadwerks** [comment]
I am now successfully using Lua Debugger by DevCat:
https://marketplace.visualstudio.com/items?itemName=devCAT.lua-debug

**Comment by Leadwerks** [comment]
This may be of interest to some users:
https://www.leadwerks.com/community/blogs/entry/2545-advanced-lua-debugging/
