### ISSUE TITLE
sol::optional not properly detecting invalid values with sol::table

### ISSUE THREAD

**Issue by Erwsaym** [ThePhD/sol2#909]
Hello !

I discovered an incorrect behavior with sol::optional. In fact I want to check if some variables exist in my table. The problem is that std::optional is valid everytime even if the variable doesn't exist in the table. I wrote a piece of code that reproduce the behavior. 

Lua version : 5.3.5
Compiler version : gcc 9.2.0

```#include <iostream>
#include <sol/sol.hpp>

void test(sol::table table)
{
        std::optional<int> v1 = table["v1"];
        if(v1)
                std::cout << v1.value() << std::endl;
        else
                std::cout << "NO VALUE\n";

        std::optional<int> v2 = table["v2"];
        if(v2)
                std::cout << v2.value() << std::endl;
        else
                std::cout << "NO VALUE\n";
}

int main()
{
        sol::state lua;
        lua.open_libraries(sol::lib::base);

        lua.set_function("test", test);
        const auto result = lua.safe_script(R"(
                a = {
                        v2 = 10
                }
                test(a)
        )");

        return 0;
}
```

Output : 
$ ./a.out
0
10

I think that the expected output should be :
$ ./a.out
NO VALUE
10

**Comment by ThePhD** [comment]
This seems weird. I'll check it over.

**Comment by ThePhD** [comment]
Oh, look. It's one of those things that's not my fault.

This program only prints the wrong output with `std::optional` (note the **std::**, not **sol::**). It does this because `std::optional` has an all-consuming forwarding-ref constructor on many implementations that doesn't stop from absorbing the left hand proxy because it's a type that is "convertible" to int. `sol::optional` is much more strict and its constructor set prevents implicit conversions -- which we use to simulate any-conversion and any-return-type proxies like `table["a"]["b"]` lookups that can be anything -- to have that happen.

Use `sol::optional` or manually do `.get<std::optional<int>>()` or something, it's not something I can control. :(

**Comment by Erwsaym** [comment]
Ohhh I see now ! I understand the problem.
In fact this is working now, thank you for the precision ! :)
