### ISSUE TITLE
Ideas for plugin design

### ISSUE THREAD

**Issue by Leadwerks** [ThePhD/sol2#923]
I'm thinking about a practical way to expose DLL C++ functions to Lua through sol.

Let's say we have a plugin that wraps up some of the Steamworks functions in C++ classes.
```
class Lobby
{
public:
    int CountMembers();
    bool Join()
};
```
This class is stored in a DLL the main program loads, without knowing the class definition in advance. The main program could pass the sol::state to the DLL and the DLL could expose the class with sol, but if (when) the version of sol gets out of sync between the DLL and main program there will be problems.

I know Lua can load function pointers from a DLL but it would be nicer if I could just call LoadPlugin() and have the whole plugin's API ready to use.

Any thoughts on this? It's not a deal breaker but maybe I am missing an easy option for this?

**Comment by ThePhD** [comment]
The entire `require_dll_example` has a way to load functionality -- functions, usertypes, and more -- from a DLL into a Lua library to be used by Lua: https://github.com/ThePhD/sol2/tree/develop/examples/require_dll_example

If you mean to coordinate between a main application and a DLL's C++ representation, that's strictly the realm of learning how to program against an "Application Binary Interface" (ABI) and in C++ and C those are extremely brittle, tough things to program for.

I would suggest hiding that class behind a Lua interface so you are less affected by ABI and API changes and can always fudge things later down the line.

**Comment by Leadwerks** [comment]
Interesting. Will check this out, thanks.

**Comment by Leadwerks** [comment]
Okay, I guess what I am looking for is a way to expose OO C++ classes in a DLL to Lua, without modifying the main program's source code. This would allow a Lua-only script programmer to drop a DLL in their plugins directly and start using new features without recompiling the main program.

Is there anything I should be looking at besides the built-in Lua DLL features?

**Comment by ThePhD** [comment]
Write a class that contains a bunch of functions, named as you need them. For each function, have the function body just be a `sol::(protected_)function` that is called, if it is present. In Lua, make a person provide the functions they care about to hook. Lua now has a way to interact with that class.

Add more functions when needed. DLLs made by users can only interact through handing you Lua functions, and therefore their code is always correct because they just populate known function fields. This prevents ABI issues since their code is always invoked through the (dynamic, runtime-evaluated) Lua function fields.

**Comment by Leadwerks** [comment]
> Will we have problems if there is a mismatch between the version of sol used in the DLL and the main program? Or is sol even used in the DLL?

**Comment by Leadwerks** [comment]
> Add more functions when needed. DLLs made by users can only interact through handing you Lua functions, and therefore their code is always correct because they just populate known function fields. This prevents ABI issues since their code is always invoked through the (dynamic, runtime-evaluated) Lua function fields.

Will we have problems if there is a mismatch between the version of sol used in the DLL and the main program? Or is sol even used in the DLL?

**Comment by ThePhD** [comment]
sol is a header-only library. While there are some data bits, everything does not escape your application/DLL itself. When people on the outside interact with your Lua, they just write Lua code. If they want to work with your classes in C++, you need to provide them headers which they compile against.

The Lua code is strong against ABI problems, because it's dynamically executed and resolved with names globally agreed between you and your users (sans any API changes you make). The C++ code is less strong, because you need to make sure users rebuilding their work if you exposed them to your C++ and that code changes in ANY meaningful way (object `sizeof()` changes, members are reordered, virtual functions are changed if any, etc. etc.).

If you expose the Lua, someone could use sol2 in their work and it won't bother your work unless they go trying to overwrite what you wrote (this is where `sol::environment`, sandboxing, etc. come in). There are many modders today using sol2 to do glue work where the original game does not implement sol2, and vice-versa.
