### ISSUE TITLE
Obscure error when creating new usertype with member variabe/function from wrong class

### ISSUE THREAD

**Issue by cschreib** [ThePhD/sol2#933]
I am still learning how to use sol (release 3.2, default configuration), and just wrote this today by mistake:
```c++
lua.new_usertype<player_list>("player", 
    "name", &player::name,
    // ... more stuff
);

lua.new_usertype<player_list>("player_list",
    "get_self", &player_list::get_self,
    // ... more stuff
);
```

Notice how I incorrectly specified the template parameter ``player_list`` on the first line, where it should have been ``player``. The compiler (g++ 7.4, on Linux Mint 19.3) emits a lot of error messages, with the key error being:

```
/home/cschreib/programming/cobalt/client/../lua/sol2/include/sol/call.hpp:502:25: error: invalid static_cast from type ‘client::player_list*’ to type ‘object_type* {aka client::player*}’
        object_type* o = static_cast<object_type*>(maybeo.value());
```

It took me a while to realize what the mistake was, partly because I first thought the offending line was the ``player_list::get_self`` method, which returns a ``const player*``, and I thought maybe this was confusing sol somehow (I just migrated from using the original ``sol`` library which had a number of bugs...). I didn't notice the exact origin of the error because the amount of errors generated on the terminal was huge (to include the full template instantiation backtrace).

It would have been easier if there had been few errors generated and an explicit message. For example a ``static_assert`` somewhere inside ``new_usertype<T>``, or one of the intermediate types used internally, could make sure that member variables / functions have an object type that is a (base of) ``T``. This is written in the documentation as a requirement, but it is not explicitly enforced by the code.

**Comment by ThePhD** [comment]
Ubfortunately, a static assert above that line is less-than-useful as far as amount of template error spew ,since it'd still be a giant template spew. (But I could write a better error message.)

It'd come from mostly the same place, though, because you _can_ put completely unrelated class methods in `new_usertype` with some trickery. I just don't quite advertise that you can.

I'll try to figure out a proper error. :D

**Comment by ThePhD** [comment]
So I don't think I can _actually_ fix this for you, at least not in all cases.

The problem is that people can -- and do -- bind member functions and functions of types not related to `player` on the `player` type. This would break this code, pretty handily. So I have to be careful about how vigorously I error in this case. I've added some static asserts that I think are safe and will not break anyone.

**Comment by ThePhD** [comment]
Compiler should yell at you more now. :D

**Comment by cschreib** [comment]
Thanks! :)
