### ISSUE TITLE
Unique usertype persisting after being destroyed externally

### ISSUE THREAD

**Issue by alexdevteam** [ThePhD/sol2#944]
I have had a problem that has been driving me crazy for the past 3 days. Apparently, destroying an unique usertype from a C function called from lua will _not_ make it check if the pointer for it has changed to null, making UB possible.

The smallest MCVE i could come up with is relatively long (115 lines), since it requires setting up unique usertype traits. In it, I define a `Button` class, which will be the target unique type, and a custom pointer for it (`ButtonPtr`). After defining the unique usertype traits for `Button`, I create an example optional variable `button_instance` that will hold one single button. I create this button, giving it some value (In this case, a string), and then run the lua script.

The lua script provided deletes the button calling the externally-defined `delete_button` function that resets `button_instance`. Here's where the error happens: Sol3 thinks that the button _still exists_ on the pointer given, which results in undefined behaviour when trying to access the button's text.

Here's the code: https://gist.github.com/alexdevteam/b6822616755e961889027e06db353463
And the output:
```
Button copied (constructor) -> 	Destroyed button.
Created button, address: 0x561299c6f6c0
get() called!
[script] Deleting...
[delete_button] Deleting button
Destroyed button.
[script] From inside:
	Button is (should be nil!): sol.sol::detail::unique_usertype<Button>: 0x56129a8a9b38
	Is button nil?: false
	Button's text is... (Should return index from nil error!): @���V   
������V  _
Is the buttonPtr nullptr right now: true
[script] From outside:
	Button is (should be nil!): sol.sol::detail::unique_usertype<Button>: 0x56129a8a9b38
	Is button nil?: false
	Button's text is... (Should return index from nil error!): @���V   
������V  _

Process finished with exit code 0
```

I'm using CLang on Manjaro Linux, latest sol2 master branch and CLion (which should not influence in the test at all.)

**Comment by ThePhD** [comment]
### Short version

The userdata, stored in Lua, is a pointer value separate from your button pointer instance, stored _inside_ the Lua userdata. Lua's userdata lifetime is bound to its GarbageCollector, not to when you call a C++ function.

### Long version

You deleting the button in C++ does nothing about the button pointer that you set into Lua with `button = self`. You're accessing that `button` global variable rather than a script-specific or instance-specific button. Lua will keep a shallow reference to the userdata (your class instance) that you passed in as `ButtonPtr`.

`get()` is only called on first passing it into the script: it is part of the interop layer, not the general `a.foo` syntax in C++. This is evidenced by the fact that the button **userdata** value (the `0x56129a8a9b38`) is still the same each time you print it out. (The printed value is not your button's pointer value, but the pointer value Lua gives it in the VM.) If you are using Lua 5.1/LuaJIT, no `operator==` will be called for `button == nil` because they are not the same type, and there is nothing I can do to help you there (otherwise, I could automatically help you there).

`button` is pointing to a `ButtonPtr` instance that is recklessly and rogue-ly accessing dead data, because deleting the button in C++ does not remove it from Lua's GarbageCollector or make the userdata value nil.

**Comment by alexdevteam** [comment]
Thank you for your quick response.

> `button` is pointing to a `ButtonPtr` instance that is recklessly and rogue-ly accessing dead data, because deleting the button in C++ does not remove it from Lua's GarbageCollector or make the userdata value nil.

So would passing `ButtonPtr` by reference in `delete_button` to set its value to nil work? Would collecting garbage work? I tried both things in the past but none worked, I still have to do a MCVE for them though.

**Comment by ThePhD** [comment]
No. You'd need to blow up the actual Lua variable in order for "button" to be nil. That means doing `button = nil`, in Lua code. There's no way for C++ to do this, and no way for a Lua function through a variable to help. You can structure something that contains a reference to a pre-existing `sol::reference`/`sol::object` and do aliveness-checks before invoking methods, or erroring, but that's a lot more effort.
