### ISSUE TITLE
can't catch sol::table access not exist key error. 

### ISSUE THREAD

**Issue by yezhulove** [ThePhD/sol2#960]
- vs2019 with c++17  
- lua 5.3
- latest sol2 release version

sol::table  access not exist key. trigger lua error. but detail::clean sentry in traverse_get_single clean the error message at top of stack and leave nil on stack.

## test code
```c++
#define SOL_ALL_SAFETIES_ON 1
#define SOL_USING_CXX_LUA  1
#define SOL_NO_COMPAT 1
#include "sol/sol.hpp"


// vs2019 with c++17  
// lua 5.3
// latest sol2 release version

int main(int, char* []) {
    std::cout << "=== calling lua functions ===" << std::endl;

    sol::state lua;
    lua.open_libraries();

    lua.set_function("demo", [](sol::table t) -> void {
        t.get<int>("not_exist"); // access not exist key. trigger lua error.
                                 // but detail::clean sentry in traverse_get_single clean the error message at top of stack and leave nil on stack
    });

    sol::protected_function_result pfr = lua.safe_script("demo({x = 1})", &sol::script_pass_on_error);
    //c_assert(!pfr.valid());
    sol::error err = pfr; // will panic
    std::cout << err.what() << std::endl;
    std::cout << std::endl;
    return 0;
}
```

**Comment by ThePhD** [comment]
I'm not sure if this should propagate the error up through the stack here. This feels like you should be using

```
t.get<sol::optional<int>>("not_exist");
```

to guard the access. When the function returns we cannot transport the error that happens here because Lua panics and longjmp's, or throws an exception (when built as C++) that we are not allowed to catch. In either case: panics/exceptions cannot escape your code -> Lua -> more C++, and the trampoline handling it cannot know how many layers you've violated.

Sorry, you'll need to use the optional syntax and guard your C++ access.
