### ISSUE TITLE
DeepCode found possible bugs

### ISSUE THREAD

**Issue by patlecat** [ThePhD/sol2#976]
Running deepcode it found 4 possible problems and 2 recommendations (DeepCode):

Link to report: https://www.deepcode.ai/app/gh/ThePhD/sol2/e09d2ffef8f4edb1e67aef881c6ad3c58a30c5d6/_/dashboard

**Comment by ThePhD** [comment]
I can't access the report without giving DeepCode permissions, which is weird.

**Comment by ThePhD** [comment]
To be clear, I'm not giving DeepCode those permissions for this repository or my account.

Feel free to open up a new issue with the report pasted in plaintext, however hideous it may look!~

**Comment by Rochet2** [comment]
The warnings seemed to be about the examples. Such as conditions being always true and vector written to but never read from. So I would consider them false positives.

One of the suggestions was to use a guard in this example code instead of lock and unlock
```cpp
std::shared_ptr<SomeLib> SomeLib::getInstance() {
	static std::weak_ptr<SomeLib> instance;
	static std::mutex m;

	m.lock();
	auto ret = instance.lock();
	if (!ret) {
		ret.reset(new SomeLib());
		instance = ret;
	}
	m.unlock();

	return ret;
}
```

And the other suggestion was to use empty() instead of size() here
```cpp
std::ostream& operator<<(std::ostream& os, const automatic& right) {
	if (right.size() == 0) {
		os << "{ empty }";
		return os;
	}
```

Here is a summary of the report:
![image](https://user-images.githubusercontent.com/468816/83953793-174b1980-a84c-11ea-9925-a98aa9f40a28.png)
