### ISSUE TITLE
Killing the code from the outside...

### ISSUE THREAD

**Issue by isvogor-foi** [ThePhD/sol2#977]
Hi,

I was just wondering whether, once you send lua code to be executed... So I have a C++ program which loads lua code, which does things. ... Is it possible to kill lua code in mid execution from C++? Is there any handle to lua? For instance, something like

lua.Abort() .... where lua is the object of sol::state.

Thanks!

**Comment by isvogor-foi** [comment]
Hi again! Thanks for your reply and patience!
Hm, std::terminate() would stop my entire program, and I have a c++ program
which is like a "player" of Lua programs.
Well, let me describe my situation. So, as I pointed out, I use Lua as
Domain Specific Language (DSL), however, some specific functions I have
implemented in C++ and then I expose those objects to Lua. So, I use Lua's
language constructs, but I make it control stuff, through C++ objects. So
my program would be, simplified, like this:
if my_cpp_object.successful() == 1 then
  my_cpp_object2.doStuff()
end
However, my code can get stuck in "my_cpp_object" implementation. So, what
do I do? I use the debug function form Lua, and after each line of code
executed, I check whether everything is ok, by evaluating my observers. If
some of them report an error (i.e. in the my_cpp_object I raise an event on
a dispatched thread if stuff goes wrong). So, since the debug function from
Lua only triggered when the line of code is changed, and my C++ object is
stuck, I have everything stuck.
My option is to, either create another controller thread (because I don't
want a full stop of my C++ management program, I just want to restart Lua),
or... I would benefit from lua.Abort() which would terminate Lua execution.
So, I could catch that event and restart...
I might be nitpicking here, but I was mostly wondering what would be the
best approach in the spirit of Sol2... I have alternatives, as you
suggested, or as I pointed out with some monitoring threads, but it seems
to me that Abort function would be a perfect and clean solution. Am I
missing something?


Cheers!

**Comment by ThePhD** [comment]
You're missing the part where, if you can't jump out of the code...

how do you expect me to jump out of _your_ code?

"Steal execution from a process and kill it" is the domain of the operating system: "just implement a Lua abort" is not something I can "just" do, and it does not even help here because it's not the Lua machine that's stuck, it's YOUR code. How can you expect me to literally freeze your program's execution at some arbitrary and undetermined time when I am not the operating system responsible for system resources?

Fix your program's infinite loop, then throw an exception to immediately get out with unwinding if you're inside a Lua call, or something else. Use a real debugger to figure out why your "code is stuck" (it should not be, you are in control of that, please take the time to figure it out and don't fork that responsibility onto me, a library maintainer). Or, implement the controller thread and do the (very dangerous) act of doing work on a single thread with a handle you can invoke a kill on.

**Comment by isvogor-foi** [comment]
Hi,
I am sorry if I agitated you with my comments. By no means do I insist that
you implement the abort function, I was just wondering why it doesn't
exist. I know that you probably have good reasons, I just wanted to
understand a bit more... With your response, I think I do.
I know that there is an issue from my end, and I've been using your library
for two years now, and it has been a great and reliable tool for me. So
thanks!
The thing is, that from my end, abort would be a simple and, to be fair, a
dirty fix. But, you are right, there is a lot of ways I can prevent
this from happening.

Thanks for your patience, keep up the good work!
Cheers!

**Comment by sagamusix** [comment]
Maybe you could consider using Lua's instruction count hook:
```
lua_sethook(lua, HookFunc, LUA_MASKCOUNT, 1000); // interrupt Lua execution after every 1000th Lua VM instruction

static void Hook(lua_State *L, lua_Debug *)
{
	if(some_external_condition_indicates_that_the_code_should_terminate)
		luaL_error(L, "STOP!");
}
```

**Comment by isvogor-foi** [comment]
Hi,
thank you for your response. I already use debug hooks, however, as you
pointed out the instruction hook, I think I'll refresh my memory on Sol2
internals and hooks. As ThePhD pointed out, and as I am aware, the problem
is from my side, and I will solve it. From my understanding, it was
intuitive that stopping Lua execution would exist, however, I need to look
into it a bit more to find out why I am wrong! Anyway, you've guys been
cool, and thanks for the support!

Cheers

**Comment by Fighter19** [comment]
@sagamusix Thank you! This is exactly, what I required.
Unfortunately, it appears as if raising an error within the hook, prevents the hook from being reusable, at least with Sol.
(L->allowhook does not get reset, because the exception handler leaves that function.
But it somehow should be doable, as the normal Lua CLI also does it that way.
There it's being reset in luaD_pcall)



Generally, regarding this topic:

I don't think that this has to be a developer problem.
I intend to provide a scripting API for an application for users at some point.
And unless I want to over engineer everything, running Lua in the same thread as the rest of the code is necessary.
(Otherwise, I'd have to launch a new thread just for Lua, then create message dispatchers that look like the "real" class, then synchronize these to the main thread)
So this conflict, between stability even though user scripting is enabled and code maintainability is perfectly alleviated with just having this timeout.

A very specific example here, a user provided blitting function should not take longer than 100ms. If it does, we're already way past acceptable limits. The whole application would be frozen beyond repair, by just one bad user script. By limiting it to 100ms, I can ensure, that the application at least does not completely freeze and remains usable aside from visual bugs.

**Comment by Fighter19** [comment]
Alright, so I got it working this far, by setting up a timer using SIGEV_THREAD_ID on Linux, to trigger only on the Lua thread (quite possibly optional, but I'd prefer to avoid data races), then install a hook to execute on the next instruction.
Then on that instruction I check if the time has actually passed (also quite possibly optional, as the timer has been setup already, but knowing signals, spurious wake-ups might be a think).
When the time has passed, I put an error on stack and remove the hook.

For this to work, it's necessary to use a protected function, as otherwise the exception handler will make it jump out of the hook handling code and prevent us from re-entering, as allowhook is never set back to 1.

Like this, I managed to get a kill timer working.
