### ISSUE TITLE
Reloading code loaded from script files.

### ISSUE THREAD

**Issue by TerensTare** [ThePhD/sol2#980]
I have a script file named `script.lua`, which contains some global functions. On the `main` function, I deal with `script.lua` in this way:
``` c++
sol::state lua_;
lua_.open_libraries(sol::lib::package);
auto game{lua_.require_file("game", "./script.lua")};
auto func1{lua_["func1"]};
MyFileType script{"./script.lua"}; // A custom file handle

bool loop{true};
while(loop)
{
  if(shouldExit)
    loop = false;
  
  if(script.changed()) // compare last write time to check if file has been modified
  {
    lua_.script(R"(
      if package.loaded["game"] then
        package.loaded["game"]= nil
      end
    )");
    game = lua_.require_file("game", "./script.lua");
    func1 = lua_["func1"];
  }

  func1();
}
```

As long as `script.lua` remains unmodifed, everything is ok, but when I save any modifications made to `script.lua`, the programs stops as soon as it reachs the `func1()` call. I surrounded the code from `lua_.script` to the `func1` assignment with `try`/`catch` and print any exception that is caught, but no exception was ever thrown, even on modifying. I also added `lua_.script("if func1 == nil then print "Invalid" end");` before re-assigning `func1` on file change, but the snippet never prints anything (meaning `func1` is not `nil`). Am I doing anything wrong?

**Comment by ThePhD** [comment]
"require file" packages and caches things. What you're looking for is a hard reload. Setting `package.loaded` might not be enough because different versions of Lua store that information in lots of different places, not just one. `require_X` calls should take an additional parameter that says "override no matter what", which may help. Similarly, if you're just going to bulldoze the contents anyways, why use `require` when you can just call `script` or `script_file` instead?

**Comment by TerensTare** [comment]
I just got the chance to retry the code with your suggestions (I removed the `game` variable, used `script_file` instead of `require_file`, and put the `script_file` call inside a `try`/`catch` block, which prints any caught exceptions). As soon as I modify `script.lua`, `lua: error: error in error handling` gets printed on the console.

**Comment by ThePhD** [comment]
Okay, so that took way longer than it should have to figure out. The problem is this line:

```
auto func1{lua_["func1"]};
```

The problem is `auto`. `auto` resolves to exactly the type of `lua["func1"];` -- this is a proxy type, not a real function anchored in reality. Change it to `sol::protected_function` and everything is fine.
