### ISSUE TITLE
Retaining a table

### ISSUE THREAD

**Issue by 5ladimir** [ThePhD/sol2#994]
I believe it is not a bug but rather misunderstanding, maybe it is worth yet another example.

I am trying to store sol::table variable as class member:

```cpp
// Storing
sol::state_view lua{state};
sol::protected_function_result rslt = lua["functionName"] (state, ...);
if (rslt.valid())
	m_table = rslt.get<sol::table>(0);  // sol::table m_table member variable
```

Then later I use it:

```cpp
// Usage
m_table["fooFunction"](state, ...);
```
As my current understanding sol::table adds reference for me to ensure lifetime, but from the random faults what I am experiencing the table is gone. Also a workaround for this makes me feel it is lack of a reference:

```cpp
// Storing
sol::state_view lua{state};
sol::protected_function_result rslt = sol::state_view{ state } ["functionName"] (state, ...);
if (rslt.valid())
	lua["g_tbl"] = rslt.get<sol::table>(0);
```
```cpp
// Usage
lua["g_tbl"]["fooFunction"](state, ...);
```

So, the question is how to store table value in C++ way?
Thanks in advance
Vladimir

**Comment by ThePhD** [comment]
Are you sure that the result is valid? If `rslt.valid()` is false, you'll skip the `m_table` initialization. That might fail you. You should print something or exit of the code fails on you, so you can properly diagnose an error rather than just continue on even if it fails.

Other things to make sure of: is there always an existing Lua State? Does the Lua State ever go out of scope and die? A small, simple, compilable example could help me help you better.

Minor notes:
- Why do you keep passing `state` as the first variable? Is that required? sol2 doesn't need you to pass the state to it, so if your function doesn't need that state variable that is extra work on your behalf.
- I don't understand what you're trying to do here.
- Why are you explicitly passing `0` into `get`? You don't need to be passing that.

**Comment by 5ladimir** [comment]
I'd like to have c++ equal to

g_obj = createObj();

function onCallback()
    g_obj:foo();
end

createObj constructs a complex table object with metatables. I can't post it here just because it's 3rd party software I don't know what it is exactly. My guess, it is compiled dll module. Maybe the problem is that the sol::table does not suite storing a table with metatables.

**Comment by ThePhD** [comment]
`sol::table` works fine with metatables. I think your problem in this case lies elsewhere, or with the syntax of how you are calling the object. Note that to call `g_obj:foo();` in C++ using sol2, you need to do

```cpp
sol::table g_obj = lua["g_obj"];
g_obj["foo"](g_obj);
```

You must pass "self". `g_obj:foo(rest_of_args...);` is syntax sugar in Lua for `g_obj.foo(g_obj, rest_of_args...);`

**Comment by 5ladimir** [comment]
Hi, 

So, finally, the solution was:

class Foo
{
	// sol::table m_table;
	sol::**main_table** m_table;  // Now the table referenced "properly", at least faults are rare
};

...
m_table = GetTableFromSomewhere();

Looking up the source, the difference is basic_reference<false> vs basic_reference<true>. Still it is vague. It would be nice to have docs about sol::table, sol::main_table, sol::stack_table etc

Vladimir
